/* Generated by wayland-scanner 1.25.0 */

#ifndef LUNA_WM_V1_CLIENT_PROTOCOL_H
#define LUNA_WM_V1_CLIENT_PROTOCOL_H

#include <stdint.h>
#include <stddef.h>
#include "wayland-client.h"

#ifdef  __cplusplus
extern "C" {
#endif

/**
 * @page page_luna_wm_v1 The luna_wm_v1 protocol
 * Luna private window placement
 *
 * @section page_desc_luna_wm_v1 Description
 *
 * Private extension advertised only by the Luna compositor.  Standard
 * xdg-shell forbids absolute toplevel placement; this interface restores
 * SetWindowPos / GetWindowPos semantics for Luna-session clients (aplay,
 * luna-ui) that already know they are talking to Luna.
 *
 * @section page_ifaces_luna_wm_v1 Interfaces
 * - @subpage page_iface_luna_wm_v1 - factory for absolute toplevel placement
 * @section page_copyright_luna_wm_v1 Copyright
 * <pre>
 *
 * Copyright © 2026 Yuichiro Nakada / Project Vespera
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice (including the next
 * paragraph) shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 * </pre>
 */
struct luna_wm_v1;
struct wl_surface;

#ifndef LUNA_WM_V1_INTERFACE
#define LUNA_WM_V1_INTERFACE
/**
 * @page page_iface_luna_wm_v1 luna_wm_v1
 * @section page_iface_luna_wm_v1_desc Description
 *
 * Global singleton.  Clients bind it when present and use set_position /
 * get_position against their own mapped xdg_toplevel wl_surfaces.
 * @section page_iface_luna_wm_v1_api API
 * See @ref iface_luna_wm_v1.
 */
/**
 * @defgroup iface_luna_wm_v1 The luna_wm_v1 interface
 *
 * Global singleton.  Clients bind it when present and use set_position /
 * get_position against their own mapped xdg_toplevel wl_surfaces.
 */
extern const struct wl_interface luna_wm_v1_interface;
#endif

/**
 * @ingroup iface_luna_wm_v1
 * @struct luna_wm_v1_listener
 */
struct luna_wm_v1_listener {
	/**
	 * current absolute content position
	 *
	 * Sent in response to get_position. Coordinates match
	 * set_position.
	 */
	void (*position)(void *data,
			 struct luna_wm_v1 *luna_wm_v1,
			 struct wl_surface *surface,
			 int32_t x,
			 int32_t y);
};

/**
 * @ingroup iface_luna_wm_v1
 */
static inline int
luna_wm_v1_add_listener(struct luna_wm_v1 *luna_wm_v1,
			const struct luna_wm_v1_listener *listener, void *data)
{
	return wl_proxy_add_listener((struct wl_proxy *) luna_wm_v1,
				     (void (**)(void)) listener, data);
}

#define LUNA_WM_V1_DESTROY 0
#define LUNA_WM_V1_SET_POSITION 1
#define LUNA_WM_V1_GET_POSITION 2
#define LUNA_WM_V1_START_MOVE 3
#define LUNA_WM_V1_SHOW_WINDOW_MENU 4

/**
 * @ingroup iface_luna_wm_v1
 */
#define LUNA_WM_V1_POSITION_SINCE_VERSION 1

/**
 * @ingroup iface_luna_wm_v1
 */
#define LUNA_WM_V1_DESTROY_SINCE_VERSION 1
/**
 * @ingroup iface_luna_wm_v1
 */
#define LUNA_WM_V1_SET_POSITION_SINCE_VERSION 1
/**
 * @ingroup iface_luna_wm_v1
 */
#define LUNA_WM_V1_GET_POSITION_SINCE_VERSION 1
/**
 * @ingroup iface_luna_wm_v1
 */
#define LUNA_WM_V1_START_MOVE_SINCE_VERSION 1
/**
 * @ingroup iface_luna_wm_v1
 */
#define LUNA_WM_V1_SHOW_WINDOW_MENU_SINCE_VERSION 1

/** @ingroup iface_luna_wm_v1 */
static inline void
luna_wm_v1_set_user_data(struct luna_wm_v1 *luna_wm_v1, void *user_data)
{
	wl_proxy_set_user_data((struct wl_proxy *) luna_wm_v1, user_data);
}

/** @ingroup iface_luna_wm_v1 */
static inline void *
luna_wm_v1_get_user_data(struct luna_wm_v1 *luna_wm_v1)
{
	return wl_proxy_get_user_data((struct wl_proxy *) luna_wm_v1);
}

static inline uint32_t
luna_wm_v1_get_version(struct luna_wm_v1 *luna_wm_v1)
{
	return wl_proxy_get_version((struct wl_proxy *) luna_wm_v1);
}

/**
 * @ingroup iface_luna_wm_v1
 */
static inline void
luna_wm_v1_destroy(struct luna_wm_v1 *luna_wm_v1)
{
	wl_proxy_marshal_flags((struct wl_proxy *) luna_wm_v1,
			 LUNA_WM_V1_DESTROY, NULL, wl_proxy_get_version((struct wl_proxy *) luna_wm_v1), WL_MARSHAL_FLAG_DESTROY);
}

/**
 * @ingroup iface_luna_wm_v1
 *
 * Move the content top-left of an xdg_toplevel surface to (x, y) in
 * compositor output coordinates (origin top-left of the primary
 * output).  Non-toplevel surfaces are ignored.  The compositor may
 * clamp into the usable area (outside docks / panels).
 */
static inline void
luna_wm_v1_set_position(struct luna_wm_v1 *luna_wm_v1, struct wl_surface *surface, int32_t x, int32_t y)
{
	wl_proxy_marshal_flags((struct wl_proxy *) luna_wm_v1,
			 LUNA_WM_V1_SET_POSITION, NULL, wl_proxy_get_version((struct wl_proxy *) luna_wm_v1), 0, surface, x, y);
}

/**
 * @ingroup iface_luna_wm_v1
 *
 * Request a position event for the given surface.  The compositor
 * replies with one position event on this luna_wm object.
 */
static inline void
luna_wm_v1_get_position(struct luna_wm_v1 *luna_wm_v1, struct wl_surface *surface)
{
	wl_proxy_marshal_flags((struct wl_proxy *) luna_wm_v1,
			 LUNA_WM_V1_GET_POSITION, NULL, wl_proxy_get_version((struct wl_proxy *) luna_wm_v1), 0, surface);
}

/**
 * @ingroup iface_luna_wm_v1
 *
 * Start a compositor-side move of the given xdg_toplevel, equivalent to
 * xdg_toplevel.move.  Must be issued in response to a pointer button
 * press that is still held; the compositor uses its last button serial.
 * Prefer this over streaming set_position during a titlebar drag.
 */
static inline void
luna_wm_v1_start_move(struct luna_wm_v1 *luna_wm_v1, struct wl_surface *surface)
{
	wl_proxy_marshal_flags((struct wl_proxy *) luna_wm_v1,
			 LUNA_WM_V1_START_MOVE, NULL, wl_proxy_get_version((struct wl_proxy *) luna_wm_v1), 0, surface);
}

/**
 * @ingroup iface_luna_wm_v1
 *
 * Equivalent to xdg_toplevel.show_window_menu for frameless Luna clients
 * that cannot reach the xdg_toplevel object through GLFW.  x and y are
 * surface-local coordinates for menu placement.
 */
static inline void
luna_wm_v1_show_window_menu(struct luna_wm_v1 *luna_wm_v1, struct wl_surface *surface, int32_t x, int32_t y)
{
	wl_proxy_marshal_flags((struct wl_proxy *) luna_wm_v1,
			 LUNA_WM_V1_SHOW_WINDOW_MENU, NULL, wl_proxy_get_version((struct wl_proxy *) luna_wm_v1), 0, surface, x, y);
}

#ifdef  __cplusplus
}
#endif

#endif
