    "/* Vespera GUI Engine v3.12 — Shadow clip fix, text z-order, stylish widgets */\n"
    "\n"
    "/* ── Reset & Base ── */\n"
    "*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }\n"
    "html, body {\n"
    "  min-height: 100%;\n"
    "  background: radial-gradient(ellipse at 30% 20%, #312e6e 0%, #1a1a2e 40%, #0f0f1a 100%);\n"
    "  font-family: -apple-system, BlinkMacSystemFont, \"Inter\", \"Segoe UI\", sans-serif;\n"
    "  -webkit-font-smoothing: antialiased;\n"
    "}\n"
    "body {\n"
    "  position: relative;\n"
    "  min-width: 1040px;\n"
    "  min-height: 860px;\n"
    "}\n"
    "\n"
    "/* Text should stay inside its CSS box in both browsers and opengl_gui. */\n"
    "p, div, span {\n"
    "  overflow-wrap: break-word;\n"
    "}\n"
    ".btn_os, .nav_item, .tool_btn, .chip, .tag, .badge, .dock_icon,\n"
    ".hscroll_chip, .tab_pill, .select_option, .metric_pill {\n"
    "  white-space: nowrap;\n"
    "  text-overflow: ellipsis;\n"
    "  overflow: hidden;\n"
    "}\n"
    "\n"
    "/* ── Shared positioning helpers ── */\n"
    ".window { position: absolute; box-sizing: border-box; }\n"
    "#main_win, #toast, #info_win, #dock, #modal_overlay { position: absolute; box-sizing: border-box; }\n"
    "#sidebar, #content, #title_bar { position: absolute; box-sizing: border-box; }\n"
    "\n"
    "/* ── Window chrome ── */\n"
    ".window {\n"
    "  background: rgba(252,253,255,0.97);\n"
    "  border-radius: 18px;\n"
    "  border: 1px solid rgba(255,255,255,0.18);\n"
    "  box-shadow: 0 12px 48px rgba(0,0,0,0.32);\n"
    "}\n"
    ".window.focused {\n"
    "  border-color: rgba(99,102,241,0.35);\n"
    "  box-shadow: 0 16px 56px rgba(0,0,0,0.42);\n"
    "}\n"
    ".card {\n"
    "  border: 1px solid rgba(0,0,0,0.06);\n"
    "  background: rgba(255,255,255,0.98);\n"
    "}\n"
    ".hidden { display: none !important; }\n"
    ".overlay { border-radius: 0 !important; }\n"
    "\n"
    "/* ── Main window ── */\n"
    "#main_win { width: 740px; height: 660px; left: 150px; top: 80px; z-index: 10; overflow: hidden; }\n"
    "\n"
    "/* ── Title bar ── */\n"
    "#title_bar {\n"
    "  position: absolute;\n"
    "  background: transparent;\n"
    "  width: 740px; height: 48px;\n"
    "  left: 0; top: 0;\n"
    "  display: flex; align-items: center;\n"
    "  border-bottom: 1px solid rgba(0,0,0,0.06);\n"
    "}\n"
    "#title_text {\n"
    "  position: absolute;\n"
    "  color: #1e1e2e;\n"
    "  left: 0; top: 0; width: 740px; height: 48px;\n"
    "  display: flex; align-items: center; justify-content: center;\n"
    "  text-align: center;\n"
    "  font-weight: 600; font-size: 13px;\n"
    "  letter-spacing: 0.01em;\n"
    "  pointer-events: none;\n"
    "}\n"
    ".title_drag { position: absolute; width: 740px; height: 48px; left: 0; top: 0; cursor: move; }\n"
    ".btn_os {\n"
    "  position: absolute;\n"
    "  width: 13px; height: 13px;\n"
    "  border-radius: 50%;\n"
    "  top: 18px; cursor: pointer; z-index: 20;\n"
    "  transition: filter 0.1s;\n"
    "}\n"
    ".btn_os:hover { filter: brightness(1.15); }\n"
    "#btn_close { background: #ff5f57; left: 16px; }\n"
    "#btn_min   { background: #febc2e; left: 36px; }\n"
    "#btn_max   { background: #28c840; left: 56px; }\n"
    "\n"
    "/* ── Sidebar ── */\n"
    "#sidebar {\n"
    "  position: absolute;\n"
    "  background: linear-gradient(175deg, #1e1e2e 0%, #252542 60%, #2a2a50 100%);\n"
    "  width: 200px; height: 612px;\n"
    "  left: 0; top: 48px;\n"
    "  border-right: 1px solid rgba(255,255,255,0.06);\n"
    "  overflow: hidden;\n"
    "}\n"
    "\n"
    "/* Avatar */\n"
    "#sidebar_avatar {\n"
    "  position: absolute;\n"
    "  background: linear-gradient(135deg, #6366f1, #a855f7);\n"
    "  border-radius: 50%;\n"
    "  width: 54px; height: 54px;\n"
    "  left: 73px; top: 22px;\n"
    "  box-shadow: 0 4px 16px rgba(99,102,241,0.55);\n"
    "  border: 3px solid rgba(99,102,241,0.35);\n"
    "}\n"
    "#sidebar_username {\n"
    "  position: absolute;\n"
    "  color: #f0f0f8;\n"
    "  left: 0; top: 86px;\n"
    "  width: 200px; height: 20px;\n"
    "  text-align: center;\n"
    "  font-weight: 700; font-size: 13px;\n"
    "  letter-spacing: 0.01em;\n"
    "}\n"
    "#sidebar_role {\n"
    "  position: absolute;\n"
    "  color: rgba(180,180,210,0.7);\n"
    "  left: 0; top: 107px;\n"
    "  width: 200px; height: 16px;\n"
    "  text-align: center;\n"
    "  font-size: 10px; letter-spacing: 0.05em; text-transform: uppercase;\n"
    "}\n"
    "\n"
    "/* Nav items */\n"
    ".nav_item {\n"
    "  position: absolute;\n"
    "  color: rgba(190,190,220,0.75);\n"
    "  width: 172px; height: 36px;\n"
    "  border-radius: 10px;\n"
    "  left: 14px;\n"
    "  padding: 0 12px;\n"
    "  display: flex; align-items: center;\n"
    "  cursor: pointer;\n"
    "  font-size: 13px; font-weight: 500;\n"
    "  transition: background 0.15s, color 0.15s;\n"
    "  letter-spacing: 0.01em;\n"
    "}\n"
    ".nav_item:hover { background: rgba(255,255,255,0.08); color: #f0f0f8; }\n"
    ".nav_item.active {\n"
    "  background: rgba(99,102,241,0.2);\n"
    "  color: #c7d2fe;\n"
    "  font-weight: 600;\n"
    "  border-left: 2px solid #6366f1;\n"
    "  padding-left: 10px;\n"
    "}\n"
    ".nav_item:focus-visible { background: rgba(255,255,255,0.12); outline: 1px solid #c7d2fe; }\n"
    "#nav_1 { top: 138px; } #nav_2 { top: 180px; } #nav_3 { top: 222px; } #nav_4 { top: 264px; }\n"
    "\n"
    "/* Tag cloud */\n"
    "#tag_cloud {\n"
    "  position: absolute;\n"
    "  display: flex; flex-wrap: wrap;\n"
    "  gap: 5px;\n"
    "  place-content: center;\n"
    "  width: 172px; height: 62px;\n"
    "  left: 14px; top: 314px;\n"
    "  padding: 4px;\n"
    "}\n"
    ".tag {\n"
    "  background: rgba(255,255,255,0.1);\n"
    "  color: #c7d2fe;\n"
    "  border: 1px solid rgba(99,102,241,0.25);\n"
    "  height: 22px;\n"
    "  padding: 0 10px;\n"
    "  border-radius: 11px;\n"
    "  display: flex; align-items: center; justify-content: center;\n"
    "  font-size: 10px; font-weight: 700;\n"
    "  letter-spacing: 0.03em;\n"
    "}\n"
    ".tag.wide { flex: 1 1 64px; min-width: 48px; }\n"
    "\n"
    "/* Shrink row */\n"
    "#shrink_row {\n"
    "  position: absolute;\n"
    "  display: flex;\n"
    "  flex-direction: row;\n"
    "  gap: 5px;\n"
    "  width: 172px; height: 34px;\n"
    "  left: 14px; top: 386px;\n"
    "  padding: 3px;\n"
    "  background: rgba(255,255,255,0.06);\n"
    "  border-radius: 10px;\n"
    "}\n"
    ".shrink_item {\n"
    "  background: #6366f1;\n"
    "  color: #fff;\n"
    "  height: 28px;\n"
    "  border-radius: 8px;\n"
    "  display: flex; align-items: center; justify-content: center;\n"
    "  font-size: 11px; font-weight: 700;\n"
    "  flex: 1 1 0;\n"
    "  min-width: 0;\n"
    "}\n"
    "\n"
    "/* Dense demo */\n"
    "#dense_demo {\n"
    "  position: absolute;\n"
    "  display: grid;\n"
    "  grid-template-columns: repeat(3, 1fr);\n"
    "  grid-auto-rows: 20px;\n"
    "  grid-auto-flow: row dense;\n"
    "  place-items: center;\n"
    "  gap: 3px;\n"
    "  width: 172px; height: 56px;\n"
    "  left: 14px; top: 428px;\n"
    "  padding: 6px;\n"
    "  background: rgba(255,255,255,0.06);\n"
    "  border-radius: 10px;\n"
    "}\n"
    ".dense_cell {\n"
    "  background: #6366f1;\n"
    "  color: #fff;\n"
    "  width: 100%; height: 100%;\n"
    "  border-radius: 5px;\n"
    "  display: flex; align-items: center; justify-content: center;\n"
    "  font-size: 10px; font-weight: 700;\n"
    "}\n"
    "#dense_wide { grid-column: span 2; background: #a855f7; }\n"
    "\n"
    "/* Column dense demo */\n"
    "#col_dense_demo {\n"
    "  position: absolute;\n"
    "  display: grid;\n"
    "  grid-auto-flow: column dense;\n"
    "  grid-template-rows: repeat(2, 20px);\n"
    "  grid-template-columns: repeat(3, 1fr);\n"
    "  place-items: center;\n"
    "  gap: 3px;\n"
    "  width: 172px; height: 52px;\n"
    "  left: 14px; top: 492px;\n"
    "  padding: 6px;\n"
    "  background: rgba(255,255,255,0.06);\n"
    "  border-radius: 8px;\n"
    "}\n"
    ".col_dense_cell {\n"
    "  background: #8b5cf6;\n"
    "  color: #fff;\n"
    "  width: 100%; height: 100%;\n"
    "  border-radius: 5px;\n"
    "  display: flex; align-items: center; justify-content: center;\n"
    "  font-size: 10px; font-weight: 700;\n"
    "}\n"
    "#col_dense_tall { grid-row: span 2; background: #ec4899; }\n"
    "#col_dense_b    { background: #f59e0b; }\n"
    "\n"
    "/* Stat mini-cards */\n"
    ".stat_card {\n"
    "  position: absolute;\n"
    "  border-radius: 10px;\n"
    "  width: 50px; height: 50px;\n"
    "  box-shadow: 0 4px 10px rgba(0,0,0,0.3);\n"
    "}\n"
    "#stat_cpu { background: linear-gradient(135deg, #f59e0b, #f97316); left: 14px; top: 552px; }\n"
    "#stat_mem { background: linear-gradient(135deg, #06b6d4, #6366f1); left: 75px; top: 552px; }\n"
    "#stat_net { background: linear-gradient(135deg, #10b981, #059669); left: 136px; top: 552px; }\n"
    ".stat_label {\n"
    "  position: absolute;\n"
    "  color: rgba(255,255,255,0.85);\n"
    "  width: 50px; height: 16px;\n"
    "  left: 0; top: 7px;\n"
    "  text-align: center;\n"
    "  font-size: 8px; font-weight: 700; letter-spacing: 0.06em;\n"
    "}\n"
    ".stat_val {\n"
    "  position: absolute;\n"
    "  color: #fff;\n"
    "  width: 50px; height: 18px;\n"
    "  left: 0; top: 26px;\n"
    "  text-align: center;\n"
    "  font-size: 11px; font-weight: 700;\n"
    "}\n"
    "\n"
    "/* ── Content panel ── */\n"
    "#content {\n"
    "  position: absolute;\n"
    "  background: transparent;\n"
    "  width: 540px; height: 612px;\n"
    "  left: 200px; top: 48px;\n"
    "  overflow: hidden;\n"
    "}\n"
    "\n"
    "#section_title {\n"
    "  position: absolute;\n"
    "  color: #1e1e2e;\n"
    "  left: 28px; top: 20px;\n"
    "  width: 484px; height: 28px;\n"
    "  font-size: 20px; font-weight: 700;\n"
    "  letter-spacing: -0.02em;\n"
    "}\n"
    "#desc {\n"
    "  position: absolute;\n"
    "  color: #6b6b84;\n"
    "  width: 484px; height: 36px;\n"
    "  left: 28px; top: 52px;\n"
    "  font-size: 13px; line-height: 1.5;\n"
    "}\n"
    "#sep1 {\n"
    "  position: absolute;\n"
    "  background: rgba(0,0,0,0.07);\n"
    "  height: 1px; width: 484px;\n"
    "  left: 28px; top: 96px;\n"
    "}\n"
    "\n"
    "/* Toolbar */\n"
    "#toolbar {\n"
    "  position: absolute;\n"
    "  display: flex; flex-direction: row;\n"
    "  align-items: center;\n"
    "  gap: 8px;\n"
    "  width: 484px; height: 40px;\n"
    "  left: 28px; top: 110px;\n"
    "}\n"
    ".tool_btn {\n"
    "  background: #f0f0f8;\n"
    "  color: #3a3a50;\n"
    "  height: 36px;\n"
    "  border-radius: 10px;\n"
    "  display: flex; align-items: center; justify-content: center;\n"
    "  text-align: center;\n"
    "  font-size: 12px; font-weight: 600;\n"
    "  cursor: pointer;\n"
    "  transition: background 0.12s, color 0.12s, transform 0.1s;\n"
    "  flex: 1 1 auto;\n"
    "  letter-spacing: 0.01em;\n"
    "}\n"
    ".tool_btn:hover { background: #e0e0ec; color: #1e1e2e; transform: translateY(-1px); }\n"
    ".tool_btn:active { transform: translateY(0); }\n"
    ".tool_btn.active {\n"
    "  background: linear-gradient(135deg, #6366f1, #8b5cf6);\n"
    "  color: #fff;\n"
    "  box-shadow: 0 4px 12px rgba(99,102,241,0.3);\n"
    "}\n"
    ".tool_btn:focus-visible { outline: 2px solid rgba(99,102,241,0.5); }\n"
    "#tool_export { flex: 2 1 auto; }\n"
    "\n"
    "/* Apply button */\n"
    "#apply_btn {\n"
    "  position: absolute;\n"
    "  background: linear-gradient(135deg, #6366f1, #8b5cf6, #a855f7);\n"
    "  color: #fff;\n"
    "  width: 160px; height: 38px;\n"
    "  border-radius: 12px;\n"
    "  left: 28px; top: 160px;\n"
    "  display: flex; align-items: center; justify-content: center;\n"
    "  text-align: center;\n"
    "  font-weight: 700; font-size: 13px;\n"
    "  cursor: pointer;\n"
    "  transition: all 0.15s;\n"
    "  box-shadow: 0 4px 14px rgba(99,102,241,0.4);\n"
    "  letter-spacing: 0.01em;\n"
    "}\n"
    "#apply_btn:hover {\n"
    "  background: linear-gradient(135deg, #818cf8, #a78bfa);\n"
    "  box-shadow: 0 6px 18px rgba(99,102,241,0.5);\n"
    "  transform: translateY(-1px);\n"
    "}\n"
    "#apply_btn:active { transform: translateY(0); box-shadow: 0 2px 8px rgba(99,102,241,0.25); }\n"
    "#apply_btn:focus-visible { outline: 2px solid rgba(99,102,241,0.6); outline-offset: 2px; }\n"
    "\n"
    "/* Chip row */\n"
    "#chip_row {\n"
    "  position: absolute;\n"
    "  display: flex; flex-wrap: wrap;\n"
    "  gap: 7px;\n"
    "  align-items: center;\n"
    "  width: 484px; height: auto;\n"
    "  min-height: 66px;\n"
    "  left: 28px; top: 210px;\n"
    "}\n"
    ".chip {\n"
    "  background: #f0f0f8;\n"
    "  color: #4b4b68;\n"
    "  border: 1px solid rgba(0,0,0,0.06);\n"
    "  height: 28px;\n"
    "  padding: 0 14px;\n"
    "  border-radius: 14px;\n"
    "  display: flex; align-items: center; justify-content: center;\n"
    "  font-size: 11px; font-weight: 600;\n"
    "  transition: background 0.12s, color 0.12s;\n"
    "  letter-spacing: 0.02em;\n"
    "}\n"
    ".chip:hover { background: #e4e4f4; color: #1e1e2e; }\n"
    ".chip.accent {\n"
    "  background: linear-gradient(135deg, #6366f1, #8b5cf6);\n"
    "  color: #fff;\n"
    "  border-color: transparent;\n"
    "  box-shadow: 0 2px 8px rgba(99,102,241,0.3);\n"
    "}\n"
    "#chip_wide { padding: 0 20px; }\n"
    "\n"
    "/* Toggle */\n"
    "#toggle_row_label {\n"
    "  position: absolute;\n"
    "  color: #3a3a50;\n"
    "  left: 28px; top: 295px;\n"
    "  width: 200px; height: 28px;\n"
    "  display: flex; align-items: center;\n"
    "  font-size: 14px; font-weight: 500;\n"
    "}\n"
    ".toggle {\n"
    "  position: absolute;\n"
    "  width: 48px; height: 28px;\n"
    "  border-radius: 14px;\n"
    "  background: #d4d4e0;\n"
    "  left: 432px; top: 292px;\n"
    "  cursor: pointer;\n"
    "  transition: background 0.2s;\n"
    "  box-shadow: inset 0 1px 3px rgba(0,0,0,0.12);\n"
    "}\n"
    ".toggle.on { background: #6366f1; }\n"
    ".toggle_knob {\n"
    "  position: absolute;\n"
    "  width: 22px; height: 22px;\n"
    "  border-radius: 50%;\n"
    "  background: #fff;\n"
    "  box-shadow: 0 2px 6px rgba(0,0,0,0.25);\n"
    "  left: 3px; top: 3px;\n"
    "  transition: left 0.2s cubic-bezier(.4,0,.2,1);\n"
    "}\n"
    ".toggle.on .toggle_knob { left: 23px; }\n"
    "\n"
    "/* Checkbox */\n"
    ".checkbox {\n"
    "  position: absolute;\n"
    "  width: 20px; height: 20px;\n"
    "  border-radius: 6px;\n"
    "  background: #fff;\n"
    "  border: 2px solid #c8c8d8;\n"
    "  left: 28px; top: 337px;\n"
    "  cursor: pointer;\n"
    "  transition: background 0.15s, border-color 0.15s;\n"
    "}\n"
    ".checkbox.checked { background: #6366f1; border-color: #4f46e5; }\n"
    "#chk_label {\n"
    "  position: absolute;\n"
    "  color: #3a3a50;\n"
    "  left: 58px; top: 335px;\n"
    "  width: 300px; height: 24px;\n"
    "  display: flex; align-items: center;\n"
    "  font-size: 13px;\n"
    "}\n"
    "\n"
    "/* Theme selector */\n"
    "#theme_label {\n"
    "  position: absolute;\n"
    "  color: #3a3a50;\n"
    "  left: 28px; top: 373px;\n"
    "  width: 80px; height: 32px;\n"
    "  display: flex; align-items: center;\n"
    "  font-size: 13px; font-weight: 500;\n"
    "}\n"
    "#theme_combo { position: absolute; left: 120px; top: 369px; width: 160px; height: 32px; }\n"
    "#theme_combo:focus-within {\n"
    "  border-radius: 10px;\n"
    "  box-shadow: 0 0 0 2px rgba(99,102,241,0.3);\n"
    "}\n"
    "#theme_select_box {\n"
    "  position: absolute;\n"
    "  background: #fff;\n"
    "  color: #2a2a3a;\n"
    "  border: 1.5px solid #d8d8e8;\n"
    "  border-radius: 10px;\n"
    "  left: 0; top: 0; width: 160px; height: 32px;\n"
    "  padding: 0 10px;\n"
    "  display: flex; align-items: center;\n"
    "  cursor: pointer;\n"
    "  font-size: 12px; font-weight: 500;\n"
    "  transition: border-color 0.12s;\n"
    "}\n"
    "#theme_select_box:hover { border-color: #6366f1; }\n"
    "#theme_select_box:focus-visible { border-color: #6366f1; border-width: 2px; outline: none; }\n"
    "#select_panel {\n"
    "  position: absolute;\n"
    "  background: #fff;\n"
    "  border-radius: 10px;\n"
    "  border: 1px solid #e0e0ef;\n"
    "  left: 0; top: 36px;\n"
    "  width: 160px; height: 94px;\n"
    "  box-shadow: 0 12px 32px rgba(0,0,0,0.14);\n"
    "  z-index: 200;\n"
    "  overflow: hidden;\n"
    "}\n"
    ".select_option {\n"
    "  position: absolute;\n"
    "  background: transparent;\n"
    "  color: #2a2a3a;\n"
    "  width: 160px; height: 30px;\n"
    "  left: 0;\n"
    "  padding: 0 12px;\n"
    "  display: flex; align-items: center;\n"
    "  cursor: pointer;\n"
    "  font-size: 12px;\n"
    "  transition: background 0.1s;\n"
    "}\n"
    ".select_option:hover { background: rgba(99,102,241,0.08); color: #6366f1; }\n"
    ".select_option:focus-visible { background: rgba(99,102,241,0.08); outline: 1px solid rgba(99,102,241,0.4); }\n"
    "#opt_blue { top: 2px; } #opt_graphite { top: 32px; } #opt_green { top: 62px; }\n"
    "\n"
    "/* Slider */\n"
    "#slider_label {\n"
    "  position: absolute;\n"
    "  color: #7a7a90;\n"
    "  left: 28px; top: 418px;\n"
    "  width: 300px; height: 20px;\n"
    "  display: flex; align-items: center;\n"
    "  font-size: 12px;\n"
    "}\n"
    "#slider_track {\n"
    "  position: absolute;\n"
    "  background: #e8e8f0;\n"
    "  border-radius: 5px;\n"
    "  width: 432px; height: 6px;\n"
    "  left: 28px; top: 446px;\n"
    "}\n"
    "#slider_fill {\n"
    "  background: linear-gradient(90deg, #6366f1, #a855f7);\n"
    "  border-radius: 5px;\n"
    "  width: 302px; height: 6px;\n"
    "  position: absolute; left: 0; top: 0;\n"
    "}\n"
    "#slider_thumb {\n"
    "  position: absolute;\n"
    "  background: #fff;\n"
    "  border-radius: 50%;\n"
    "  width: 20px; height: 20px;\n"
    "  border: 2px solid #6366f1;\n"
    "  left: 292px; top: -7px;\n"
    "  box-shadow: 0 2px 8px rgba(0,0,0,0.18);\n"
    "  cursor: pointer;\n"
    "  transition: transform 0.1s;\n"
    "}\n"
    "#slider_thumb:hover { transform: scale(1.15); }\n"
    "\n"
    "/* Horizontal scroll */\n"
    "#hscroll_panel {\n"
    "  position: absolute;\n"
    "  background: #f0f0f8;\n"
    "  border-radius: 10px;\n"
    "  width: 432px; height: 36px;\n"
    "  left: 28px; top: 472px;\n"
    "  padding: 6px;\n"
    "  overflow-x: auto;\n"
    "  overflow-y: hidden;\n"
    "  scrollbar-width: thin;\n"
    "  scrollbar-color: rgba(99,102,241,0.5) #f0f0f8;\n"
    "}\n"
    "#hscroll_inner {\n"
    "  /* Use flex so chips flow naturally */\n"
    "  position: relative;\n"
    "  display: flex;\n"
    "  flex-direction: row;\n"
    "  gap: 6px;\n"
    "  width: max-content;\n"
    "  height: 24px;\n"
    "  align-items: center;\n"
    "}\n"
    ".hscroll_chip {\n"
    "  position: relative;\n"
    "  background: #6366f1;\n"
    "  color: #fff;\n"
    "  width: 72px; height: 24px;\n"
    "  border-radius: 8px;\n"
    "  display: flex; align-items: center; justify-content: center;\n"
    "  font-size: 10px; font-weight: 700;\n"
    "  flex-shrink: 0;\n"
    "}\n"
    "#hs_pin {\n"
    "  position: sticky;\n"
    "  left: 0;\n"
    "  background: #ec4899;\n"
    "  width: 52px;\n"
    "  z-index: 2;\n"
    "}\n"
    "\n"
    "/* Progress */\n"
    "#progress_label {\n"
    "  position: absolute;\n"
    "  color: #7a7a90;\n"
    "  left: 28px; top: 518px;\n"
    "  width: 300px; height: 20px;\n"
    "  display: flex; align-items: center;\n"
    "  font-size: 12px;\n"
    "}\n"
    "#progress_track {\n"
    "  position: absolute;\n"
    "  background: #e8e8f0;\n"
    "  border-radius: 5px;\n"
    "  width: 432px; height: 6px;\n"
    "  left: 28px; top: 542px;\n"
    "}\n"
    "#progress_fill {\n"
    "  background: linear-gradient(90deg, #22d3ee, #6366f1);\n"
    "  border-radius: 5px;\n"
    "  width: 0; height: 6px;\n"
    "  position: absolute; left: 0; top: 0;\n"
    "  animation: progress-anim 2.5s ease-in-out infinite alternate;\n"
    "}\n"
    "@keyframes progress-anim { to { width: 280px; } }\n"
    "\n"
    "/* Activity panel */\n"
    "#activity_panel {\n"
    "  position: absolute;\n"
    "  background: #f6f6fc;\n"
    "  border-radius: 10px;\n"
    "  border: 1px solid rgba(0,0,0,0.05);\n"
    "  width: 484px; height: 60px;\n"
    "  left: 28px; top: 558px;\n"
    "  overflow-y: auto;\n"
    "  overflow-x: hidden;\n"
    "  scrollbar-width: thin;\n"
    "  scrollbar-color: rgba(99,102,241,0.4) #f0f0f8;\n"
    "}\n"
    "/* Activity items use normal flow — remove absolute positioning */\n"
    ".activity_sticky {\n"
    "  position: sticky;\n"
    "  top: 0;\n"
    "  background: #f6f6fc;\n"
    "  color: #3a3a50;\n"
    "  width: 100%;\n"
    "  padding: 3px 10px;\n"
    "  font-size: 10px; font-weight: 700;\n"
    "  letter-spacing: 0.04em; text-transform: uppercase;\n"
    "  z-index: 1;\n"
    "  border-bottom: 1px solid rgba(0,0,0,0.05);\n"
    "}\n"
    ".activity_sticky_bottom {\n"
    "  position: sticky;\n"
    "  bottom: 0;\n"
    "  background: linear-gradient(135deg, #6366f1, #8b5cf6);\n"
    "  color: #fff;\n"
    "  width: 100%;\n"
    "  padding: 3px 10px;\n"
    "  font-size: 10px; font-weight: 700;\n"
    "  text-align: center;\n"
    "  border-top: 1px solid rgba(0,0,0,0.05);\n"
    "}\n"
    ".activity_line {\n"
    "  display: block;\n"
    "  color: #5c5c72;\n"
    "  width: 100%;\n"
    "  padding: 3px 10px;\n"
    "  font-size: 11px;\n"
    "  border-bottom: 1px solid rgba(0,0,0,0.03);\n"
    "}\n"
    "\n"
    "/* Badges */\n"
    ".badge {\n"
    "  position: absolute;\n"
    "  border-radius: 12px;\n"
    "  height: 22px;\n"
    "  padding: 0 10px;\n"
    "  display: flex; align-items: center; justify-content: center;\n"
    "  font-size: 10px; font-weight: 700;\n"
    "  color: #fff;\n"
    "  letter-spacing: 0.03em;\n"
    "}\n"
    "#badge_active { background: #22c55e; width: 60px; left: 28px;  top: 628px; }\n"
    "#badge_update { background: #f59e0b; width: 60px; left: 96px;  top: 628px; }\n"
    "#badge_err    { background: #ef4444; width: 54px; left: 164px; top: 628px; }\n"
    "#sep2 { position: absolute; background: rgba(0,0,0,0.06); height: 1px; width: 484px; left: 28px; top: 658px; }\n"
    "#status_text {\n"
    "  position: absolute;\n"
    "  color: #9898b0;\n"
    "  right: 28px; bottom: 8px;\n"
    "  width: 484px; height: 18px;\n"
    "  font-size: 11px; text-align: right;\n"
    "  letter-spacing: 0.01em;\n"
    "}\n"
    "\n"
    "/* ── Toast ── */\n"
    "#toast {\n"
    "  width: 340px; height: 86px;\n"
    "  left: 750px; top: 32px;\n"
    "  z-index: 20;\n"
    "}\n"
    "#toast_bar { position: absolute; width: 340px; height: 86px; left: 0; top: 0; }\n"
    "#toast_drag { position: absolute; width: 280px; height: 86px; left: 0; top: 0; cursor: move; }\n"
    "#toast_icon {\n"
    "  position: absolute;\n"
    "  background: linear-gradient(135deg, #6366f1, #a855f7);\n"
    "  border-radius: 14px;\n"
    "  width: 38px; height: 38px;\n"
    "  left: 40px; top: 24px;\n"
    "}\n"
    "#toast_title {\n"
    "  position: absolute;\n"
    "  color: #1e1e2e;\n"
    "  left: 90px; top: 19px;\n"
    "  width: 230px; height: 20px;\n"
    "  font-weight: 700; font-size: 13px;\n"
    "  display: flex; align-items: center;\n"
    "}\n"
    "#toast_msg {\n"
    "  position: absolute;\n"
    "  color: #7a7a90;\n"
    "  left: 90px; top: 40px;\n"
    "  width: 230px; height: 32px;\n"
    "  font-size: 11px; line-height: 1.4;\n"
    "  display: flex; align-items: center;\n"
    "}\n"
    "#toast_close {\n"
    "  position: absolute;\n"
    "  background: #ff5f57;\n"
    "  border-radius: 50%;\n"
    "  width: 13px; height: 13px;\n"
    "  left: 16px; top: 12px;\n"
    "  cursor: pointer; z-index: 25;\n"
    "  transition: filter 0.1s;\n"
    "}\n"
    "#toast_close:hover { filter: brightness(1.15); }\n"
    "\n"
    "/* ── Info window ── */\n"
    "#info_win { width: 320px; height: 196px; left: 48px; top: 528px; z-index: 15; }\n"
    "#info_drag { position: absolute; width: 280px; height: 44px; left: 0; top: 0; cursor: move; }\n"
    "#info_close {\n"
    "  position: absolute;\n"
    "  background: #ff5f57;\n"
    "  border-radius: 50%;\n"
    "  width: 13px; height: 13px;\n"
    "  left: 16px; top: 14px;\n"
    "  cursor: pointer; z-index: 25;\n"
    "  transition: filter 0.1s;\n"
    "}\n"
    "#info_close:hover { filter: brightness(1.15); }\n"
    "#info_icon {\n"
    "  position: absolute;\n"
    "  background: linear-gradient(135deg, #34d399, #059669);\n"
    "  border-radius: 50%;\n"
    "  width: 52px; height: 52px;\n"
    "  left: 134px; top: 44px;\n"
    "  box-shadow: 0 5px 18px rgba(52,211,153,0.5);\n"
    "}\n"
    "#info_title {\n"
    "  position: absolute;\n"
    "  color: #1e1e2e;\n"
    "  width: 320px; height: 22px;\n"
    "  left: 0; top: 106px;\n"
    "  text-align: center;\n"
    "  font-weight: 700; font-size: 15px;\n"
    "}\n"
    "#info_msg {\n"
    "  position: absolute;\n"
    "  color: #5c5c72;\n"
    "  width: 280px; height: 48px;\n"
    "  left: 20px; top: 132px;\n"
    "  text-align: center;\n"
    "  font-size: 12px; line-height: 1.5;\n"
    "}\n"
    "\n"
    "/* ── Dock ── */\n"
    "#dock {\n"
    "  background: rgba(248,249,252,0.88);\n"
    "  backdrop-filter: blur(20px);\n"
    "  -webkit-backdrop-filter: blur(20px);\n"
    "  border-radius: 22px;\n"
    "  border: 1px solid rgba(255,255,255,0.6);\n"
    "  width: 280px; height: 66px;\n"
    "  left: 390px; top: 700px;\n"
    "  box-shadow: 0 8px 32px rgba(0,0,0,0.28);\n"
    "  z-index: 30;\n"
    "  display: flex;\n"
    "  align-items: center;\n"
    "  justify-content: center;\n"
    "  gap: 0;\n"
    "}\n"
    ".dock_icon {\n"
    "  position: absolute;\n"
    "  width: 44px; height: 44px;\n"
    "  top: 11px;\n"
    "  border-radius: 14px;\n"
    "  cursor: pointer;\n"
    "  display: flex; align-items: center; justify-content: center;\n"
    "  font-weight: 800; color: #fff; font-size: 15px;\n"
    "  transition: transform 0.12s cubic-bezier(.34,1.56,.64,1);\n"
    "}\n"
    ".dock_icon:hover { transform: scale(1.18) translateY(-6px); }\n"
    "#dock_icon_info   { background: linear-gradient(135deg, #34d399, #059669); left: 12px; }\n"
    "#dock_icon_theme  { background: linear-gradient(135deg, #fbbf24, #f59e0b); left: 68px; }\n"
    "#dock_icon_notify { background: linear-gradient(135deg, #60a5fa, #6366f1); left: 124px; }\n"
    "#dock_icon_toast  { background: linear-gradient(135deg, #f87171, #ef4444); left: 180px; }\n"
    "\n"
    "/* ── Modal ── */\n"
    "#modal_overlay {\n"
    "  background: rgba(10,10,20,0.6);\n"
    "  backdrop-filter: blur(4px);\n"
    "  width: 100%; height: 100%;\n"
    "  left: 0; top: 0;\n"
    "  border-radius: 0;\n"
    "  z-index: 100;\n"
    "}\n"
    "#modal_dialog {\n"
    "  width: 400px; height: 248px;\n"
    "  left: 320px; top: 256px;\n"
    "  z-index: 110;\n"
    "  background: #fff;\n"
    "}\n"
    "#modal_icon {\n"
    "  position: absolute;\n"
    "  background: linear-gradient(135deg, #6366f1, #a855f7);\n"
    "  border-radius: 24px;\n"
    "  width: 52px; height: 52px;\n"
    "  left: 174px; top: 24px;\n"
    "  box-shadow: 0 6px 20px rgba(99,102,241,0.35);\n"
    "}\n"
    "#modal_title {\n"
    "  position: absolute;\n"
    "  color: #1e1e2e;\n"
    "  width: 400px; height: 24px;\n"
    "  left: 0; top: 88px;\n"
    "  text-align: center;\n"
    "  font-weight: 700; font-size: 17px;\n"
    "}\n"
    "#modal_msg {\n"
    "  position: absolute;\n"
    "  color: #5c5c72;\n"
    "  width: 340px; height: 44px;\n"
    "  left: 30px; top: 118px;\n"
    "  text-align: center;\n"
    "  font-size: 13px; line-height: 1.5;\n"
    "}\n"
    "#modal_cancel {\n"
    "  position: absolute;\n"
    "  background: #f0f0f8;\n"
    "  color: #3a3a50;\n"
    "  width: 148px; height: 42px;\n"
    "  border-radius: 12px;\n"
    "  left: 24px; top: 182px;\n"
    "  display: flex; align-items: center; justify-content: center;\n"
    "  text-align: center;\n"
    "  cursor: pointer;\n"
    "  border: 1px solid rgba(0,0,0,0.07);\n"
    "  font-size: 14px; font-weight: 500;\n"
    "  transition: background 0.12s;\n"
    "}\n"
    "#modal_cancel:hover { background: #e4e4f0; }\n"
    "#modal_cancel:active { background: #d4d4e4; }\n"
    "#modal_cancel:focus-visible { outline: 2px solid rgba(99,102,241,0.5); outline-offset: 2px; }\n"
    "#modal_confirm {\n"
    "  position: absolute;\n"
    "  background: linear-gradient(135deg, #6366f1, #8b5cf6);\n"
    "  color: #fff;\n"
    "  width: 148px; height: 42px;\n"
    "  border-radius: 12px;\n"
    "  right: 24px; top: 182px;\n"
    "  display: flex; align-items: center; justify-content: center;\n"
    "  text-align: center;\n"
    "  font-weight: 700; font-size: 14px;\n"
    "  cursor: pointer;\n"
    "  box-shadow: 0 4px 14px rgba(99,102,241,0.35);\n"
    "  transition: all 0.12s;\n"
    "}\n"
    "#modal_confirm:hover { background: linear-gradient(135deg, #818cf8, #a78bfa); box-shadow: 0 6px 18px rgba(99,102,241,0.45); }\n"
    "#modal_confirm:active { background: linear-gradient(135deg, #4f46e5, #7c3aed); }\n"
    "#modal_confirm:focus-visible { outline: 2px solid rgba(99,102,241,0.6); outline-offset: 2px; }\n"
    "\n"
    "/* ── Quick-Stats glass card (top-right accent widget) ── */\n"
    "#quick_stats {\n"
    "  position: absolute;\n"
    "  left: 920px; top: 80px;\n"
    "  width: 148px; height: 230px;\n"
    "  border-radius: 20px;\n"
    "  background: linear-gradient(160deg, rgba(255,255,255,0.14) 0%, rgba(255,255,255,0.06) 100%);\n"
    "  border: 1px solid rgba(255,255,255,0.22);\n"
    "  box-shadow: 0 8px 32px rgba(0,0,0,0.38);\n"
    "  z-index: 12;\n"
    "}\n"
    "#qs_title {\n"
    "  position: absolute;\n"
    "  color: rgba(255,255,255,0.9);\n"
    "  left: 0; top: 14px;\n"
    "  width: 148px; height: 18px;\n"
    "  text-align: center;\n"
    "  font-size: 11px; font-weight: 700;\n"
    "  letter-spacing: 0.06em;\n"
    "}\n"
    ".qs_row {\n"
    "  position: absolute;\n"
    "  width: 118px; height: 38px;\n"
    "  left: 15px;\n"
    "  border-radius: 12px;\n"
    "  background: rgba(255,255,255,0.1);\n"
    "  border: 1px solid rgba(255,255,255,0.12);\n"
    "}\n"
    "#qs_row1 { top: 40px; }\n"
    "#qs_row2 { top: 86px; }\n"
    "#qs_row3 { top: 132px; }\n"
    ".qs_label {\n"
    "  position: absolute;\n"
    "  color: rgba(200,200,255,0.75);\n"
    "  left: 10px; top: 4px;\n"
    "  width: 60px; height: 14px;\n"
    "  font-size: 9px; font-weight: 700; letter-spacing: 0.05em;\n"
    "}\n"
    ".qs_val {\n"
    "  position: absolute;\n"
    "  color: #fff;\n"
    "  left: 10px; top: 18px;\n"
    "  width: 90px; height: 16px;\n"
    "  font-size: 12px; font-weight: 700;\n"
    "}\n"
    ".qs_dot {\n"
    "  position: absolute;\n"
    "  width: 8px; height: 8px;\n"
    "  border-radius: 50%;\n"
    "  right: 10px; top: 15px;\n"
    "}\n"
    "#qs_dot1 { background: #22d3ee; box-shadow: 0 0 6px rgba(34,211,238,0.7); }\n"
    "#qs_dot2 { background: #a78bfa; box-shadow: 0 0 6px rgba(167,139,250,0.7); }\n"
    "#qs_dot3 { background: #34d399; box-shadow: 0 0 6px rgba(52,211,153,0.7); }\n"
    "#qs_bar {\n"
    "  position: absolute;\n"
    "  left: 15px; top: 184px;\n"
    "  width: 118px; height: 4px;\n"
    "  border-radius: 2px;\n"
    "  background: rgba(255,255,255,0.12);\n"
    "}\n"
    "#qs_bar_fill {\n"
    "  position: absolute;\n"
    "  left: 0; top: 0;\n"
    "  width: 72px; height: 4px;\n"
    "  border-radius: 2px;\n"
    "  background: linear-gradient(90deg, #6366f1, #a855f7);\n"
    "}\n"
    "#qs_footer {\n"
    "  position: absolute;\n"
    "  color: rgba(180,180,220,0.7);\n"
    "  left: 0; top: 198px;\n"
    "  width: 148px; height: 18px;\n"
    "  text-align: center;\n"
    "  font-size: 9px; font-weight: 600; letter-spacing: 0.04em;\n"
    "}\n"
    "\n"
    "/* ── Vertical Toolbar ── */\n"
    "#vtoolbar {\n"
    "  position: absolute;\n"
    "  left: 4px; top: 196px;\n"
    "  width: 46px; height: 380px;\n"
    "  border-radius: 18px;\n"
    "  background: rgba(12,12,28,0.93);\n"
    "  border: 1px solid rgba(255,255,255,0.09);\n"
    "  box-shadow: 0 14px 40px rgba(0,0,0,0.55), 0 2px 8px rgba(0,0,0,0.3);\n"
    "  z-index: 11;\n"
    "  display: flex; flex-direction: column;\n"
    "  align-items: center;\n"
    "  gap: 5px;\n"
    "  padding: 12px 0;\n"
    "}\n"
    ".vtb {\n"
    "  width: 32px; height: 32px;\n"
    "  border-radius: 10px;\n"
    "  display: flex; align-items: center; justify-content: center;\n"
    "  cursor: pointer;\n"
    "  font-size: 11px; font-weight: 800;\n"
    "  color: rgba(180,180,230,0.55);\n"
    "  background: transparent;\n"
    "  transition: background 0.14s, color 0.14s;\n"
    "}\n"
    ".vtb:hover { background: rgba(99,102,241,0.18); color: #c7d2fe; }\n"
    ".vtb.active {\n"
    "  background: linear-gradient(135deg, #6366f1, #8b5cf6);\n"
    "  color: #fff;\n"
    "  box-shadow: 0 3px 10px rgba(99,102,241,0.45);\n"
    "}\n"
    "#vtb_sep, #vtb_sep2 {\n"
    "  width: 22px; height: 1px;\n"
    "  background: rgba(255,255,255,0.1);\n"
    "  border-radius: 1px;\n"
    "  margin: 2px 0;\n"
    "}\n"
    "\n"
    "/* ── Connection Status Card ── */\n"
    "#status_card {\n"
    "  position: absolute;\n"
    "  left: 893px; top: 330px;\n"
    "  width: 125px; height: 186px;\n"
    "  border-radius: 18px;\n"
    "  background: linear-gradient(155deg, rgba(16,185,129,0.13) 0%, rgba(5,60,46,0.12) 100%);\n"
    "  border: 1px solid rgba(52,211,153,0.24);\n"
    "  box-shadow: 0 10px 36px rgba(0,0,0,0.52), 0 0 18px rgba(52,211,153,0.07);\n"
    "  z-index: 12;\n"
    "}\n"
    "#sc_title {\n"
    "  position: absolute;\n"
    "  color: rgba(255,255,255,0.38);\n"
    "  left: 0; top: 13px; width: 125px; height: 14px;\n"
    "  text-align: center; font-size: 8px; font-weight: 700; letter-spacing: 0.09em;\n"
    "}\n"
    "#sc_dot {\n"
    "  position: absolute;\n"
    "  left: 48px; top: 34px;\n"
    "  width: 28px; height: 28px;\n"
    "  border-radius: 50%;\n"
    "  background: radial-gradient(circle at 35% 35%, #34d399, #059669);\n"
    "  box-shadow: 0 0 10px rgba(52,211,153,0.65), 0 0 22px rgba(52,211,153,0.28);\n"
    "}\n"
    "#sc_status {\n"
    "  position: absolute;\n"
    "  color: #34d399;\n"
    "  left: 0; top: 72px; width: 125px; height: 15px;\n"
    "  text-align: center; font-size: 10px; font-weight: 700; letter-spacing: 0.02em;\n"
    "}\n"
    ".sc_row {\n"
    "  position: absolute;\n"
    "  width: 97px; left: 14px;\n"
    "  height: 30px; border-radius: 8px;\n"
    "  background: rgba(255,255,255,0.06);\n"
    "  border: 1px solid rgba(255,255,255,0.06);\n"
    "}\n"
    "#sc_r1 { top: 96px; }\n"
    "#sc_r2 { top: 134px; }\n"
    ".sc_rlabel {\n"
    "  position: absolute;\n"
    "  color: rgba(160,200,180,0.5);\n"
    "  left: 8px; top: 4px; width: 80px; height: 10px;\n"
    "  font-size: 7px; font-weight: 700; letter-spacing: 0.06em;\n"
    "}\n"
    ".sc_rval {\n"
    "  position: absolute;\n"
    "  color: rgba(210,240,225,0.85);\n"
    "  left: 8px; top: 14px; width: 80px; height: 12px;\n"
    "  font-size: 10px; font-weight: 600;\n"
    "}\n"
    "\n"
    "/* ── Improved info_win ── */\n"
    "#info_win {\n"
    "  background: linear-gradient(155deg, rgba(240,242,255,0.98), rgba(250,251,255,0.99));\n"
    "  border: 1px solid rgba(99,102,241,0.14);\n"
    "  box-shadow: 0 16px 48px rgba(0,0,0,0.2), 0 4px 12px rgba(99,102,241,0.08);\n"
    "}\n"
    "#info_icon {\n"
    "  box-shadow: 0 6px 20px rgba(52,211,153,0.42), 0 0 0 4px rgba(52,211,153,0.12);\n"
    "}\n"
    "\n"
    "/* ── Notification dots on nav items ── */\n"
    ".nav_dot {\n"
    "  position: absolute;\n"
    "  width: 7px; height: 7px;\n"
    "  border-radius: 50%;\n"
    "  right: 10px; top: 14px;\n"
    "}\n"
    "#nav_dot_1 { background: #22c55e; box-shadow: 0 0 6px rgba(34,197,94,0.7); }\n"
    "#nav_dot_2 { background: #f59e0b; box-shadow: 0 0 6px rgba(245,158,11,0.65); }\n"
    "\n"
    "/* ── AI Assistant card ── */\n"
    "#ai_card {\n"
    "  position: absolute;\n"
    "  left: 920px; top: 326px;\n"
    "  width: 148px; height: 136px;\n"
    "  border-radius: 18px;\n"
    "  background: linear-gradient(155deg, rgba(99,102,241,0.18) 0%, rgba(168,85,247,0.10) 100%);\n"
    "  border: 1px solid rgba(99,102,241,0.3);\n"
    "  box-shadow: 0 8px 28px rgba(99,102,241,0.25), 0 0 0 1px rgba(99,102,241,0.08);\n"
    "  z-index: 12;\n"
    "}\n"
    "#ai_title {\n"
    "  position: absolute;\n"
    "  color: rgba(199,210,254,0.9);\n"
    "  left: 0; top: 14px; width: 148px; height: 16px;\n"
    "  text-align: center;\n"
    "  font-size: 9px; font-weight: 700; letter-spacing: 0.08em;\n"
    "}\n"
    "#ai_orb {\n"
    "  position: absolute;\n"
    "  left: 50px; top: 30px;\n"
    "  width: 48px; height: 48px;\n"
    "  border-radius: 50%;\n"
    "  background: radial-gradient(circle at 38% 32%, #a78bfa, #6366f1 55%, #4f46e5);\n"
    "  box-shadow: 0 0 18px rgba(99,102,241,0.55), 0 0 40px rgba(99,102,241,0.22);\n"
    "  border: 1.5px solid rgba(167,139,250,0.4);\n"
    "}\n"
    "#ai_status {\n"
    "  position: absolute;\n"
    "  color: rgba(167,139,250,0.9);\n"
    "  left: 0; top: 88px; width: 148px; height: 14px;\n"
    "  text-align: center;\n"
    "  font-size: 9px; font-weight: 600; letter-spacing: 0.04em;\n"
    "}\n"
    "#ai_hint {\n"
    "  position: absolute;\n"
    "  color: rgba(180,180,230,0.55);\n"
    "  left: 10px; top: 106px; width: 128px; height: 22px;\n"
    "  text-align: center;\n"
    "  font-size: 9px; letter-spacing: 0.02em;\n"
    "}\n"
    "\n"
    "/* ── Command palette search bar ── */\n"
    "#cmd_palette {\n"
    "  position: absolute;\n"
    "  left: 380px; top: 740px;\n"
    "  width: 300px; height: 40px;\n"
    "  border-radius: 14px;\n"
    "  background: rgba(18,18,30,0.88);\n"
    "  border: 1px solid rgba(99,102,241,0.3);\n"
    "  box-shadow: 0 8px 28px rgba(0,0,0,0.45), 0 0 0 1px rgba(99,102,241,0.1);\n"
    "  z-index: 25;\n"
    "  display: flex; align-items: center;\n"
    "}\n"
    "#cmd_icon {\n"
    "  position: absolute;\n"
    "  color: rgba(99,102,241,0.7);\n"
    "  left: 14px; top: 0; width: 16px; height: 40px;\n"
    "  display: flex; align-items: center;\n"
    "  font-size: 13px; font-weight: 700;\n"
    "}\n"
    "#cmd_text {\n"
    "  position: absolute;\n"
    "  color: rgba(200,200,240,0.55);\n"
    "  left: 36px; top: 0; width: 200px; height: 40px;\n"
    "  display: flex; align-items: center;\n"
    "  font-size: 12px; letter-spacing: 0.01em;\n"
    "}\n"
    "#cmd_key {\n"
    "  position: absolute;\n"
    "  background: rgba(99,102,241,0.15);\n"
    "  color: rgba(180,180,230,0.6);\n"
    "  border: 1px solid rgba(99,102,241,0.25);\n"
    "  border-radius: 6px;\n"
    "  right: 12px; top: 10px;\n"
    "  width: 42px; height: 20px;\n"
    "  display: flex; align-items: center; justify-content: center;\n"
    "  font-size: 9px; font-weight: 700; letter-spacing: 0.04em;\n"
    "}\n"
    "\n"
    "/* ── Metric progress bars inside stat cards ── */\n"
    ".stat_bar_bg {\n"
    "  position: absolute;\n"
    "  background: rgba(255,255,255,0.18);\n"
    "  border-radius: 2px;\n"
    "  width: 34px; height: 3px;\n"
    "  left: 8px; top: 44px;\n"
    "}\n"
    ".stat_bar_fill {\n"
    "  position: absolute;\n"
    "  border-radius: 2px;\n"
    "  height: 3px; top: 0; left: 0;\n"
    "}\n"
    "#cpu_bar_fill  { background: rgba(255,255,255,0.85); width: 21px; }\n"
    "#mem_bar_fill  { background: rgba(255,255,255,0.85); width: 26px; }\n"
    "#net_bar_fill  { background: rgba(255,255,255,0.85); width: 16px; }\n"
    "\n"
    "/* ── Sidebar divider ── */\n"
    ".sidebar_divider {\n"
    "  position: absolute;\n"
    "  background: rgba(255,255,255,0.07);\n"
    "  height: 1px; width: 152px;\n"
    "  left: 24px;\n"
    "}\n"
    "\n"
    "/* ── Sidebar footer version badge ── */\n"
    "#sidebar_version {\n"
    "  position: absolute;\n"
    "  color: rgba(140,140,180,0.4);\n"
    "  left: 0; top: 594px;\n"
    "  width: 200px; height: 16px;\n"
    "  text-align: center;\n"
    "  font-size: 8px; letter-spacing: 0.06em;\n"
    "}\n"
    "\n"
    "/* ── Modal: improved confirm button glow on active ── */\n"
    "#modal_confirm:active {\n"
    "  box-shadow: 0 0 20px rgba(99,102,241,0.6);\n"
    "}\n"
    "\n"
    "/* ── Dock icon labels ── */\n"
    ".dock_label {\n"
    "  position: absolute;\n"
    "  color: rgba(255,255,255,0.75);\n"
    "  width: 44px; height: 12px;\n"
    "  left: 0; top: 48px;\n"
    "  text-align: center;\n"
    "  font-size: 7px; font-weight: 700; letter-spacing: 0.05em;\n"
    "}\n"
    "\n"
    "/* ── Content metrics row ── */\n"
    "#metrics_row {\n"
    "  position: absolute;\n"
    "  display: flex; flex-direction: row;\n"
    "  gap: 8px;\n"
    "  align-items: center;\n"
    "  width: 484px; height: 54px;\n"
    "  left: 28px; top: 634px;\n"
    "}\n"
    ".metric_pill {\n"
    "  border-radius: 12px;\n"
    "  height: 46px;\n"
    "  display: flex; align-items: center;\n"
    "  padding: 0 14px;\n"
    "  flex: 1 1 0;\n"
    "  min-width: 0;\n"
    "}\n"
    "#mp_online {\n"
    "  background: linear-gradient(135deg, rgba(34,197,94,0.15), rgba(16,185,129,0.1));\n"
    "  border: 1px solid rgba(34,197,94,0.25);\n"
    "}\n"
    "#mp_peers {\n"
    "  background: linear-gradient(135deg, rgba(99,102,241,0.15), rgba(168,85,247,0.1));\n"
    "  border: 1px solid rgba(99,102,241,0.25);\n"
    "}\n"
    "#mp_latency {\n"
    "  background: linear-gradient(135deg, rgba(245,158,11,0.15), rgba(249,115,22,0.1));\n"
    "  border: 1px solid rgba(245,158,11,0.25);\n"
    "}\n"
    ".mp_val {\n"
    "  position: absolute;\n"
    "  font-size: 15px; font-weight: 800;\n"
    "  letter-spacing: -0.02em;\n"
    "}\n"
    ".mp_label {\n"
    "  position: absolute;\n"
    "  font-size: 8px; font-weight: 700;\n"
    "  letter-spacing: 0.05em; text-transform: uppercase;\n"
    "  opacity: 0.6;\n"
    "}\n"
    "#mp_val_online { color: #4ade80; left: 14px; top: 8px; width: 80px; height: 20px; }\n"
    "#mp_val_peers  { color: #a78bfa; left: 14px; top: 8px; width: 80px; height: 20px; }\n"
    "#mp_val_lat    { color: #fbbf24; left: 14px; top: 8px; width: 80px; height: 20px; }\n"
    "#mp_lbl_online { color: #4ade80; left: 14px; top: 30px; width: 80px; height: 12px; }\n"
    "#mp_lbl_peers  { color: #a78bfa; left: 14px; top: 30px; width: 80px; height: 12px; }\n"
    "#mp_lbl_lat    { color: #fbbf24; left: 14px; top: 30px; width: 80px; height: 12px; }\n"
    "\n"
    "/* ── Keyframe animations ── */\n"
    "@keyframes progress-anim { to { width: 280px; } }\n"
    "@keyframes orb-pulse {\n"
    "  0%   { box-shadow: 0 0 18px rgba(99,102,241,0.55), 0 0 40px rgba(99,102,241,0.22); }\n"
    "  50%  { box-shadow: 0 0 28px rgba(99,102,241,0.8),  0 0 60px rgba(99,102,241,0.35); }\n"
    "  100% { box-shadow: 0 0 18px rgba(99,102,241,0.55), 0 0 40px rgba(99,102,241,0.22); }\n"
    "}\n"
    "\n"
    "/* ── Image / Media card ── */\n"
    "#media_card {\n"
    "  position: absolute;\n"
    "  left: 1090px; top: 80px;\n"
    "  width: 140px; height: 200px;\n"
    "  border-radius: 20px;\n"
    "  background: rgba(255,255,255,0.07);\n"
    "  border: 1px solid rgba(255,255,255,0.14);\n"
    "  box-shadow: 0 10px 36px rgba(0,0,0,0.45);\n"
    "  z-index: 12;\n"
    "  overflow: hidden;\n"
    "}\n"
    "#media_img {\n"
    "  position: absolute;\n"
    "  left: 0; top: 0;\n"
    "  width: 140px; height: 140px;\n"
    "  border-radius: 20px 20px 0 0;\n"
    "  background: linear-gradient(135deg, #6366f1 0%, #a855f7 50%, #ec4899 100%);\n"
    "}\n"
    "#media_label {\n"
    "  position: absolute;\n"
    "  color: rgba(255,255,255,0.9);\n"
    "  left: 0; top: 144px;\n"
    "  width: 140px; height: 18px;\n"
    "  text-align: center;\n"
    "  font-size: 11px; font-weight: 700; letter-spacing: 0.04em;\n"
    "}\n"
    "#media_sub {\n"
    "  position: absolute;\n"
    "  color: rgba(180,180,230,0.55);\n"
    "  left: 0; top: 166px;\n"
    "  width: 140px; height: 14px;\n"
    "  text-align: center;\n"
    "  font-size: 9px; letter-spacing: 0.03em;\n"
    "}\n"
    "#media_badge {\n"
    "  position: absolute;\n"
    "  background: #22c55e;\n"
    "  border-radius: 6px;\n"
    "  width: 44px; height: 18px;\n"
    "  left: 48px; top: 182px;\n"
    "  display: flex; align-items: center; justify-content: center;\n"
    "  font-size: 9px; font-weight: 700; color: #fff;\n"
    "  letter-spacing: 0.04em;\n"
    "}\n"
    "\n"
    "/* ── Floating Action Button ── */\n"
    "#fab {\n"
    "  position: absolute;\n"
    "  right: 28px; bottom: 28px;\n"
    "  width: 52px; height: 52px;\n"
    "  border-radius: 50%;\n"
    "  background: linear-gradient(135deg, #22d3ee, #6366f1);\n"
    "  box-shadow: 0 8px 24px rgba(34,211,238,0.45), 0 3px 8px rgba(0,0,0,0.25);\n"
    "  z-index: 40;\n"
    "  display: flex; align-items: center; justify-content: center;\n"
    "  cursor: pointer;\n"
    "  font-size: 20px;\n"
    "  transition: transform 0.12s cubic-bezier(.34,1.56,.64,1), box-shadow 0.12s;\n"
    "}\n"
    "#fab:hover {\n"
    "  transform: scale(1.1) translateY(-2px);\n"
    "  box-shadow: 0 12px 32px rgba(34,211,238,0.55), 0 4px 12px rgba(0,0,0,0.3);\n"
    "}\n"
    "#fab:active { transform: scale(0.96); }\n"
    "\n"
    "/* ── Notification pill (top centre) ── */\n"
    "#notif_pill {\n"
    "  position: absolute;\n"
    "  left: 392px;\n"
    "  top: 14px;\n"
    "  width: 280px;\n"
    "  height: 38px;\n"
    "  border-radius: 19px;\n"
    "  background: rgba(20,20,36,0.88);\n"
    "  border: 1px solid rgba(99,102,241,0.35);\n"
    "  box-shadow: 0 4px 20px rgba(0,0,0,0.4), 0 0 0 1px rgba(99,102,241,0.1);\n"
    "  z-index: 50;\n"
    "  display: flex; align-items: center;\n"
    "}\n"
    "#notif_dot {\n"
    "  position: absolute;\n"
    "  left: 14px; top: 15px;\n"
    "  width: 8px; height: 8px;\n"
    "  border-radius: 50%;\n"
    "  background: #22d3ee;\n"
    "  box-shadow: 0 0 8px rgba(34,211,238,0.7);\n"
    "}\n"
    "#notif_text {\n"
    "  position: absolute;\n"
    "  color: rgba(220,220,255,0.85);\n"
    "  left: 32px; top: 0;\n"
    "  width: 200px; height: 38px;\n"
    "  display: flex; align-items: center;\n"
    "  font-size: 11px; font-weight: 600; letter-spacing: 0.01em;\n"
    "}\n"
    "#notif_close {\n"
    "  position: absolute;\n"
    "  right: 12px; top: 13px;\n"
    "  width: 12px; height: 12px;\n"
    "  border-radius: 50%;\n"
    "  background: rgba(255,255,255,0.15);\n"
    "  cursor: pointer;\n"
    "  font-size: 8px; color: rgba(255,255,255,0.5);\n"
    "  display: flex; align-items: center; justify-content: center;\n"
    "  font-weight: 700;\n"
    "}\n"
    "#notif_close:hover { background: rgba(255,80,80,0.5); color: #fff; }\n"
    "\n"
    "/* ── Transfer / Upload card ── */\n"
    "#transfer_card {\n"
    "  position: absolute;\n"
    "  left: 1090px; top: 296px;\n"
    "  width: 140px; height: 132px;\n"
    "  border-radius: 18px;\n"
    "  background: linear-gradient(150deg, rgba(14,165,233,0.15) 0%, rgba(6,182,212,0.08) 100%);\n"
    "  border: 1px solid rgba(14,165,233,0.26);\n"
    "  box-shadow: 0 8px 28px rgba(0,0,0,0.38);\n"
    "  z-index: 12;\n"
    "}\n"
    "#tc_title {\n"
    "  position: absolute;\n"
    "  color: rgba(186,230,253,0.8);\n"
    "  left: 0; top: 12px; width: 140px; height: 14px;\n"
    "  text-align: center;\n"
    "  font-size: 8px; font-weight: 700; letter-spacing: 0.08em;\n"
    "}\n"
    "#tc_icon {\n"
    "  position: absolute;\n"
    "  left: 50px; top: 28px;\n"
    "  width: 40px; height: 40px;\n"
    "  border-radius: 12px;\n"
    "  background: linear-gradient(135deg, #0ea5e9, #06b6d4);\n"
    "  box-shadow: 0 4px 14px rgba(14,165,233,0.45);\n"
    "}\n"
    "#tc_val {\n"
    "  position: absolute;\n"
    "  color: #7dd3fc;\n"
    "  left: 0; top: 76px; width: 140px; height: 16px;\n"
    "  text-align: center;\n"
    "  font-size: 11px; font-weight: 700; letter-spacing: 0.01em;\n"
    "}\n"
    "#tc_bar_bg {\n"
    "  position: absolute;\n"
    "  left: 16px; top: 100px;\n"
    "  width: 108px; height: 4px;\n"
    "  border-radius: 2px;\n"
    "  background: rgba(255,255,255,0.1);\n"
    "}\n"
    "#tc_bar_fill {\n"
    "  position: absolute;\n"
    "  left: 0; top: 0;\n"
    "  width: 74px; height: 4px;\n"
    "  border-radius: 2px;\n"
    "  background: linear-gradient(90deg, #0ea5e9, #22d3ee);\n"
    "}\n"
    "\n"
    "/* ── Pill-style tab bar ── */\n"
    "#tab_bar {\n"
    "  position: absolute;\n"
    "  left: 1090px; top: 444px;\n"
    "  width: 140px; height: 36px;\n"
    "  border-radius: 18px;\n"
    "  background: rgba(255,255,255,0.07);\n"
    "  border: 1px solid rgba(255,255,255,0.1);\n"
    "  box-shadow: 0 4px 14px rgba(0,0,0,0.3);\n"
    "  z-index: 12;\n"
    "  display: flex;\n"
    "  align-items: center;\n"
    "  gap: 0;\n"
    "  padding: 3px;\n"
    "}\n"
    ".tab_pill {\n"
    "  border-radius: 15px;\n"
    "  height: 30px;\n"
    "  display: flex; align-items: center; justify-content: center;\n"
    "  font-size: 10px; font-weight: 700;\n"
    "  cursor: pointer;\n"
    "  flex: 1 1 0;\n"
    "  color: rgba(180,180,230,0.5);\n"
    "  transition: background 0.15s, color 0.15s;\n"
    "  letter-spacing: 0.03em;\n"
    "}\n"
    ".tab_pill.active {\n"
    "  background: linear-gradient(135deg, #6366f1, #8b5cf6);\n"
    "  color: #fff;\n"
    "  box-shadow: 0 2px 8px rgba(99,102,241,0.4);\n"
    "}\n"
    ".tab_pill:hover { color: rgba(220,220,255,0.8); }\n"
    "\n"
    "/* ── Mini color swatch row ── */\n"
    "#swatch_row {\n"
    "  position: absolute;\n"
    "  left: 1090px; top: 494px;\n"
    "  width: 140px; height: 32px;\n"
    "  display: flex; gap: 6px; align-items: center;\n"
    "  justify-content: center;\n"
    "  z-index: 12;\n"
    "}\n"
    ".swatch {\n"
    "  width: 22px; height: 22px;\n"
    "  border-radius: 50%;\n"
    "  cursor: pointer;\n"
    "  box-shadow: 0 2px 6px rgba(0,0,0,0.3);\n"
    "  border: 2px solid rgba(255,255,255,0.2);\n"
    "  transition: transform 0.1s;\n"
    "}\n"
    ".swatch:hover { transform: scale(1.2); }\n"
    ".swatch.sel { border-color: #fff; border-width: 2.5px; }\n"
    "#sw1 { background: #6366f1; }\n"
    "#sw2 { background: #ec4899; }\n"
    "#sw3 { background: #10b981; }\n"
    "#sw4 { background: #f59e0b; }\n"
    "#sw5 { background: #ef4444; }\n"
    "\n"
    "/* ── Keyboard shortcut hint card ── */\n"
    "#kbd_card {\n"
    "  position: absolute;\n"
    "  left: 1090px; top: 540px;\n"
    "  width: 140px; height: 100px;\n"
    "  border-radius: 16px;\n"
    "  background: rgba(255,255,255,0.05);\n"
    "  border: 1px solid rgba(255,255,255,0.1);\n"
    "  box-shadow: 0 6px 20px rgba(0,0,0,0.35);\n"
    "  z-index: 12;\n"
    "}\n"
    "#kbd_title {\n"
    "  position: absolute;\n"
    "  color: rgba(200,200,255,0.5);\n"
    "  left: 0; top: 10px; width: 140px; height: 14px;\n"
    "  text-align: center;\n"
    "  font-size: 8px; font-weight: 700; letter-spacing: 0.07em;\n"
    "}\n"
    ".kbd_row {\n"
    "  position: absolute;\n"
    "  width: 116px; left: 12px;\n"
    "  height: 20px;\n"
    "  display: flex; align-items: center;\n"
    "}\n"
    "#kr1 { top: 28px; }\n"
    "#kr2 { top: 52px; }\n"
    "#kr3 { top: 76px; }\n"
    ".kbd_label {\n"
    "  position: absolute;\n"
    "  color: rgba(180,180,220,0.5);\n"
    "  left: 0; top: 0; width: 70px; height: 20px;\n"
    "  display: flex; align-items: center;\n"
    "  font-size: 9px;\n"
    "}\n"
    ".kbd_key {\n"
    "  position: absolute;\n"
    "  right: 0; top: 2px;\n"
    "  background: rgba(255,255,255,0.08);\n"
    "  border: 1px solid rgba(255,255,255,0.14);\n"
    "  border-radius: 5px;\n"
    "  height: 16px;\n"
    "  padding: 0 5px;\n"
    "  display: flex; align-items: center; justify-content: center;\n"
    "  font-size: 9px; font-weight: 700;\n"
    "  color: rgba(200,200,255,0.6);\n"
    "  letter-spacing: 0.03em;\n"
    "}\n"
