    "<!DOCTYPE html>\n"
    "<html lang=\"en\">\n"
    "<head>\n"
    "  <meta charset=\"utf-8\">\n"
    "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
    "  <title>Vespera GUI Engine v3.12</title>\n"
    "  <link rel=\"stylesheet\" type=\"text/css\" href=\"demo.css\">\n"
    "</head>\n"
    "<body>\n"
    "\n"
    "<!-- Notification pill (top centre) -->\n"
    "<div id=\"notif_pill\">\n"
    "  <div id=\"notif_dot\"></div>\n"
    "  <p id=\"notif_text\">VPN connected — 7 peers online</p>\n"
    "  <p id=\"notif_close\">✕</p>\n"
    "</div>\n"
    "\n"
    "\n"
    "<!-- Main window -->\n"
    "<div id=\"main_win\" class=\"window focused\">\n"
    "  <div id=\"title_bar\">\n"
    "    <div id=\"title_drag\" class=\"title_drag\" draggable=\"1\"></div>\n"
    "    <div id=\"btn_close\" class=\"btn_os\" onclick=\"onClose()\"></div>\n"
    "    <div id=\"btn_min\" class=\"btn_os\" onclick=\"onMinimize()\"></div>\n"
    "    <div id=\"btn_max\" class=\"btn_os\" onclick=\"onMaximize()\"></div>\n"
    "    <p id=\"title_text\">System Preferences</p>\n"
    "  </div>\n"
    "  <div id=\"sidebar\">\n"
    "    <div id=\"sidebar_avatar\"></div>\n"
    "    <p id=\"sidebar_username\">Vespera User</p>\n"
    "    <p id=\"sidebar_role\">Administrator</p>\n"
    "    <div id=\"nav_1\" class=\"nav_item active\" onclick=\"onNavClick()\">General<div id=\"nav_dot_1\" class=\"nav_dot\"></div></div>\n"
    "    <div id=\"nav_2\" class=\"nav_item\" onclick=\"onNavClick()\">Appearance<div id=\"nav_dot_2\" class=\"nav_dot\"></div></div>\n"
    "    <div id=\"nav_3\" class=\"nav_item\" onclick=\"onNavClick()\">Network</div>\n"
    "    <div id=\"nav_4\" class=\"nav_item\" onclick=\"onNavClick()\">Security</div>\n"
    "    <div id=\"sidebar_vpn_block\">\n"
    "      <div id=\"sidebar_vpn_dot\"></div>\n"
    "      <p id=\"sidebar_vpn_label\">VPN Active</p>\n"
    "    </div>\n"
    "    <div id=\"sidebar_stats_block\">\n"
    "      <div class=\"sidebar_stat_row\"><p class=\"ss_key\">Peers</p><p class=\"ss_val\">7</p></div>\n"
    "      <div class=\"sidebar_stat_row\"><p class=\"ss_key\">Ping</p><p class=\"ss_val\">12 ms</p></div>\n"
    "      <div class=\"sidebar_stat_row\"><p class=\"ss_key\">Speed</p><p class=\"ss_val\">1.2 MB/s</p></div>\n"
    "    </div>\n"
    "    <p id=\"sidebar_version\">v3.12.0 — Vespera</p>\n"
    "  </div>\n"
    "  <div id=\"content\">\n"
    "    <p id=\"section_title\">General</p>\n"
    "    <p id=\"desc\" aria-live=\"polite\">Position, px units, browser-matched CSS.</p>\n"
    "    <div id=\"sep1\"></div>\n"
    "    <div id=\"toolbar\">\n"
    "      <div id=\"tool_save\" class=\"tool_btn active\" role=\"button\" onclick=\"onToolClick()\">Save</div>\n"
    "      <div id=\"tool_reset\" class=\"tool_btn\" role=\"button\" onclick=\"onToolClick()\">Reset</div>\n"
    "      <div id=\"tool_export\" class=\"tool_btn\" role=\"button\" onclick=\"onToolClick()\">Export</div>\n"
    "    </div>\n"
    "    <div id=\"apply_btn\" onclick=\"onApply()\">Apply Changes</div>\n"
    "    <div id=\"chip_row\">\n"
    "      <div class=\"chip accent\">CSS</div>\n"
    "      <div class=\"chip\">Flex</div>\n"
    "      <div class=\"chip\">Grid</div>\n"
    "      <div class=\"chip\">HSL</div>\n"
    "      <div class=\"chip\">Wrap</div>\n"
    "      <div class=\"chip\">GLSL</div>\n"
    "      <div id=\"chip_wide\" class=\"chip\">Focus</div>\n"
    "    </div>\n"
    "    <p id=\"toggle_row_label\">Dark Mode</p>\n"
    "    <div id=\"toggle_knob_track\" class=\"toggle\" onclick=\"onToggleClick()\">\n"
    "      <div id=\"toggle_knob\" class=\"toggle_knob\"></div>\n"
    "    </div>\n"
    "    <div id=\"checkbox_notify\" class=\"checkbox\" onclick=\"onCheckboxClick()\"></div>\n"
    "    <p id=\"chk_label\">Enable Notifications</p>\n"
    "    <p id=\"theme_label\">Theme</p>\n"
    "    <div id=\"theme_combo\">\n"
    "      <div id=\"theme_select_box\" role=\"combobox\" aria-label=\"Theme\" aria-expanded=\"false\" onclick=\"onSelectToggle()\">Indigo  ▾</div>\n"
    "      <div id=\"select_panel\" class=\"card hidden\">\n"
    "        <div id=\"opt_blue\" class=\"select_option\" onclick=\"onSelectOption()\">Indigo</div>\n"
    "        <div id=\"opt_graphite\" class=\"select_option\" onclick=\"onSelectOption()\">Graphite</div>\n"
    "        <div id=\"opt_green\" class=\"select_option\" onclick=\"onSelectOption()\">Emerald</div>\n"
    "      </div>\n"
    "    </div>\n"
    "    <p id=\"slider_label\">Brightness: 70%</p>\n"
    "    <div id=\"slider_track\">\n"
    "      <div id=\"slider_fill\"></div>\n"
    "      <div id=\"slider_thumb\" draggable=\"2\"></div>\n"
    "    </div>\n"
    "    <div id=\"hscroll_panel\">\n"
    "      <div id=\"hscroll_inner\">\n"
    "        <div id=\"hs_pin\" class=\"hscroll_chip\">Pin</div>\n"
    "        <div class=\"hscroll_chip\">Alpha</div>\n"
    "        <div class=\"hscroll_chip\">Beta</div>\n"
    "        <div class=\"hscroll_chip\">Gamma</div>\n"
    "        <div class=\"hscroll_chip\">Delta</div>\n"
    "        <div class=\"hscroll_chip\">Epsilon</div>\n"
    "        <div class=\"hscroll_chip\">Zeta</div>\n"
    "      </div>\n"
    "    </div>\n"
    "    <div id=\"progress_track\">\n"
    "      <div id=\"progress_fill\"></div>\n"
    "    </div>\n"
    "    <div id=\"activity_panel\">\n"
    "      <div id=\"activity_header\" class=\"activity_sticky\">Recent Activity</div>\n"
    "      <div class=\"activity_line\">Sync complete — 2 min ago</div>\n"
    "      <div class=\"activity_line\">Theme applied — Indigo</div>\n"
    "      <div class=\"activity_line\">Network profile updated</div>\n"
    "      <div class=\"activity_line\">Backup finished — 128 files</div>\n"
    "      <div class=\"activity_line\">VPN connected — qberry</div>\n"
    "      <div id=\"activity_footer\" class=\"activity_sticky_bottom\">End of feed</div>\n"
    "    </div>\n"
    "  </div>\n"
    "</div>\n"
    "\n"
    "<!-- Right column: Toast -->\n"
    "<div id=\"toast\" class=\"window card\">\n"
    "  <div id=\"toast_bar\">\n"
    "    <div id=\"toast_drag\" draggable=\"1\"></div>\n"
    "    <div id=\"toast_icon\"></div>\n"
    "    <p id=\"toast_title\">Update Available</p>\n"
    "    <p id=\"toast_msg\">Version 2.3 is ready to install.</p>\n"
    "    <div id=\"toast_close\" onclick=\"onToastDismiss()\"></div>\n"
    "  </div>\n"
    "</div>\n"
    "\n"
    "<!-- Right column: System stats glass card -->\n"
    "<div id=\"quick_stats\">\n"
    "  <p id=\"qs_title\">SYSTEM</p>\n"
    "  <div id=\"qs_row1\" class=\"qs_row\">\n"
    "    <p class=\"qs_label\">CPU</p>\n"
    "    <p class=\"qs_val\">42%</p>\n"
    "    <div id=\"qs_dot1\" class=\"qs_dot\"></div>\n"
    "  </div>\n"
    "  <div id=\"qs_row2\" class=\"qs_row\">\n"
    "    <p class=\"qs_label\">MEMORY</p>\n"
    "    <p class=\"qs_val\">2.4 GB</p>\n"
    "    <div id=\"qs_dot2\" class=\"qs_dot\"></div>\n"
    "  </div>\n"
    "  <div id=\"qs_row3\" class=\"qs_row\">\n"
    "    <p class=\"qs_label\">NETWORK</p>\n"
    "    <p class=\"qs_val\">qberry</p>\n"
    "    <div id=\"qs_dot3\" class=\"qs_dot\"></div>\n"
    "  </div>\n"
    "  <div id=\"qs_bar\"><div id=\"qs_bar_fill\"></div></div>\n"
    "  <p id=\"qs_footer\">61% CAPACITY</p>\n"
    "</div>\n"
    "\n"
    "<!-- Right column: Connection status -->\n"
    "<div id=\"status_card\">\n"
    "  <p id=\"sc_title\">CONNECTION</p>\n"
    "  <div id=\"sc_dot\"></div>\n"
    "  <p id=\"sc_status\">Connected</p>\n"
    "  <div id=\"sc_r1\" class=\"sc_row\">\n"
    "    <p class=\"sc_rlabel\">LATENCY</p>\n"
    "    <p class=\"sc_rval\">12ms</p>\n"
    "  </div>\n"
    "  <div id=\"sc_r2\" class=\"sc_row\">\n"
    "    <p class=\"sc_rlabel\">PEERS</p>\n"
    "    <p class=\"sc_rval\">7 online</p>\n"
    "  </div>\n"
    "</div>\n"
    "\n"
    "<!-- Right column: AI assistant -->\n"
    "<div id=\"ai_card\">\n"
    "  <p id=\"ai_title\">AI ASSISTANT</p>\n"
    "  <div id=\"ai_orb\"></div>\n"
    "  <p id=\"ai_status\">Ready</p>\n"
    "  <p id=\"ai_hint\">Click to open</p>\n"
    "</div>\n"
    "\n"
    "<!-- Right column: Transfer -->\n"
    "<div id=\"transfer_card\">\n"
    "  <p id=\"tc_title\">TRANSFER</p>\n"
    "  <div id=\"tc_icon\"></div>\n"
    "  <p id=\"tc_val\">68%  1.2 MB/s</p>\n"
    "  <div id=\"tc_bar_bg\"><div id=\"tc_bar_fill\"></div></div>\n"
    "</div>\n"
    "\n"
    "<!-- Dock (bottom centre) -->\n"
    "<div id=\"dock\" class=\"window\">\n"
    "  <div id=\"dock_icon_info\" class=\"dock_icon\" onclick=\"onDockToggleToast()\">i<p class=\"dock_label\">Info</p></div>\n"
    "  <div id=\"dock_icon_theme\" class=\"dock_icon\" onclick=\"onDockTheme()\">T<p class=\"dock_label\">Theme</p></div>\n"
    "  <div id=\"dock_icon_notify\" class=\"dock_icon\" onclick=\"onDockNotify()\">N<p class=\"dock_label\">Alert</p></div>\n"
    "  <div id=\"dock_icon_toast\" class=\"dock_icon\" onclick=\"onDockToast()\">✕<p class=\"dock_label\">Toast</p></div>\n"
    "</div>\n"
    "\n"
    "<!-- Floating Action Button -->\n"
    "<div id=\"fab\" onclick=\"onScreenshot()\" title=\"Screenshot (F12)\">📷</div>\n"
    "\n"
    "<!-- Modal overlay -->\n"
    "<div id=\"modal_overlay\" class=\"overlay hidden\">\n"
    "  <div id=\"modal_dialog\" class=\"window\">\n"
    "    <div id=\"modal_icon\"></div>\n"
    "    <p id=\"modal_title\">Apply Changes?</p>\n"
    "    <p id=\"modal_msg\">Your preferences will be updated immediately.</p>\n"
    "    <div id=\"modal_cancel\" role=\"button\" onclick=\"onModalCancel()\">Cancel</div>\n"
    "    <div id=\"modal_confirm\" role=\"button\" onclick=\"onModalConfirm()\">Apply</div>\n"
    "  </div>\n"
    "</div>\n"
    "\n"
    "<script>\n"
    "function _el() { return event && event.currentTarget; }\n"
    "function onClose() { window.close(); }\n"
    "function onMinimize() {}\n"
    "function onMaximize() {}\n"
    "function onApply() { document.getElementById('modal_overlay').classList.remove('hidden'); }\n"
    "function onModalCancel() { document.getElementById('modal_overlay').classList.add('hidden'); }\n"
    "function onModalConfirm() {\n"
    "  document.getElementById('desc').textContent = 'Settings applied. Gradient CSS engine active!';\n"
    "  document.getElementById('modal_overlay').classList.add('hidden');\n"
    "}\n"
    "function onNavClick() {\n"
    "  const el = _el();\n"
    "  for (let i = 1; i <= 4; i++) document.getElementById('nav_' + i)?.classList.remove('active');\n"
    "  el.classList.add('active');\n"
    "  document.getElementById('section_title').textContent = el.childNodes[0].textContent.trim();\n"
    "}\n"
    "function onToolClick() {\n"
    "  const el = _el();\n"
    "  document.querySelectorAll('.tool_btn').forEach(b => b.classList.remove('active'));\n"
    "  el.classList.add('active');\n"
    "  document.getElementById('desc').textContent = 'Toolbar: ' + el.textContent + ' selected.';\n"
    "}\n"
    "function onToggleClick() { _el().classList.toggle('on'); }\n"
    "function onCheckboxClick() {\n"
    "  const el = _el();\n"
    "  el.classList.toggle('checked');\n"
    "  document.getElementById('chk_label').textContent =\n"
    "    el.classList.contains('checked') ? 'Notifications: On' : 'Enable Notifications';\n"
    "}\n"
    "function onSelectToggle() { document.getElementById('select_panel').classList.toggle('hidden'); }\n"
    "function onSelectOption() {\n"
    "  const el = _el();\n"
    "  document.getElementById('theme_select_box').textContent = el.textContent + '  ▾';\n"
    "  document.getElementById('select_panel').classList.add('hidden');\n"
    "}\n"
    "function onToastDismiss() { document.getElementById('toast').style.display = 'none'; }\n"
    "function onDockToggleToast() {\n"
    "  const t = document.getElementById('toast');\n"
    "  t.style.display = t.style.display === 'none' ? '' : 'none';\n"
    "}\n"
    "function onDockTheme() { document.getElementById('toggle_knob_track').classList.toggle('on'); }\n"
    "function onDockNotify() { document.getElementById('checkbox_notify').classList.toggle('checked'); }\n"
    "function onDockToast() { document.getElementById('toast').style.display = ''; }\n"
    "function onScreenshot() { alert('Screenshot: press F12 in Vespera GUI, or Print Screen in browser.'); }\n"
    "</script>\n"
    "</body>\n"
    "</html>\n"
