    "/* Vespera GUI Engine v3.10 — browser-compatible shared CSS */\n"
    "html, body { margin: 0; padding: 0; min-height: 100%; background: #b8b8c8; font-family: system-ui, -apple-system, sans-serif; }\n"
    "body { position: relative; min-width: 980px; min-height: 820px; }\n"
    "#main_win, #toast, #info_win, #dock, #modal_overlay { position: absolute; box-sizing: border-box; }\n"
    "#sidebar, #content, #title_bar { position: absolute; box-sizing: border-box; }\n"
    ".window { position: absolute; box-sizing: border-box; }\n"
    "#tag_cloud, #shrink_row, #dense_demo, #col_dense_demo, #toolbar, #chip_row, #theme_combo,\n"
    "#hscroll_panel, #activity_panel, #slider_track, #progress_track, #toast_bar, #modal_dialog,\n"
    "#hscroll_inner { position: absolute; box-sizing: border-box; }\n"
    ".nav_item, .btn_os, .title_drag, .badge, .dock_icon, #apply_btn, #toggle_knob_track, .toggle,\n"
    ".checkbox, #theme_select_box, #select_panel, .select_option, #slider_fill, #slider_thumb,\n"
    ".hscroll_chip, .activity_line, .activity_sticky, .activity_sticky_bottom,\n"
    "#toast_drag, #toast_icon, #toast_close, #info_drag, #info_close, #info_icon,\n"
    "#modal_icon, #modal_cancel, #modal_confirm, #sidebar_avatar, #sep1, #sep2,\n"
    "#section_title, #desc, #toggle_row_label, #chk_label, #theme_label, #slider_label,\n"
    "#progress_label, #status_text, #toast_title, #toast_msg, #info_title, #info_msg,\n"
    "#modal_title, #modal_msg, #sidebar_username, #sidebar_role, #title_text { position: absolute; box-sizing: border-box; }\n"
    ".tag, .shrink_item, .dense_cell, .col_dense_cell, .tool_btn, .chip { position: static; box-sizing: border-box; }\n"
    ".toggle_knob { position: absolute; box-sizing: border-box; }\n"
    "\n"
    ".window { background-color: #f8f9fcff; border-radius: 16px; border-width: 1px;  border-color: #00000014; box-shadow: 0px 18px 48px rgba(0,0,0,0.16); }\n"
    ".window.focused { border-color: #6366f140; box-shadow: 0px 22px 56px rgba(99,102,241,0.22); }\n"
    ".card { border-width: 1px; border-color: #00000010; }\n"
    ".hidden { display: none; }\n"
    "#main_win { width: 720px; height: 660px; left: 140px; top: 90px; z-index: 10; }\n"
    "#title_bar { background-color: transparent; width: 720px; height: 48px; left: 0px; top: 0px; }\n"
    "#title_text { color: #1e1e2eff; background-color: transparent; left: 0px; top: 15px; width: 720px; height: 20px;  text-align: center; font-weight: bold; font-size: 14px; pointer-events: none; }\n"
    ".title_drag { background-color: transparent; width: 720px; height: 48px; left: 0px; top: 0px; cursor: pointer; }\n"
    ".btn_os { width: 13px; height: 13px; border-radius: 7px; top: 18px; cursor: pointer; z-index: 20; }\n"
    "#btn_close { background-color: #ff5f57ff; left: 18px; }\n"
    "#btn_min   { background-color: #febc2eff; left: 38px; }\n"
    "#btn_max   { background-color: #28c840ff; left: 58px; }\n"
    "#btn_close:hover{ background-color: #ff736aff; border-width: 1px; border-color: #e0443e80; }\n"
    "#btn_min:hover{ background-color: #ffcc54ff; border-width: 1px; border-color: #dea12380; }\n"
    "#btn_max:hover{ background-color: #4cd860ff; border-width: 1px; border-color: #1aab2980; }\n"
    "#sidebar { background: linear-gradient(180deg, #1e1e2eff, #2d2d44ff);  border-radius: 0px; width: 196px; height: 612px; left: 0px; top: 48px; }\n"
    "#sidebar_avatar { background: linear-gradient(135deg, #6366f1ff, #a855f7ff);  border-radius: 28px; width: 56px; height: 56px; left: 70px; top: 22px; }\n"
    "#sidebar_username { color: #f0f0f8ff; background-color: transparent; left: 0px; top: 88px;  width: 196px; height: 20px; text-align: center; font-weight: bold; font-size: 14px; }\n"
    "#sidebar_role { color: #9898b0ff; background-color: transparent; left: 0px; top: 108px;  width: 196px; height: 16px; text-align: center; font-size: 11px; }\n"
    ".nav_item { background-color: transparent; color: #b8b8d0ff; width: 168px; height: 36px;  border-radius: 10px; left: 14px; padding: 9px; cursor: pointer; font-size: 14px; transition-duration: 0.15s; }\n"
    ".nav_item:hover{ background-color: #ffffff14; color: #f0f0f8ff; }\n"
    ".nav_item.active { background-color: #6366f128; color: #c7d2feff; font-weight: bold; }\n"
    "#nav_1 { top: 140px; } #nav_2 { top: 182px; } #nav_3 { top: 224px; } #nav_4 { top: 266px; }\n"
    "#tag_cloud { display: flex; flex-wrap: wrap; place-content: center; gap: 5px;  width: 168px; height: 72px; left: 14px; top: 318px; padding: 4px; box-sizing: border-box; }\n"
    ".tag { background-color: #ffffff18; color: #c7d2feff; width: 48px; height: 22px;  border-radius: 11px; text-align: center; font-size: 10px; font-weight: bold; }\n"
    ".tag.wide { width: 64px; flex: 1px 1px 64px; min-width: 48px; }\n"
    "#shrink_row { display: flex; flex-direction: row; gap: 6px; width: 168px; height: 36px;  left: 14px; top: 400px; padding: 4px; box-sizing: border-box;  background-color: #ffffff10; border-radius: 10px; }\n"
    ".shrink_item { background-color: #6366f1ff; color: #ffffffff; height: 28px;  border-radius: 8px; text-align: center; font-size: 11px; font-weight: bold;  flex: 1px 1px 56px; min-width: 36px; max-width: 72px; }\n"
    "#dense_demo { display: grid; grid-template-columns: 44px 44px 44px; grid-template-rows: 22px 22px 22px;  grid-auto-flow: row dense; place-content: center; place-items: center; gap: 3px;  width: 168px; height: 86px; left: 14px; top: 442px; padding: 4px;  box-sizing: border-box; background-color: #ffffff10; border-radius: 10px; }\n"
    ".dense_cell { background-color: #6366f1ff; color: #ffffffff; width: 40px; height: 18px;  border-radius: 6px; text-align: center; font-size: 10px; font-weight: bold; }\n"
    "#dense_wide { grid-column: span 2; width: 84px; background-color: #a855f7ff; }\n"
    "#col_dense_demo { display: grid; grid-auto-flow: column dense;  grid-template-rows: 22px 22px 22px; grid-template-columns: 44px 44px;  place-content: center; place-items: center; gap: 3px;  width: 168px; height: 72px; left: 14px; top: 534px; padding: 4px;  box-sizing: border-box; background-color: #ffffff10; border-radius: 8px; }\n"
    ".col_dense_cell { background-color: #8b5cf6ff; color: #ffffffff; width: 40px; height: 18px;  border-radius: 6px; text-align: center; font-size: 10px; font-weight: bold; }\n"
    "#col_dense_tall { grid-row: span 2; height: 42px; background-color: #ec4899ff; }\n"
    "#col_dense_b { place-self: end center; background-color: #f59e0bff; width: 36px; }\n"
    "#hscroll_panel { background-color: #ececf4ff; border-radius: 10px; width: 280px; height: 36px;  left: 28px; top: 468px; padding: 6px; box-sizing: border-box;  overflow-x: scroll; overflow-y: hidden;  scrollbar-width: thin; scrollbar-color: #8b5cf6cc #ececf4ff; }\n"
    "#hscroll_inner { background-color: transparent; width: 560px; height: 24px; left: 0px; top: 0px; }\n"
    ".hscroll_chip { background-color: #6366f1ff; color: #ffffffff; width: 72px; height: 24px;  border-radius: 8px; text-align: center; font-size: 10px; font-weight: bold; }\n"
    "#hs_pin { position: sticky; left: 0px; background-color: #ec4899ff; width: 56px; z-index: 2; }\n"
    "#hs_1 { left: 64px; } #hs_2 { left: 144px; } #hs_3 { left: 224px; } #hs_4 { left: 304px; } #hs_5 { left: 384px; } #hs_6 { left: 464px; }\n"
    "#content { background-color: transparent; width: 524px; height: 612px; left: 196px; top: 48px; }\n"
    "#section_title { color: #1e1e2eff; background-color: transparent; left: 28px; top: 20px;  width: 468px; height: 28px; font-size: 22px; font-weight: bold; }\n"
    "#desc { color: #5c5c72ff; background-color: transparent; width: 468px; height: 40px;  left: 28px; top: 54px; padding: 0px; font-size: 14px; }\n"
    "#sep1 { background-color: #00000010; height: 1px; width: 468px; left: 28px; top: 102px; }\n"
    "#toolbar { display: flex; flex-direction: row; justify-content: space-between; align-items: center;  gap: 10px; width: 468px; height: 40px; left: 28px; top: 114px; padding: 0px; }\n"
    ".tool_btn { background-color: #ececf4ff; color: #3a3a50ff; height: 36px; border-radius: 10px;  text-align: center; font-size: 13px; font-weight: bold; cursor: pointer;  transition-duration: 0.12s; flex: 1px 1px auto; }\n"
    "#tool_save  { flex: 1px 1px 88px; }\n"
    "#tool_reset { flex: 1px 1px 88px; }\n"
    "#tool_export { flex: 2px 1px 160px; }\n"
    ".tool_btn:hover{ background-color: #dfe0ebff; color: #1e1e2eff; }\n"
    ".tool_btn.active { background: linear-gradient(135deg, #6366f1ff, #8b5cf6ff); color: #ffffffff; }\n"
    "#apply_btn { background: linear-gradient(135deg, #6366f1ff, #8b5cf6ff, #a855f7ff);  color: #ffffffff; width: 168px; height: 40px; border-radius: 12px; left: 28px; top: 166px;  padding: 9px; text-align: center; font-weight: bold; cursor: pointer; transition-duration: 0.12s; }\n"
    "#apply_btn:hover{ background: linear-gradient(135deg, #818cf8ff, #a78bfaff); }\n"
    "#apply_btn:active{ background: linear-gradient(135deg, #4f46e5ff, #7c3aedff); }\n"
    "#apply_btn:focus-visible{ outline-width: 2px; outline-color: #6366f1aa; outline-offset: 2px; }\n"
    ".tool_btn:focus-visible{ outline-width: 2px; outline-color: #6366f180; }\n"
    ".nav_item:focus-visible{ background-color: #ffffff20; outline-width: 1px; outline-color: #c7d2feff; }\n"
    "#modal_cancel:focus-visible, #modal_confirm:focus-visible{ outline-width: 2px; outline-color: #6366f1cc; outline-offset: 1px; }\n"
    ".select_option:focus-visible{ outline-width: 1px; outline-color: #6366f1aa; background-color: #6366f114; }\n"
    "#chip_row { display: flex; flex-wrap: wrap; place-content: space-between center; gap: 8px;  width: 468px; height: 72px; left: 28px; top: 214px; align-items: center; }\n"
    ".chip { background-color: #ececf4ff; color: #3a3a50ff; width: 72px; height: 28px;  border-radius: 14px; text-align: center; font-size: 11px; font-weight: bold; }\n"
    ".chip.accent { background: linear-gradient(135deg, #6366f1ff, #8b5cf6ff); color: #ffffffff; }\n"
    "#chip_wide { width: 110px; align-self: stretch; }\n"
    "#toggle_row_label { color: #3a3a50ff; background-color: transparent; left: 28px; top: 296px;  width: 200px; height: 24px; font-size: 14px; }\n"
    ".toggle { width: 48px; height: 28px; border-radius: 14px; background-color: #d4d4e0ff;  left: 420px; top: 292px; cursor: pointer; }\n"
    ".toggle.on { background-color: #6366f1ff; }\n"
    ".toggle_knob { width: 22px; height: 22px; border-radius: 11px; background-color: #ffffffff;  box-shadow: 0px 2px 4px rgba(0,0,0,0.22); left: 3px; top: 3px; transition-duration: 0.15s; }\n"
    ".checkbox { width: 22px; height: 22px; border-radius: 7px; background-color: #ffffffff;  border-width: 2px; border-color: #c8c8d8ff; left: 28px; top: 336px; cursor: pointer; }\n"
    ".checkbox.checked { background-color: #6366f1ff; border-color: #4f46e5ff; }\n"
    "#chk_label { color: #3a3a50ff; background-color: transparent; left: 60px; top: 338px;  width: 300px; height: 24px; font-size: 14px; }\n"
    "#theme_label { color: #3a3a50ff; background-color: transparent; left: 28px; top: 374px;  width: 80px; height: 24px; font-size: 14px; }\n"
    "#theme_combo { background-color: transparent; left: 120px; top: 370px; width: 156px; height: 32px; }\n"
    "#theme_combo:focus-within{ background-color: #6366f110; border-radius: 10px;  border-width: 1px; border-color: #6366f160; }\n"
    "#theme_select_box { background-color: #ffffffff; color: #2a2a3aff; border-width: 1px;  border-color: #d8d8e8ff; border-radius: 10px; left: 0px; top: 0px; width: 156px; height: 32px;  padding: 7px; cursor: pointer; font-size: 13px; box-sizing: border-box; }\n"
    "#theme_select_box:hover{ border-color: #6366f1ff; }\n"
    "#theme_select_box:focus-visible{ border-color: #6366f1ff; border-width: 2px; }\n"
    "#select_panel { background-color: #ffffffff; border-radius: 10px; border-width: 1px;  border-color: #e0e0efff; left: 0px; top: 36px; width: 156px; height: 90px;  box-shadow: 0px 10px 28px rgba(0,0,0,0.16); z-index: 200; }\n"
    ".select_option { background-color: transparent; color: #2a2a3aff; width: 156px; height: 30px;  left: 0px; padding: 7px; cursor: pointer; font-size: 13px; }\n"
    ".select_option:hover{ background-color: #6366f114; color: #6366f1ff; }\n"
    "#opt_blue { top: 0px; } #opt_graphite { top: 30px; } #opt_green { top: 60px; }\n"
    "#slider_label { color: #7a7a90ff; background-color: transparent; left: 28px; top: 418px;  width: 300px; height: 18px; font-size: 13px; }\n"
    "#slider_track { background-color: #e8e8f0ff; border-radius: 5px; width: 420px; height: 8px;  left: 28px; top: 444px; }\n"
    "#slider_fill { background: linear-gradient(90deg, #6366f1ff, #a855f7ff);  border-radius: 5px; width: 294px; height: 8px; left: 0px; top: 0px; }\n"
    "#slider_thumb { background-color: #ffffffff; border-radius: 11px; width: 24px; height: 24px;  border-width: 2px; border-color: #6366f1ff; left: 282px; top: -8px;  box-shadow: 0px 2px 8px rgba(0,0,0,0.16); cursor: pointer; }\n"
    "#progress_label { color: #7a7a90ff; background-color: transparent; left: 28px; top: 510px;  width: 300px; height: 18px; font-size: 13px; }\n"
    "#progress_track { background-color: #e8e8f0ff; border-radius: 5px; width: 420px; height: 8px;  left: 28px; top: 534px; }\n"
    "#progress_fill  { background: linear-gradient(90deg, #22d3eeff, #6366f1ff);  border-radius: 5px; width: 0px; height: 8px; left: 0px; top: 0px; }\n"
    "#activity_panel { background-color: #ececf4ff; border-radius: 10px; width: 468px; height: 68px;  left: 28px; top: 550px; padding: 6px; box-sizing: border-box; overflow-y: scroll; overflow-x: hidden;  scroll-behavior: smooth; scroll-padding: 20px 0px 18px 0px; scroll-snap-type: y mandatory;  scrollbar-width: thin; scrollbar-color: #6366f1cc #dfe0ebff; }\n"
    ".activity_sticky { position: sticky; top: 0px; left: 0px; background-color: #ececf4ff; color: #3a3a50ff;  width: 456px; height: 18px; left: 0px; font-size: 11px; font-weight: bold; padding: 2px; }\n"
    ".activity_sticky_bottom { position: sticky; bottom: 0px; background-color: #6366f1ff; color: #ffffffff;  width: 456px; height: 16px; left: 0px; font-size: 10px; font-weight: bold; text-align: center; padding: 2px; }\n"
    ".activity_line { background-color: transparent; color: #5c5c72ff; width: 456px; height: 18px;  left: 0px; font-size: 12px; padding: 2px; scroll-margin: 6px; scroll-snap-align: start; }\n"
    "#act_1 { top: 20px; } #act_2 { top: 38px; } #act_3 { top: 56px; } #act_4 { top: 74px; } #act_5 { top: 92px; } #act_6 { top: 110px; } #activity_footer { top: 128px; }\n"
    ".badge { border-radius: 11px; height: 24px; padding: 5px; font-size: 11px;  text-align: center; color: #ffffffff; font-weight: bold; }\n"
    "#badge_active { background-color: #22c55eff; width: 64px; left: 28px; top: 610px; }\n"
    "#badge_update { background-color: #f59e0bff; width: 64px; left: 100px; top: 610px; }\n"
    "#badge_err    { background-color: #ef4444ff; width: 64px; left: 172px; top: 610px; }\n"
    "#sep2 { background-color: #00000010; height: 1px; width: 468px; left: 28px; top: 642px; }\n"
    "#status_text { color: #9898b0ff; background-color: transparent; right: 28px; bottom: 8px;  width: 468px; height: 18px; font-size: 12px; text-align: right; }\n"
    "#toast { width: 340px; height: 88px; left: 720px; top: 36px; z-index: 20; }\n"
    "#toast_bar { background-color: transparent; width: 340px; height: 88px; left: 0px; top: 0px; }\n"
    "#toast_drag { background-color: transparent; width: 280px; height: 88px; left: 0px; top: 0px; cursor: pointer; }\n"
    "#toast_icon { background: linear-gradient(135deg, #6366f1ff, #a855f7ff);  border-radius: 18px; width: 40px; height: 40px; left: 18px; top: 24px; }\n"
    "#toast_title { color: #1e1e2eff; background-color: transparent; left: 70px; top: 20px;  width: 200px; height: 20px; font-weight: bold; font-size: 14px; }\n"
    "#toast_msg   { color: #7a7a90ff; background-color: transparent; left: 70px; top: 42px;  width: 200px; height: 30px; font-size: 12px; }\n"
    "#toast_close { background-color: transparent; color: #9898b0ff; border-radius: 11px;  width: 26px; height: 26px; left: 302px; top: 10px; text-align: center; cursor: pointer; font-size: 14px; z-index: 25; }\n"
    "#toast_close:hover{ background-color: #00000010; color: #3a3a50ff; }\n"
    "#info_win { width: 320px; height: 200px; left: 48px; top: 520px; z-index: 15; }\n"
    "#info_drag { background-color: transparent; width: 280px; height: 44px; left: 0px; top: 0px; cursor: pointer; }\n"
    "#info_close { background-color: #00000008; color: #7a7a90ff; border-radius: 11px;  width: 26px; height: 26px; left: 282px; top: 12px; text-align: center; cursor: pointer; z-index: 25; }\n"
    "#info_close:hover{ background-color: #00000014; color: #3a3a50ff; }\n"
    "#info_icon { background: linear-gradient(135deg, #34d399ff, #059669ff);  border-radius: 28px; width: 56px; height: 56px; left: 132px; top: 48px; }\n"
    "#info_title { color: #1e1e2eff; background-color: transparent; width: 320px; height: 22px;  left: 0px; top: 112px; text-align: center; font-weight: bold; font-size: 16px; }\n"
    "#info_msg { color: #5c5c72ff; background-color: transparent; width: 280px; height: 50px;  left: 20px; top: 138px; text-align: center; font-size: 13px; }\n"
    "#dock { background-color: #f8f9fcdd; border-radius: 22px; border-width: 1px;  border-color: #ffffffaa; width: 280px; height: 68px; left: 372px; top: 680px;  box-shadow: 0px 10px 32px rgba(0,0,0,0.18); z-index: 30; }\n"
    ".dock_icon { width: 46px; height: 46px; top: 11px; border-radius: 14px; cursor: pointer;  text-align: center; font-weight: bold; color: #ffffffff; transition-duration: 0.12s; }\n"
    ".dock_icon:hover{ transform: scale(1.1) translateY(-5px); }\n"
    "#dock_icon_info   { background: linear-gradient(135deg, #34d399ff, #059669ff); left: 14px; }\n"
    "#dock_icon_theme  { background: linear-gradient(135deg, #fbbf24ff, #f59e0bff); left: 78px; }\n"
    "#dock_icon_notify { background: linear-gradient(135deg, #60a5faff, #6366f1ff); left: 142px; }\n"
    "#dock_icon_toast  { background: linear-gradient(135deg, #f87171ff, #ef4444ff); left: 206px; }\n"
    "#modal_overlay { background-color: rgba(15,15,25,0.55); width: 100%; height: 100%;  left: 0px; top: 0px; border-radius: 0px; z-index: 100; }\n"
    "#modal_dialog  { width: 400px; height: 248px; left: 312px; top: 256px; z-index: 110; }\n"
    "#modal_icon    { background: linear-gradient(135deg, #6366f1ff, #a855f7ff);  border-radius: 26px; width: 52px; height: 52px; left: 174px; top: 24px; }\n"
    "#modal_title   { color: #1e1e2eff; background-color: transparent; width: 400px; height: 24px;  left: 0px; top: 88px; text-align: center; font-weight: bold; font-size: 18px; }\n"
    "#modal_msg     { color: #5c5c72ff; background-color: transparent; width: 340px; height: 44px;  left: 30px; top: 118px; text-align: center; font-size: 14px; }\n"
    "#modal_cancel  { background-color: #f0f0f8ff; color: #3a3a50ff; width: 148px; height: 42px;  border-radius: 12px; left: 36px; top: 182px; text-align: center; cursor: pointer;  border-width: 1px; border-color: #00000014; }\n"
    "#modal_cancel:hover{ background-color: #e4e4f0ff; }\n"
    "#modal_cancel:active{ background-color: #d4d4e4ff; }\n"
    "#modal_confirm { background: linear-gradient(135deg, #6366f1ff, #8b5cf6ff);  color: #ffffffff; width: 148px; height: 42px; border-radius: 12px; left: 216px; top: 182px;  text-align: center; font-weight: bold; cursor: pointer; }\n"
    "#modal_confirm:hover{ background: linear-gradient(135deg, #818cf8ff, #a78bfaff); }\n"
    "#modal_confirm:active{ background: linear-gradient(135deg, #4f46e5ff, #7c3aedff); }\n"
