    "<!DOCTYPE html>\n"
    "<html lang=\"en\">\n"
    "<head>\n"
    "  <meta charset=\"utf-8\">\n"
    "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
    "  <title>Vespera GUI Engine v3.12</title>\n"
    "  <link rel=\"stylesheet\" type=\"text/css\" href=\"demo_style.css\">\n"
    "</head>\n"
    "<body>\n"
    "<div id=\"main_win\" class=\"window focused\">\n"
    "  <div id=\"title_bar\">\n"
    "    <div id=\"title_drag\" class=\"title_drag\" draggable=\"1\"></div>\n"
    "    <div id=\"btn_close\" class=\"btn_os\"></div>\n"
    "    <div id=\"btn_min\" class=\"btn_os\"></div>\n"
    "    <div id=\"btn_max\" class=\"btn_os\"></div>\n"
    "    <p id=\"title_text\">System Preferences</p>\n"
    "  </div>\n"
    "  <div id=\"sidebar\">\n"
    "    <div id=\"sidebar_avatar\"></div>\n"
    "    <p id=\"sidebar_username\">Vespera User</p>\n"
    "    <p id=\"sidebar_role\">Administrator</p>\n"
    "    <div id=\"nav_1\" class=\"nav_item active\">General<div id=\"nav_dot_1\" class=\"nav_dot\"></div></div>\n"
    "    <div id=\"nav_2\" class=\"nav_item\">Appearance<div id=\"nav_dot_2\" class=\"nav_dot\"></div></div>\n"
    "    <div id=\"nav_3\" class=\"nav_item\">Network</div>\n"
    "    <div id=\"nav_4\" class=\"nav_item\">Security</div>\n"
    "    <div id=\"tag_cloud\">\n"
    "      <div class=\"tag\">CSS</div>\n"
    "      <div class=\"tag\">Flex</div>\n"
    "      <div class=\"tag wide\">Shrink</div>\n"
    "      <div class=\"tag\">Grid</div>\n"
    "      <div class=\"tag\">Flow</div>\n"
    "      <div class=\"tag wide\">Clip</div>\n"
    "    </div>\n"
    "    <div id=\"shrink_row\">\n"
    "      <div class=\"shrink_item\">A</div>\n"
    "      <div class=\"shrink_item\">BB</div>\n"
    "      <div class=\"shrink_item\">CCC</div>\n"
    "      <div class=\"shrink_item\">DD</div>\n"
    "    </div>\n"
    "    <div id=\"dense_demo\">\n"
    "      <div id=\"dense_wide\" class=\"dense_cell\">Wide</div>\n"
    "      <div class=\"dense_cell\">1</div>\n"
    "      <div class=\"dense_cell\">2</div>\n"
    "      <div class=\"dense_cell\">3</div>\n"
    "      <div class=\"dense_cell\">4</div>\n"
    "    </div>\n"
    "    <div id=\"col_dense_demo\">\n"
    "      <div id=\"col_dense_tall\" class=\"col_dense_cell\">T</div>\n"
    "      <div id=\"col_dense_b\" class=\"col_dense_cell\">B</div>\n"
    "      <div class=\"col_dense_cell\">1</div>\n"
    "      <div class=\"col_dense_cell\">2</div>\n"
    "      <div class=\"col_dense_cell\">3</div>\n"
    "    </div>\n"
    "    <div id=\"stat_cpu\" class=\"stat_card\">\n"
    "      <p class=\"stat_label\">CPU</p>\n"
    "      <p class=\"stat_val\">42%</p>\n"
    "      <div class=\"stat_bar_bg\"><div id=\"cpu_bar_fill\" class=\"stat_bar_fill\"></div></div>\n"
    "    </div>\n"
    "    <div id=\"stat_mem\" class=\"stat_card\">\n"
    "      <p class=\"stat_label\">MEM</p>\n"
    "      <p class=\"stat_val\">2.4G</p>\n"
    "      <div class=\"stat_bar_bg\"><div id=\"mem_bar_fill\" class=\"stat_bar_fill\"></div></div>\n"
    "    </div>\n"
    "    <div id=\"stat_net\" class=\"stat_card\">\n"
    "      <p class=\"stat_label\">NET</p>\n"
    "      <p class=\"stat_val\">72K</p>\n"
    "      <div class=\"stat_bar_bg\"><div id=\"net_bar_fill\" class=\"stat_bar_fill\"></div></div>\n"
    "    </div>\n"
    "    <p id=\"sidebar_version\">v3.12.0 — Vespera</p>\n"
    "  </div>\n"
    "  <div id=\"content\">\n"
    "    <p id=\"section_title\">General</p>\n"
    "    <p id=\"desc\" aria-live=\"polite\">Position, px units, browser-matched CSS.</p>\n"
    "    <div id=\"sep1\"></div>\n"
    "    <div id=\"toolbar\">\n"
    "      <div id=\"tool_save\" class=\"tool_btn active\" role=\"button\" aria-label=\"Save settings\">Save</div>\n"
    "      <div id=\"tool_reset\" class=\"tool_btn\" role=\"button\">Reset</div>\n"
    "      <div id=\"tool_export\" class=\"tool_btn\" role=\"button\">Export</div>\n"
    "    </div>\n"
    "    <div id=\"apply_btn\" aria-label=\"Apply all pending settings\">Apply Changes</div>\n"
    "    <div id=\"chip_row\">\n"
    "      <div class=\"chip accent\" aria-hidden=\"true\">CSS</div>\n"
    "      <div class=\"chip\" aria-hidden=\"true\">Flex</div>\n"
    "      <div class=\"chip\">Grid</div>\n"
    "      <div class=\"chip\">HSL</div>\n"
    "      <div class=\"chip\">Wrap</div>\n"
    "      <div class=\"chip\">Self</div>\n"
    "      <div id=\"chip_wide\" class=\"chip\">Axis</div>\n"
    "      <div class=\"chip\">GLSL</div>\n"
    "      <div class=\"chip\">Focus</div>\n"
    "    </div>\n"
    "    <p id=\"toggle_row_label\">Dark Mode</p>\n"
    "    <div id=\"toggle_knob_track\" class=\"toggle\">\n"
    "      <div id=\"toggle_knob\" class=\"toggle_knob\"></div>\n"
    "    </div>\n"
    "    <div id=\"checkbox_notify\" class=\"checkbox\"></div>\n"
    "    <p id=\"chk_label\">Enable Notifications</p>\n"
    "    <p id=\"theme_label\">Theme</p>\n"
    "    <div id=\"theme_combo\">\n"
    "      <div id=\"theme_select_box\" role=\"combobox\" aria-label=\"Theme\" aria-expanded=\"false\">Indigo  ▾</div>\n"
    "      <div id=\"select_panel\" class=\"card hidden\">\n"
    "        <div id=\"opt_blue\" class=\"select_option\">Indigo</div>\n"
    "        <div id=\"opt_graphite\" class=\"select_option\">Graphite</div>\n"
    "        <div id=\"opt_green\" class=\"select_option\">Emerald</div>\n"
    "      </div>\n"
    "    </div>\n"
    "    <p id=\"slider_label\">Brightness: 70%</p>\n"
    "    <div id=\"slider_track\">\n"
    "      <div id=\"slider_fill\"></div>\n"
    "      <div id=\"slider_thumb\" draggable=\"2\"></div>\n"
    "    </div>\n"
    "    <div id=\"hscroll_panel\">\n"
    "      <div id=\"hscroll_inner\">\n"
    "        <div id=\"hs_pin\" class=\"hscroll_chip\">Pin</div>\n"
    "        <div id=\"hs_1\" class=\"hscroll_chip\">Alpha</div>\n"
    "        <div id=\"hs_2\" class=\"hscroll_chip\">Beta</div>\n"
    "        <div id=\"hs_3\" class=\"hscroll_chip\">Gamma</div>\n"
    "        <div id=\"hs_4\" class=\"hscroll_chip\">Delta</div>\n"
    "        <div id=\"hs_5\" class=\"hscroll_chip\">Epsilon</div>\n"
    "        <div id=\"hs_6\" class=\"hscroll_chip\">Zeta</div>\n"
    "      </div>\n"
    "    </div>\n"
    "    <p id=\"progress_label\">Syncing...</p>\n"
    "    <div id=\"progress_track\">\n"
    "      <div id=\"progress_fill\"></div>\n"
    "    </div>\n"
    "    <!-- activity_panel uses normal document flow for scrollable items -->\n"
    "    <div id=\"activity_panel\">\n"
    "      <div id=\"activity_header\" class=\"activity_sticky\">Recent Activity</div>\n"
    "      <div id=\"act_1\" class=\"activity_line\">Sync complete — 2 min ago</div>\n"
    "      <div id=\"act_2\" class=\"activity_line\">Theme applied — Indigo</div>\n"
    "      <div id=\"act_3\" class=\"activity_line\">Network profile updated</div>\n"
    "      <div id=\"act_4\" class=\"activity_line\">Backup finished — 128 files</div>\n"
    "      <div id=\"act_5\" class=\"activity_line\">Driver update available</div>\n"
    "      <div id=\"act_6\" class=\"activity_line\">VPN connected — qberry</div>\n"
    "      <div id=\"activity_footer\" class=\"activity_sticky_bottom\">End of feed</div>\n"
    "    </div>\n"
    "    <div id=\"badge_active\" class=\"badge\">Active</div>\n"
    "    <div id=\"badge_update\" class=\"badge\">Update</div>\n"
    "    <div id=\"badge_err\"    class=\"badge\">Error</div>\n"
    "    <div id=\"sep2\"></div>\n"
    "    <div id=\"metrics_row\">\n"
    "      <div id=\"mp_online\" class=\"metric_pill\">\n"
    "        <p id=\"mp_val_online\" class=\"mp_val\">Online</p>\n"
    "        <p id=\"mp_lbl_online\" class=\"mp_label\">STATUS</p>\n"
    "      </div>\n"
    "      <div id=\"mp_peers\" class=\"metric_pill\">\n"
    "        <p id=\"mp_val_peers\" class=\"mp_val\">7</p>\n"
    "        <p id=\"mp_lbl_peers\" class=\"mp_label\">PEERS</p>\n"
    "      </div>\n"
    "      <div id=\"mp_latency\" class=\"metric_pill\">\n"
    "        <p id=\"mp_val_lat\" class=\"mp_val\">12ms</p>\n"
    "        <p id=\"mp_lbl_lat\" class=\"mp_label\">PING</p>\n"
    "      </div>\n"
    "    </div>\n"
    "    <p id=\"status_text\" aria-live=\"assertive\">v3.12.0 — Vespera GUI Engine</p>\n"
    "  </div>\n"
    "</div>\n"
    "<div id=\"toast\" class=\"window card\">\n"
    "  <div id=\"toast_bar\">\n"
    "    <div id=\"toast_drag\" draggable=\"1\"></div>\n"
    "    <div id=\"toast_icon\"></div>\n"
    "    <p id=\"toast_title\">Update Available</p>\n"
    "    <p id=\"toast_msg\">Version 2.3 is ready to install.</p>\n"
    "    <div id=\"toast_close\"></div>\n"
    "  </div>\n"
    "</div>\n"
    "<div id=\"info_win\" class=\"window card\">\n"
    "  <div id=\"info_drag\" draggable=\"1\"></div>\n"
    "  <div id=\"info_close\"></div>\n"
    "  <div id=\"info_icon\"></div>\n"
    "  <p id=\"info_title\">Vespera GUI Engine</p>\n"
    "  <p id=\"info_msg\">OpenGL window manager with CSS styling, gradients, and smooth transitions.</p>\n"
    "</div>\n"
    "<div id=\"dock\" class=\"window\">\n"
    "  <div id=\"dock_icon_info\" class=\"dock_icon\">i<p class=\"dock_label\">Info</p></div>\n"
    "  <div id=\"dock_icon_theme\" class=\"dock_icon\">T<p class=\"dock_label\">Theme</p></div>\n"
    "  <div id=\"dock_icon_notify\" class=\"dock_icon\">N<p class=\"dock_label\">Alert</p></div>\n"
    "  <div id=\"dock_icon_toast\" class=\"dock_icon\">✕<p class=\"dock_label\">Toast</p></div>\n"
    "</div>\n"
    "<div id=\"quick_stats\">\n"
    "  <p id=\"qs_title\">SYSTEM</p>\n"
    "  <div id=\"qs_row1\" class=\"qs_row\">\n"
    "    <p class=\"qs_label\">CPU</p>\n"
    "    <p class=\"qs_val\">42%</p>\n"
    "    <div id=\"qs_dot1\" class=\"qs_dot\"></div>\n"
    "  </div>\n"
    "  <div id=\"qs_row2\" class=\"qs_row\">\n"
    "    <p class=\"qs_label\">MEMORY</p>\n"
    "    <p class=\"qs_val\">2.4 GB</p>\n"
    "    <div id=\"qs_dot2\" class=\"qs_dot\"></div>\n"
    "  </div>\n"
    "  <div id=\"qs_row3\" class=\"qs_row\">\n"
    "    <p class=\"qs_label\">NETWORK</p>\n"
    "    <p class=\"qs_val\">qberry</p>\n"
    "    <div id=\"qs_dot3\" class=\"qs_dot\"></div>\n"
    "  </div>\n"
    "  <div id=\"qs_bar\"><div id=\"qs_bar_fill\"></div></div>\n"
    "  <p id=\"qs_footer\">61% CAPACITY</p>\n"
    "</div>\n"
    "<div id=\"vtoolbar\">\n"
    "  <div id=\"vtb_home\" class=\"vtb active\">H</div>\n"
    "  <div id=\"vtb_net\" class=\"vtb\">N</div>\n"
    "  <div id=\"vtb_sec\" class=\"vtb\">S</div>\n"
    "  <div id=\"vtb_sep\"></div>\n"
    "  <div id=\"vtb_app\" class=\"vtb\">A</div>\n"
    "  <div id=\"vtb_log\" class=\"vtb\">L</div>\n"
    "  <div id=\"vtb_sep2\"></div>\n"
    "  <div id=\"vtb_ai\" class=\"vtb\">AI</div>\n"
    "  <div id=\"vtb_cfg\" class=\"vtb\">C</div>\n"
    "</div>\n"
    "<div id=\"ai_card\">\n"
    "  <p id=\"ai_title\">AI ASSISTANT</p>\n"
    "  <div id=\"ai_orb\"></div>\n"
    "  <p id=\"ai_status\">Ready</p>\n"
    "  <p id=\"ai_hint\">Click to open</p>\n"
    "</div>\n"
    "<div id=\"status_card\">\n"
    "  <p id=\"sc_title\">CONNECTION</p>\n"
    "  <div id=\"sc_dot\"></div>\n"
    "  <p id=\"sc_status\">Connected</p>\n"
    "  <div id=\"sc_r1\" class=\"sc_row\">\n"
    "    <p class=\"sc_rlabel\">LATENCY</p>\n"
    "    <p class=\"sc_rval\">12ms</p>\n"
    "  </div>\n"
    "  <div id=\"sc_r2\" class=\"sc_row\">\n"
    "    <p class=\"sc_rlabel\">PEERS</p>\n"
    "    <p class=\"sc_rval\">7 online</p>\n"
    "  </div>\n"
    "</div>\n"
    "<!-- Notification pill -->\n"
    "<div id=\"notif_pill\">\n"
    "  <div id=\"notif_dot\"></div>\n"
    "  <p id=\"notif_text\">VPN connected — 7 peers online</p>\n"
    "  <p id=\"notif_close\">✕</p>\n"
    "</div>\n"
    "\n"
    "<!-- Media / Image card -->\n"
    "<div id=\"media_card\">\n"
    "  <img id=\"media_img\" src=\"avatar.jpg\" alt=\"\">\n"
    "  <p id=\"media_label\">Preview</p>\n"
    "  <p id=\"media_sub\">background-image</p>\n"
    "  <div id=\"media_badge\">NEW</div>\n"
    "</div>\n"
    "\n"
    "<!-- Transfer card -->\n"
    "<div id=\"transfer_card\">\n"
    "  <p id=\"tc_title\">TRANSFER</p>\n"
    "  <div id=\"tc_icon\"></div>\n"
    "  <p id=\"tc_val\">68%  1.2 MB/s</p>\n"
    "  <div id=\"tc_bar_bg\"><div id=\"tc_bar_fill\"></div></div>\n"
    "</div>\n"
    "\n"
    "<!-- Pill tab bar -->\n"
    "<div id=\"tab_bar\">\n"
    "  <div class=\"tab_pill active\">All</div>\n"
    "  <div class=\"tab_pill\">VPN</div>\n"
    "  <div class=\"tab_pill\">Log</div>\n"
    "</div>\n"
    "\n"
    "<!-- Color swatches -->\n"
    "<div id=\"swatch_row\">\n"
    "  <div id=\"sw1\" class=\"swatch sel\"></div>\n"
    "  <div id=\"sw2\" class=\"swatch\"></div>\n"
    "  <div id=\"sw3\" class=\"swatch\"></div>\n"
    "  <div id=\"sw4\" class=\"swatch\"></div>\n"
    "  <div id=\"sw5\" class=\"swatch\"></div>\n"
    "</div>\n"
    "\n"
    "<!-- Keyboard shortcuts card -->\n"
    "<div id=\"kbd_card\">\n"
    "  <p id=\"kbd_title\">SHORTCUTS</p>\n"
    "  <div id=\"kr1\" class=\"kbd_row\">\n"
    "    <p class=\"kbd_label\">Connect</p>\n"
    "    <p class=\"kbd_key\">⌘ C</p>\n"
    "  </div>\n"
    "  <div id=\"kr2\" class=\"kbd_row\">\n"
    "    <p class=\"kbd_label\">Settings</p>\n"
    "    <p class=\"kbd_key\">⌘ ,</p>\n"
    "  </div>\n"
    "  <div id=\"kr3\" class=\"kbd_row\">\n"
    "    <p class=\"kbd_label\">Quit</p>\n"
    "    <p class=\"kbd_key\">⌘ Q</p>\n"
    "  </div>\n"
    "</div>\n"
    "\n"
    "<div id=\"cmd_palette\">\n"
    "  <p id=\"cmd_icon\">⌘</p>\n"
    "  <p id=\"cmd_text\">Search or type a command...</p>\n"
    "  <p id=\"cmd_key\">⌘ K</p>\n"
    "</div>\n"
    "\n"
    "<!-- Floating Action Button -->\n"
    "<div id=\"fab\">+</div>\n"
    "\n"
    "<div id=\"modal_overlay\" class=\"overlay hidden\">\n"
    "  <div id=\"modal_dialog\" class=\"window\">\n"
    "    <div id=\"modal_icon\"></div>\n"
    "    <p id=\"modal_title\">Apply Changes?</p>\n"
    "    <p id=\"modal_msg\">Your preferences will be updated immediately.</p>\n"
    "    <div id=\"modal_cancel\" role=\"button\" aria-label=\"Cancel dialog\">Cancel</div>\n"
    "    <div id=\"modal_confirm\" role=\"button\" aria-label=\"Confirm and apply\">Apply</div>\n"
    "  </div>\n"
    "</div>\n"
    "</body>\n"
    "</html>\n"
