    "<!DOCTYPE html>\n"
    "<html lang=\"en\">\n"
    "<head>\n"
    "  <meta charset=\"utf-8\">\n"
    "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
    "  <title>Luna Desktop</title>\n"
    "  <link rel=\"stylesheet\" type=\"text/css\" href=\"luna-shell.css\">\n"
    "</head>\n"
    "<body>\n"
    "\n"
    "<!-- ── Wallpaper: Luna night sky ── -->\n"
    "<div id=\"wallpaper\"></div>\n"
    "<div id=\"wp_aurora1\"></div>\n"
    "<div id=\"wp_aurora2\"></div>\n"
    "<div id=\"wp_star1\" class=\"star\"></div>\n"
    "<div id=\"wp_star2\" class=\"star\"></div>\n"
    "<div id=\"wp_star3\" class=\"star\"></div>\n"
    "<div id=\"wp_star4\" class=\"star\"></div>\n"
    "<div id=\"wp_star5\" class=\"star\"></div>\n"
    "<div id=\"wp_star6\" class=\"star\"></div>\n"
    "<div id=\"wp_star7\" class=\"star\"></div>\n"
    "<div id=\"wp_star8\" class=\"star\"></div>\n"
    "<div id=\"wp_moon_halo\"></div>\n"
    "<div id=\"wp_moon\"></div>\n"
    "\n"
    "<!-- ── Menu bar ── -->\n"
    "<div id=\"menubar\">\n"
    "  <div id=\"mb_left\">\n"
    "    <div id=\"mb_logo\" class=\"mb_item\" onclick=\"onLunaMenu()\"><div id=\"logo_disc\"></div><div id=\"logo_bite\"></div></div>\n"
    "  </div>\n"
    "  <div id=\"mb_center\">\n"
    "    <div id=\"win_list\">\n"
    "      <div id=\"win_0\"  class=\"win_item hidden\" onclick=\"onWinClick()\"><span class=\"win_label\">App</span></div>\n"
    "      <div id=\"win_1\"  class=\"win_item hidden\" onclick=\"onWinClick()\"><span class=\"win_label\">App</span></div>\n"
    "      <div id=\"win_2\"  class=\"win_item hidden\" onclick=\"onWinClick()\"><span class=\"win_label\">App</span></div>\n"
    "      <div id=\"win_3\"  class=\"win_item hidden\" onclick=\"onWinClick()\"><span class=\"win_label\">App</span></div>\n"
    "      <div id=\"win_4\"  class=\"win_item hidden\" onclick=\"onWinClick()\"><span class=\"win_label\">App</span></div>\n"
    "      <div id=\"win_5\"  class=\"win_item hidden\" onclick=\"onWinClick()\"><span class=\"win_label\">App</span></div>\n"
    "      <div id=\"win_6\"  class=\"win_item hidden\" onclick=\"onWinClick()\"><span class=\"win_label\">App</span></div>\n"
    "      <div id=\"win_7\"  class=\"win_item hidden\" onclick=\"onWinClick()\"><span class=\"win_label\">App</span></div>\n"
    "      <div id=\"win_8\"  class=\"win_item hidden\" onclick=\"onWinClick()\"><span class=\"win_label\">App</span></div>\n"
    "      <div id=\"win_9\"  class=\"win_item hidden\" onclick=\"onWinClick()\"><span class=\"win_label\">App</span></div>\n"
    "      <div id=\"win_10\" class=\"win_item hidden\" onclick=\"onWinClick()\"><span class=\"win_label\">App</span></div>\n"
    "      <div id=\"win_11\" class=\"win_item hidden\" onclick=\"onWinClick()\"><span class=\"win_label\">App</span></div>\n"
    "    </div>\n"
    "  </div>\n"
    "  <div id=\"mb_right\">\n"
    "    <div id=\"tray_area\">\n"
    "      <div id=\"tray_0\" class=\"tray_item hidden\" onclick=\"onTrayClick()\"><span class=\"tray_glyph\">●</span></div>\n"
    "      <div id=\"tray_1\" class=\"tray_item hidden\" onclick=\"onTrayClick()\"><span class=\"tray_glyph\">●</span></div>\n"
    "      <div id=\"tray_2\" class=\"tray_item hidden\" onclick=\"onTrayClick()\"><span class=\"tray_glyph\">●</span></div>\n"
    "      <div id=\"tray_3\" class=\"tray_item hidden\" onclick=\"onTrayClick()\"><span class=\"tray_glyph\">●</span></div>\n"
    "      <div id=\"tray_4\" class=\"tray_item hidden\" onclick=\"onTrayClick()\"><span class=\"tray_glyph\">●</span></div>\n"
    "      <div id=\"tray_5\" class=\"tray_item hidden\" onclick=\"onTrayClick()\"><span class=\"tray_glyph\">●</span></div>\n"
    "      <div id=\"tray_6\" class=\"tray_item hidden\" onclick=\"onTrayClick()\"><span class=\"tray_glyph\">●</span></div>\n"
    "      <div id=\"tray_7\" class=\"tray_item hidden\" onclick=\"onTrayClick()\"><span class=\"tray_glyph\">●</span></div>\n"
    "    </div>\n"
    "    <div id=\"mb_bat\"  class=\"mb_item mb_status\">100%</div>\n"
    "    <div id=\"mb_wifi\" class=\"mb_item mb_status\" onclick=\"onControlCenter()\">Wi-Fi</div>\n"
    "    <div id=\"mb_cc\"   class=\"mb_item\" onclick=\"onControlCenter()\">≡</div>\n"
    "    <div id=\"mb_clock\" class=\"mb_item\">--- -- --:--</div>\n"
    "  </div>\n"
    "</div>\n"
    "\n"
    "<!-- ── Luna menu (dropdown) ── -->\n"
    "<div id=\"luna_menu\" class=\"menu_panel hidden\">\n"
    "  <div class=\"menu_section_label\">Luna Desktop</div>\n"
    "  <div id=\"mi_about\" class=\"menu_item\" onclick=\"onAbout()\">\n"
    "    <div class=\"mi_sym\" onclick=\"onAbout()\">◐</div>\n"
    "    <div class=\"mi_label\" onclick=\"onAbout()\">About This Luna</div>\n"
    "  </div>\n"
    "  <div class=\"menu_sep\"></div>\n"
    "  <div id=\"mi_settings\" class=\"menu_item\" onclick=\"onSettingsOpen()\">\n"
    "    <div class=\"mi_sym\" onclick=\"onSettingsOpen()\">◎</div>\n"
    "    <div class=\"mi_label\" onclick=\"onSettingsOpen()\">Luna Settings…</div>\n"
    "    <div class=\"mi_key\" onclick=\"onSettingsOpen()\">⌘ ,</div>\n"
    "  </div>\n"
    "  <div id=\"mi_launchpad\" class=\"menu_item\" onclick=\"onLaunchpadOpen()\">\n"
    "    <div class=\"mi_sym\" onclick=\"onLaunchpadOpen()\">★</div>\n"
    "    <div class=\"mi_label\" onclick=\"onLaunchpadOpen()\">Launchpad</div>\n"
    "    <div class=\"mi_key\" onclick=\"onLaunchpadOpen()\">F4</div>\n"
    "  </div>\n"
    "  <div class=\"menu_sep\"></div>\n"
    "  <div id=\"mi_restart\" class=\"menu_item\" onclick=\"onRestart()\">\n"
    "    <div class=\"mi_sym\" onclick=\"onRestart()\">↺</div>\n"
    "    <div class=\"mi_label\" onclick=\"onRestart()\">Restart…</div>\n"
    "  </div>\n"
    "  <div id=\"mi_shutdown\" class=\"menu_item\" onclick=\"onShutdown()\">\n"
    "    <div class=\"mi_sym\" onclick=\"onShutdown()\">◯</div>\n"
    "    <div class=\"mi_label\" onclick=\"onShutdown()\">Shut Down…</div>\n"
    "  </div>\n"
    "  <div class=\"menu_sep\"></div>\n"
    "  <div id=\"mi_logout\" class=\"menu_item mi_destructive\" onclick=\"onLogout()\">\n"
    "    <div class=\"mi_sym\" onclick=\"onLogout()\">→</div>\n"
    "    <div class=\"mi_label\" onclick=\"onLogout()\">Log Out…</div>\n"
    "  </div>\n"
    "</div>\n"
    "\n"
    "<!-- ── Control Center (popover) ── -->\n"
    "<div id=\"control_center\" class=\"menu_panel hidden\">\n"
    "  <div class=\"cc_row\">\n"
    "    <div class=\"cc_cell\">\n"
    "      <div id=\"cc_wifi\" class=\"cc_toggle on\" onclick=\"onCcToggle()\"><div id=\"cc_wifi_knob\" class=\"cc_knob\"></div></div>\n"
    "      <p class=\"cc_label\">Wi-Fi</p>\n"
    "    </div>\n"
    "    <div class=\"cc_cell\">\n"
    "      <div id=\"cc_bt\" class=\"cc_toggle on\" onclick=\"onCcToggle()\"><div id=\"cc_bt_knob\" class=\"cc_knob\"></div></div>\n"
    "      <p class=\"cc_label\">Bluetooth</p>\n"
    "    </div>\n"
    "    <div class=\"cc_cell\">\n"
    "      <div id=\"cc_night\" class=\"cc_toggle\" onclick=\"onCcToggle()\"><div id=\"cc_night_knob\" class=\"cc_knob\"></div></div>\n"
    "      <p class=\"cc_label\">Night Light</p>\n"
    "    </div>\n"
    "  </div>\n"
    "  <p class=\"cc_section\">Display</p>\n"
    "  <div id=\"bright_track\" class=\"cc_track\">\n"
    "    <div id=\"bright_fill\" class=\"cc_fill\"></div>\n"
    "    <div id=\"bright_thumb\" class=\"cc_thumb\" draggable=\"2\"></div>\n"
    "  </div>\n"
    "  <p class=\"cc_section\">Sound</p>\n"
    "  <div id=\"vol_track\" class=\"cc_track\">\n"
    "    <div id=\"vol_fill\" class=\"cc_fill\"></div>\n"
    "    <div id=\"vol_thumb\" class=\"cc_thumb\" draggable=\"2\"></div>\n"
    "  </div>\n"
    "  <p class=\"cc_section\">System</p>\n"
    "  <div class=\"cc_stat_row\"><p class=\"cc_stat_label\">CPU</p><div class=\"cc_bar\"><div id=\"cc_cpu_fill\" class=\"cc_bar_fill\"></div></div></div>\n"
    "  <div class=\"cc_stat_row\"><p class=\"cc_stat_label\">RAM</p><div class=\"cc_bar\"><div id=\"cc_mem_fill\" class=\"cc_bar_fill\"></div></div></div>\n"
    "</div>\n"
    "\n"
    "<!-- ── Desktop widgets ── -->\n"
    "<div id=\"widget_clock\" class=\"widget\">\n"
    "  <p id=\"wg_time\">--:--</p>\n"
    "  <p id=\"wg_date\">Luna Desktop</p>\n"
    "</div>\n"
    "<div id=\"widget_stats\" class=\"widget\">\n"
    "  <div class=\"st_row\"><p class=\"st_label\">CPU</p><p id=\"st_cpu_val\" class=\"st_val\">0%</p></div>\n"
    "  <div class=\"st_bar\"><div id=\"st_cpu_fill\" class=\"st_fill\"></div></div>\n"
    "  <div class=\"st_row\"><p class=\"st_label\">Memory</p><p id=\"st_mem_val\" class=\"st_val\">0%</p></div>\n"
    "  <div class=\"st_bar\"><div id=\"st_mem_fill\" class=\"st_fill g_mem\"></div></div>\n"
    "  <div class=\"st_row\"><p class=\"st_label\">Disk</p><p id=\"st_disk_val\" class=\"st_val\">--</p></div>\n"
    "  <div class=\"st_bar\"><div id=\"st_disk_fill\" class=\"st_fill g_disk\"></div></div>\n"
    "</div>\n"
    "\n"
    "<!-- ── About This Luna ── -->\n"
    "<div id=\"about_win\" class=\"hidden\">\n"
    "  <div id=\"about_drag\" draggable=\"1\"></div>\n"
    "  <div id=\"tl_close\" class=\"tl tl_red\"    onclick=\"onAboutClose()\"></div>\n"
    "  <div id=\"tl_min\"   class=\"tl tl_yellow\"></div>\n"
    "  <div id=\"tl_max\"   class=\"tl tl_green\"></div>\n"
    "  <div id=\"about_moon\"></div>\n"
    "  <p id=\"about_title\">Luna Desktop</p>\n"
    "  <p id=\"about_ver\">Version 1.1 — Mare Tranquillitatis</p>\n"
    "  <div id=\"about_sep\"></div>\n"
    "  <p id=\"about_shell\"  class=\"about_line\">Shell    luna-shell (Luna UI engine)</p>\n"
    "  <p id=\"about_comp\"   class=\"about_line\">Display  luna-compositor (Rust Wayland)</p>\n"
    "  <p id=\"about_kernel\" class=\"about_line\">Kernel   —</p>\n"
    "  <p id=\"about_mem\"    class=\"about_line\">Memory   —</p>\n"
    "</div>\n"
    "\n"
    "<!-- ── Settings window ── -->\n"
    "<div id=\"settings_win\" class=\"modal_sheet hidden\">\n"
    "  <div id=\"settings_backdrop\" class=\"modal_backdrop\" onclick=\"onSettingsClose()\"></div>\n"
    "  <div id=\"settings_sheet\" class=\"sheet_box\">\n"
    "    <div id=\"settings_drag\" draggable=\"1\"></div>\n"
    "    <div id=\"stl_close\"  class=\"tl tl_red\"    onclick=\"onSettingsClose()\"></div>\n"
    "    <div id=\"stl_min\"    class=\"tl tl_yellow\"></div>\n"
    "    <div id=\"stl_max\"    class=\"tl tl_green\"></div>\n"
    "    <p id=\"settings_title\">Luna Settings</p>\n"
    "\n"
    "    <div id=\"settings_body\">\n"
    "      <div id=\"settings_sidebar\">\n"
    "        <div id=\"stab_apps\" class=\"stab active\" onclick=\"onSettingsTab()\"><span class=\"stab_icon\">◫</span> Apps</div>\n"
    "        <div id=\"stab_disp\" class=\"stab\"        onclick=\"onSettingsTab()\"><span class=\"stab_icon\">◑</span> Display</div>\n"
    "      </div>\n"
    "      <div id=\"settings_content\">\n"
    "        <div id=\"settings_panel_apps\">\n"
    "          <p class=\"panel_heading\">Launch Commands</p>\n"
    "          <div class=\"pref_row\"><p class=\"pref_label\">Files</p><input    id=\"pref_files\"    class=\"pref_input\" type=\"text\"></div>\n"
    "          <div class=\"pref_row\"><p class=\"pref_label\">Terminal</p><input id=\"pref_terminal\" class=\"pref_input\" type=\"text\"></div>\n"
    "          <div class=\"pref_row\"><p class=\"pref_label\">Browser</p><input  id=\"pref_browser\"  class=\"pref_input\" type=\"text\"></div>\n"
    "          <div class=\"pref_row\"><p class=\"pref_label\">Editor</p><input   id=\"pref_editor\"   class=\"pref_input\" type=\"text\"></div>\n"
    "          <div class=\"pref_row\"><p class=\"pref_label\">Music</p><input    id=\"pref_music\"    class=\"pref_input\" type=\"text\"></div>\n"
    "          <div class=\"pref_row\"><p class=\"pref_label\">Settings</p><input id=\"pref_settings\" class=\"pref_input\" type=\"text\"></div>\n"
    "          <div class=\"pref_row\"><p class=\"pref_label\">GTK Demo</p><input id=\"pref_demo\"     class=\"pref_input\" type=\"text\"></div>\n"
    "          <div class=\"pref_row\"><p class=\"pref_label\">Hello GTK</p><input id=\"pref_hello\"   class=\"pref_input\" type=\"text\"></div>\n"
    "        </div>\n"
    "        <div id=\"settings_panel_disp\" class=\"hidden\">\n"
    "          <p class=\"panel_heading\">Appearance</p>\n"
    "          <p class=\"pref_section\">Wallpaper Theme</p>\n"
    "          <div id=\"wp_thumbs_row\">\n"
    "            <div id=\"wp_night\"  class=\"wp_thumb wp_t_night  selected\" onclick=\"onWpSelect()\"></div>\n"
    "            <div id=\"wp_ocean\"  class=\"wp_thumb wp_t_ocean\"           onclick=\"onWpSelect()\"></div>\n"
    "            <div id=\"wp_forest\" class=\"wp_thumb wp_t_forest\"          onclick=\"onWpSelect()\"></div>\n"
    "            <div id=\"wp_sunset\" class=\"wp_thumb wp_t_sunset\"          onclick=\"onWpSelect()\"></div>\n"
    "          </div>\n"
    "          <div class=\"wp_label_row\">\n"
    "            <p class=\"wp_lbl\">Night</p>\n"
    "            <p class=\"wp_lbl\">Ocean</p>\n"
    "            <p class=\"wp_lbl\">Forest</p>\n"
    "            <p class=\"wp_lbl\">Sunset</p>\n"
    "          </div>\n"
    "          <p class=\"pref_section\">Hostname</p>\n"
    "          <div class=\"pref_row_full\"><input id=\"pref_hostname\" class=\"pref_input_full\" type=\"text\"></div>\n"
    "        </div>\n"
    "      </div>\n"
    "    </div>\n"
    "\n"
    "    <div id=\"settings_btns\">\n"
    "      <div class=\"dlg_btn\"         onclick=\"onSettingsClose()\">Cancel</div>\n"
    "      <div class=\"dlg_btn primary\" onclick=\"onSettingsSave()\">Save Changes</div>\n"
    "    </div>\n"
    "  </div>\n"
    "</div>\n"
    "\n"
    "<!-- ── Launchpad ── -->\n"
    "<div id=\"launchpad\" class=\"hidden\" onclick=\"onLaunchpadClose()\">\n"
    "  <input id=\"lp_search\" placeholder=\"Search\">\n"
    "  <div id=\"lp_grid\" onclick=\"onLaunchpadClose()\">\n"
    "    <div id=\"lp_files\"    class=\"lp_app\" onclick=\"onLaunchApp()\"><div class=\"lp_icon g_files\">■</div><p class=\"lp_label\">Files</p></div>\n"
    "    <div id=\"lp_terminal\" class=\"lp_app\" onclick=\"onLaunchApp()\"><div class=\"lp_icon g_terminal\">&gt;_</div><p class=\"lp_label\">Terminal</p></div>\n"
    "    <div id=\"lp_browser\"  class=\"lp_app\" onclick=\"onLaunchApp()\"><div class=\"lp_icon g_browser\">⊕</div><p class=\"lp_label\">Browser</p></div>\n"
    "    <div id=\"lp_editor\"   class=\"lp_app\" onclick=\"onLaunchApp()\"><div class=\"lp_icon g_editor\">¶</div><p class=\"lp_label\">Editor</p></div>\n"
    "    <div id=\"lp_music\"    class=\"lp_app\" onclick=\"onLaunchApp()\"><div class=\"lp_icon g_music\">♫</div><p class=\"lp_label\">Music</p></div>\n"
    "    <div id=\"lp_settings\" class=\"lp_app\" onclick=\"onLaunchApp()\"><div class=\"lp_icon g_settings\">◎</div><p class=\"lp_label\">Settings</p></div>\n"
    "    <div id=\"lp_demo\"     class=\"lp_app\" onclick=\"onLaunchApp()\"><div class=\"lp_icon g_demo\">GTK</div><p class=\"lp_label\">GTK Demo</p></div>\n"
    "    <div id=\"lp_hello\"    class=\"lp_app\" onclick=\"onLaunchApp()\"><div class=\"lp_icon g_hello\">Hi</div><p class=\"lp_label\">Hello GTK</p></div>\n"
    "  </div>\n"
    "  <p id=\"lp_hint\">Esc or click background to close</p>\n"
    "</div>\n"
    "\n"
    "<!-- ── Notification toast ── -->\n"
    "<div id=\"toast\">\n"
    "  <div id=\"toast_icon\"><div id=\"toast_moon_disc\"></div><div id=\"toast_moon_bite\"></div></div>\n"
    "  <div id=\"toast_body\">\n"
    "    <p id=\"toast_title\">Welcome to Luna</p>\n"
    "    <p id=\"toast_msg\">Your desktop is ready.</p>\n"
    "  </div>\n"
    "  <div id=\"toast_close\" onclick=\"onToastClose()\">×</div>\n"
    "</div>\n"
    "\n"
    "<!-- ── Shutdown / restart confirmation ── -->\n"
    "<div id=\"confirm_overlay\" class=\"modal_sheet hidden\">\n"
    "  <div id=\"confirm_backdrop\" class=\"modal_backdrop\" onclick=\"onConfirmCancel()\"></div>\n"
    "  <div id=\"confirm_box\" class=\"alert_box\">\n"
    "    <div id=\"confirm_icon\">\n"
    "      <div id=\"confirm_moon_disc\"></div>\n"
    "      <div id=\"confirm_moon_bite\"></div>\n"
    "    </div>\n"
    "    <p id=\"confirm_title\">Shut Down</p>\n"
    "    <p id=\"confirm_msg\">Are you sure you want to shut down your computer now?</p>\n"
    "    <div id=\"confirm_btns\">\n"
    "      <div id=\"confirm_cancel\" class=\"dlg_btn\"         onclick=\"onConfirmCancel()\">Cancel</div>\n"
    "      <div id=\"confirm_ok\"     class=\"dlg_btn danger\"  onclick=\"onConfirmOk()\">Shut Down</div>\n"
    "    </div>\n"
    "  </div>\n"
    "</div>\n"
    "\n"
    "<!-- ── Dock ── -->\n"
    "<div id=\"dock\">\n"
    "  <div id=\"dock_files\"     class=\"dock_item\" onclick=\"onDockClick()\"><div class=\"dock_icon g_files\">■</div><div id=\"dot_files\" class=\"dock_dot\"></div></div>\n"
    "  <div id=\"dock_launchpad\" class=\"dock_item\" onclick=\"onLaunchpadOpen()\"><div class=\"dock_icon g_launchpad\">★</div><div class=\"dock_dot spacer\"></div></div>\n"
    "  <div id=\"dock_terminal\"  class=\"dock_item\" onclick=\"onDockClick()\"><div class=\"dock_icon g_terminal\">&gt;_</div><div id=\"dot_terminal\" class=\"dock_dot\"></div></div>\n"
    "  <div id=\"dock_browser\"   class=\"dock_item\" onclick=\"onDockClick()\"><div class=\"dock_icon g_browser\">⊕</div><div id=\"dot_browser\" class=\"dock_dot\"></div></div>\n"
    "  <div id=\"dock_editor\"    class=\"dock_item\" onclick=\"onDockClick()\"><div class=\"dock_icon g_editor\">¶</div><div id=\"dot_editor\" class=\"dock_dot\"></div></div>\n"
    "  <div id=\"dock_music\"     class=\"dock_item\" onclick=\"onDockClick()\"><div class=\"dock_icon g_music\">♫</div><div id=\"dot_music\" class=\"dock_dot\"></div></div>\n"
    "  <div id=\"dock_settings\"  class=\"dock_item\" onclick=\"onDockClick()\"><div class=\"dock_icon g_settings\">◎</div><div id=\"dot_settings\" class=\"dock_dot\"></div></div>\n"
    "  <div id=\"dock_sep\" class=\"dock_sep\"></div>\n"
    "  <div id=\"dock_trash\"     class=\"dock_item\" onclick=\"onTrash()\"><div class=\"dock_icon g_trash\">×</div><div class=\"dock_dot spacer\"></div></div>\n"
    "</div>\n"
    "\n"
    "</body>\n"
    "</html>\n"
