    "<!DOCTYPE html>\n"
    "<html lang=\"en\">\n"
    "<head>\n"
    "  <meta charset=\"utf-8\">\n"
    "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
    "  <title>Vespera GUI Engine v3.12</title>\n"
    "  <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n"
    "  <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n"
    "  <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&family=Space+Grotesk:wght@500;700&display=swap\" rel=\"stylesheet\">\n"
    "  <link rel=\"stylesheet\" type=\"text/css\" href=\"luna-ui.css\">\n"
    "</head>\n"
    "<body>\n"
    "\n"
    "  <!-- ══ Main window ══ -->\n"
    "  <div id=\"main_win\" class=\"window focused\">\n"
    "\n"
    "    <!-- Title bar -->\n"
    "    <div id=\"title_bar\">\n"
    "      <div class=\"title_drag\"></div>\n"
    "      <div id=\"btn_close\" class=\"btn_os\" onclick=\"onClose()\"></div>\n"
    "      <div id=\"btn_min\"   class=\"btn_os\" onclick=\"onMinimize()\"></div>\n"
    "      <div id=\"btn_max\"   class=\"btn_os\" onclick=\"onMaximize()\"></div>\n"
    "      <p id=\"title_text\">System Preferences</p>\n"
    "    </div>\n"
    "\n"
    "    <!-- ── Sidebar ── -->\n"
    "    <div id=\"sidebar\">\n"
    "      <div id=\"sidebar_avatar\"></div>\n"
    "      <p id=\"sidebar_username\">Vespera User</p>\n"
    "      <p id=\"sidebar_role\">Administrator</p>\n"
    "\n"
    "      <nav id=\"sidebar_nav\">\n"
    "        <div class=\"nav_item active\" data-tab=\"general\" onclick=\"onTabSwitch()\">\n"
    "          General <span class=\"nav_dot green\"></span>\n"
    "        </div>\n"
    "        <div class=\"nav_item\" data-tab=\"appearance\" onclick=\"onTabSwitch()\">\n"
    "          Appearance <span class=\"nav_dot amber\"></span>\n"
    "        </div>\n"
    "        <div class=\"nav_item\" data-tab=\"layout\" onclick=\"onTabSwitch()\">Layout</div>\n"
    "        <div class=\"nav_item\" data-tab=\"network\" onclick=\"onTabSwitch()\">Network</div>\n"
    "        <div class=\"nav_item\" data-tab=\"security\" onclick=\"onTabSwitch()\">Security</div>\n"
    "      </nav>\n"
    "\n"
    "      <div id=\"sidebar_stats\">\n"
    "        <div class=\"stat_row\">\n"
    "          <span class=\"stat_key\">CPU</span>\n"
    "          <div class=\"stat_bar_wrap\"><div class=\"stat_bar_fill\" style=\"width:42%\"></div></div>\n"
    "          <span class=\"stat_num\">42%</span>\n"
    "        </div>\n"
    "        <div class=\"stat_row\">\n"
    "          <span class=\"stat_key\">MEM</span>\n"
    "          <div class=\"stat_bar_wrap\"><div class=\"stat_bar_fill mem\" style=\"width:60%\"></div></div>\n"
    "          <span class=\"stat_num\">2.4G</span>\n"
    "        </div>\n"
    "        <div class=\"stat_row\">\n"
    "          <span class=\"stat_key\">NET</span>\n"
    "          <div class=\"stat_bar_wrap\"><div class=\"stat_bar_fill net\" style=\"width:28%\"></div></div>\n"
    "          <span class=\"stat_num\">72K</span>\n"
    "        </div>\n"
    "      </div>\n"
    "\n"
    "      <p id=\"sidebar_version\">v3.12.0 — Vespera</p>\n"
    "    </div>\n"
    "\n"
    "    <!-- ── Content area ── -->\n"
    "    <div id=\"content\">\n"
    "\n"
    "      <!-- ═══ TAB: General ═══ -->\n"
    "      <div class=\"tab_panel active\" id=\"tab_general\">\n"
    "        <p class=\"section_title\">General</p>\n"
    "        <p class=\"section_desc\">Configure display, notifications, and system behaviour.</p>\n"
    "        <div class=\"sep\"></div>\n"
    "\n"
    "        <div id=\"toolbar\">\n"
    "          <div class=\"tool_btn active\" role=\"button\">Save</div>\n"
    "          <div class=\"tool_btn\" role=\"button\">Reset</div>\n"
    "          <div class=\"tool_btn\" role=\"button\">Export</div>\n"
    "          <div id=\"apply_btn\" role=\"button\" onclick=\"onApply()\">Apply Changes</div>\n"
    "        </div>\n"
    "\n"
    "        <div class=\"setting_row\">\n"
    "          <span class=\"setting_label\">Dark Mode</span>\n"
    "          <div class=\"toggle on\" onclick=\"onToggleClick()\"><div class=\"toggle_knob\"></div></div>\n"
    "        </div>\n"
    "        <div class=\"setting_row\">\n"
    "          <span class=\"setting_label\">Enable Notifications</span>\n"
    "          <div class=\"checkbox checked\" onclick=\"onCheckboxClick()\"></div>\n"
    "        </div>\n"
    "        <div class=\"setting_row\">\n"
    "          <span class=\"setting_label\">Theme</span>\n"
    "          <div id=\"theme_combo\">\n"
    "            <div id=\"theme_select_box\" role=\"combobox\">Indigo ▾</div>\n"
    "            <div id=\"select_panel\" class=\"hidden\">\n"
    "              <div class=\"select_option\">Indigo</div>\n"
    "              <div class=\"select_option\">Graphite</div>\n"
    "              <div class=\"select_option\">Emerald</div>\n"
    "            </div>\n"
    "          </div>\n"
    "        </div>\n"
    "        <div class=\"setting_row col\">\n"
    "          <span class=\"setting_label\">Brightness <span class=\"setting_val\">70%</span></span>\n"
    "          <div id=\"slider_track\">\n"
    "            <div id=\"slider_fill\"></div>\n"
    "            <div id=\"slider_thumb\"></div>\n"
    "          </div>\n"
    "        </div>\n"
    "\n"
    "        <div class=\"sep\"></div>\n"
    "\n"
    "        <!-- Chip wrap demo -->\n"
    "        <div class=\"demo_label\">flex-wrap · align-items · gap</div>\n"
    "        <div id=\"chip_row\">\n"
    "          <div class=\"chip accent\">CSS</div>\n"
    "          <div class=\"chip\">Flex</div>\n"
    "          <div class=\"chip\">Grid</div>\n"
    "          <div class=\"chip\">HSL</div>\n"
    "          <div class=\"chip\">Wrap</div>\n"
    "          <div class=\"chip\">Self</div>\n"
    "          <div class=\"chip\">Focus</div>\n"
    "          <div class=\"chip\">Clip</div>\n"
    "        </div>\n"
    "\n"
    "        <!-- Hscroll + sticky pin -->\n"
    "        <div class=\"demo_label\">overflow-x: auto · position: sticky</div>\n"
    "        <div id=\"hscroll_panel\">\n"
    "          <div id=\"hscroll_inner\">\n"
    "            <div class=\"hscroll_chip pinned\">Pin</div>\n"
    "            <div class=\"hscroll_chip\">Alpha</div>\n"
    "            <div class=\"hscroll_chip\">Beta</div>\n"
    "            <div class=\"hscroll_chip\">Gamma</div>\n"
    "            <div class=\"hscroll_chip\">Delta</div>\n"
    "            <div class=\"hscroll_chip\">Epsilon</div>\n"
    "            <div class=\"hscroll_chip\">Zeta</div>\n"
    "          </div>\n"
    "        </div>\n"
    "\n"
    "        <!-- Progress -->\n"
    "        <div class=\"demo_label\">animation · linear-gradient</div>\n"
    "        <div id=\"progress_track\"><div id=\"progress_fill\"></div></div>\n"
    "\n"
    "        <!-- Activity: sticky header/footer scroll -->\n"
    "        <div class=\"demo_label\">overflow-y: auto · sticky top/bottom</div>\n"
    "        <div id=\"activity_panel\">\n"
    "          <div class=\"activity_sticky\">Recent Activity</div>\n"
    "          <div class=\"activity_line\">Sync complete — 2 min ago</div>\n"
    "          <div class=\"activity_line\">Theme applied — Indigo</div>\n"
    "          <div class=\"activity_line\">Network profile updated</div>\n"
    "          <div class=\"activity_line\">Backup finished — 128 files</div>\n"
    "          <div class=\"activity_line\">Driver update available</div>\n"
    "          <div class=\"activity_line\">VPN connected — qberry</div>\n"
    "          <div class=\"activity_sticky_bottom\">End of feed</div>\n"
    "        </div>\n"
    "\n"
    "        <!-- Metrics + badges -->\n"
    "        <div id=\"metrics_row\">\n"
    "          <div class=\"metric_pill online\">\n"
    "            <p class=\"mp_val\">Online</p><p class=\"mp_label\">STATUS</p>\n"
    "          </div>\n"
    "          <div class=\"metric_pill peers\">\n"
    "            <p class=\"mp_val\">7</p><p class=\"mp_label\">PEERS</p>\n"
    "          </div>\n"
    "          <div class=\"metric_pill latency\">\n"
    "            <p class=\"mp_val\">12ms</p><p class=\"mp_label\">PING</p>\n"
    "          </div>\n"
    "          <div class=\"metric_pill badges\">\n"
    "            <span class=\"badge green\">Active</span>\n"
    "            <span class=\"badge amber\">Update</span>\n"
    "            <span class=\"badge red\">Error</span>\n"
    "          </div>\n"
    "        </div>\n"
    "\n"
    "        <p id=\"status_text\">v3.12.0 — Vespera GUI Engine</p>\n"
    "      </div><!-- /tab_general -->\n"
    "\n"
    "      <!-- ═══ TAB: Appearance ═══ -->\n"
    "      <div class=\"tab_panel\" id=\"tab_appearance\">\n"
    "        <p class=\"section_title\">Appearance</p>\n"
    "        <p class=\"section_desc\">Colours, typography, and visual style.</p>\n"
    "        <div class=\"sep\"></div>\n"
    "\n"
    "        <div class=\"setting_row\">\n"
    "          <span class=\"setting_label\">Accent colour</span>\n"
    "          <div style=\"display:flex;gap:6px;align-items:center\">\n"
    "            <div class=\"swatch sel\" style=\"background:#6366f1;box-shadow:0 0 9px rgba(99,102,241,.6)\" onclick=\"onSwatchClick()\"></div>\n"
    "            <div class=\"swatch\" style=\"background:#ec4899\" onclick=\"onSwatchClick()\"></div>\n"
    "            <div class=\"swatch\" style=\"background:#34d399\" onclick=\"onSwatchClick()\"></div>\n"
    "            <div class=\"swatch\" style=\"background:#f59e0b\" onclick=\"onSwatchClick()\"></div>\n"
    "            <div class=\"swatch\" style=\"background:#ef4444\" onclick=\"onSwatchClick()\"></div>\n"
    "          </div>\n"
    "        </div>\n"
    "        <div class=\"setting_row\">\n"
    "          <span class=\"setting_label\">Font size</span>\n"
    "          <div id=\"slider_track\" class=\"slider_track2\">\n"
    "            <div class=\"slider_fill2\" style=\"width:55%\"></div>\n"
    "            <div class=\"slider_thumb2\" style=\"left:55%\"></div>\n"
    "          </div>\n"
    "        </div>\n"
    "        <div class=\"setting_row\">\n"
    "          <span class=\"setting_label\">Transparency</span>\n"
    "          <div class=\"toggle on\" onclick=\"onToggleClick()\"><div class=\"toggle_knob\"></div></div>\n"
    "        </div>\n"
    "        <div class=\"setting_row\">\n"
    "          <span class=\"setting_label\">Reduce motion</span>\n"
    "          <div class=\"toggle\" onclick=\"onToggleClick()\"><div class=\"toggle_knob\"></div></div>\n"
    "        </div>\n"
    "        <div class=\"setting_row\">\n"
    "          <span class=\"setting_label\">Show tooltips</span>\n"
    "          <div class=\"checkbox checked\" onclick=\"onCheckboxClick()\"></div>\n"
    "        </div>\n"
    "\n"
    "        <div class=\"sep\"></div>\n"
    "        <div class=\"demo_label\">Tab bar · active pill</div>\n"
    "        <div class=\"tab_pill_bar\">\n"
    "          <div class=\"tab_pill active\" onclick=\"onTabPillClick()\">All</div>\n"
    "          <div class=\"tab_pill\" onclick=\"onTabPillClick()\">VPN</div>\n"
    "          <div class=\"tab_pill\" onclick=\"onTabPillClick()\">Logs</div>\n"
    "          <div class=\"tab_pill\" onclick=\"onTabPillClick()\">Stats</div>\n"
    "        </div>\n"
    "\n"
    "        <div class=\"demo_label\" style=\"margin-top:14px\">Keyboard shortcuts</div>\n"
    "        <div class=\"kbd_card\">\n"
    "          <div class=\"kbd_row\"><span class=\"kbd_label\">Connect</span><span class=\"kbd_key\">⌘ C</span></div>\n"
    "          <div class=\"kbd_row\"><span class=\"kbd_label\">Settings</span><span class=\"kbd_key\">⌘ ,</span></div>\n"
    "          <div class=\"kbd_row\"><span class=\"kbd_label\">Quit</span><span class=\"kbd_key\">⌘ Q</span></div>\n"
    "          <div class=\"kbd_row\"><span class=\"kbd_label\">Search</span><span class=\"kbd_key\">⌘ K</span></div>\n"
    "        </div>\n"
    "\n"
    "        <p id=\"status_text\" style=\"margin-top:auto\">v3.12.0 — Vespera GUI Engine</p>\n"
    "      </div><!-- /tab_appearance -->\n"
    "\n"
    "      <!-- ═══ TAB: Layout Demo ═══ -->\n"
    "      <div class=\"tab_panel\" id=\"tab_layout\">\n"
    "        <p class=\"section_title\">Layout Demos</p>\n"
    "        <p class=\"section_desc\">CSS layout techniques rendered as live widgets.</p>\n"
    "        <div class=\"sep\"></div>\n"
    "\n"
    "        <!-- Row 1: Flexbox shrink + flex-grow -->\n"
    "        <div class=\"demo_card\">\n"
    "          <div class=\"demo_card_head\">\n"
    "            <span class=\"demo_tag\">Flexbox</span>\n"
    "            <span class=\"demo_caption\">flex-shrink · flex-grow · min-width:0</span>\n"
    "          </div>\n"
    "          <div class=\"demo_flex_shrink\">\n"
    "            <div class=\"fs_item grow\">grow</div>\n"
    "            <div class=\"fs_item\">BB</div>\n"
    "            <div class=\"fs_item\">CCC</div>\n"
    "            <div class=\"fs_item\">DD</div>\n"
    "            <div class=\"fs_item shrink\">shrink me</div>\n"
    "          </div>\n"
    "        </div>\n"
    "\n"
    "        <!-- Row 2: Grid row-dense -->\n"
    "        <div class=\"demo_card\">\n"
    "          <div class=\"demo_card_head\">\n"
    "            <span class=\"demo_tag indigo\">Grid</span>\n"
    "            <span class=\"demo_caption\">grid-auto-flow: row dense · span</span>\n"
    "          </div>\n"
    "          <div class=\"demo_grid_dense\">\n"
    "            <div class=\"gc wide\">Wide</div>\n"
    "            <div class=\"gc\">1</div>\n"
    "            <div class=\"gc\">2</div>\n"
    "            <div class=\"gc\">3</div>\n"
    "            <div class=\"gc\">4</div>\n"
    "            <div class=\"gc\">5</div>\n"
    "          </div>\n"
    "        </div>\n"
    "\n"
    "        <!-- Row 3: Grid column-dense -->\n"
    "        <div class=\"demo_card\">\n"
    "          <div class=\"demo_card_head\">\n"
    "            <span class=\"demo_tag violet\">Grid</span>\n"
    "            <span class=\"demo_caption\">grid-auto-flow: column dense · row span</span>\n"
    "          </div>\n"
    "          <div class=\"demo_grid_col_dense\">\n"
    "            <div class=\"gcc tall\">Tall</div>\n"
    "            <div class=\"gcc b\">B</div>\n"
    "            <div class=\"gcc\">1</div>\n"
    "            <div class=\"gcc\">2</div>\n"
    "            <div class=\"gcc\">3</div>\n"
    "            <div class=\"gcc\">4</div>\n"
    "          </div>\n"
    "        </div>\n"
    "\n"
    "        <!-- Row 4: align-self -->\n"
    "        <div class=\"demo_card\">\n"
    "          <div class=\"demo_card_head\">\n"
    "            <span class=\"demo_tag cyan\">Flex</span>\n"
    "            <span class=\"demo_caption\">align-self per item</span>\n"
    "          </div>\n"
    "          <div class=\"demo_align_self\">\n"
    "            <div class=\"as_item start\">start</div>\n"
    "            <div class=\"as_item center\">center</div>\n"
    "            <div class=\"as_item end\">end</div>\n"
    "            <div class=\"as_item stretch\">stretch</div>\n"
    "            <div class=\"as_item baseline\">base</div>\n"
    "          </div>\n"
    "        </div>\n"
    "\n"
    "        <!-- Row 5: grid template areas -->\n"
    "        <div class=\"demo_card\">\n"
    "          <div class=\"demo_card_head\">\n"
    "            <span class=\"demo_tag emerald\">Grid</span>\n"
    "            <span class=\"demo_caption\">grid-template-areas</span>\n"
    "          </div>\n"
    "          <div class=\"demo_areas\">\n"
    "            <div class=\"area header\">header</div>\n"
    "            <div class=\"area sidebar\">side</div>\n"
    "            <div class=\"area main\">main</div>\n"
    "            <div class=\"area footer\">footer</div>\n"
    "          </div>\n"
    "        </div>\n"
    "\n"
    "        <!-- Row 6: min-content / max-content / fr -->\n"
    "        <div class=\"demo_card\">\n"
    "          <div class=\"demo_card_head\">\n"
    "            <span class=\"demo_tag amber\">Grid</span>\n"
    "            <span class=\"demo_caption\">min-content · max-content · 1fr</span>\n"
    "          </div>\n"
    "          <div class=\"demo_sizing\">\n"
    "            <div class=\"sz_cell min\">min</div>\n"
    "            <div class=\"sz_cell max\">max-content here</div>\n"
    "            <div class=\"sz_cell fr\">1fr</div>\n"
    "          </div>\n"
    "        </div>\n"
    "\n"
    "        <!-- Row 7: overflow clip + text-overflow -->\n"
    "        <div class=\"demo_card\">\n"
    "          <div class=\"demo_card_head\">\n"
    "            <span class=\"demo_tag pink\">Clip</span>\n"
    "            <span class=\"demo_caption\">overflow: hidden · text-overflow: ellipsis</span>\n"
    "          </div>\n"
    "          <div class=\"demo_clip_row\">\n"
    "            <div class=\"clip_box\"><span>This long text will be clipped with an ellipsis when it overflows the box boundary.</span></div>\n"
    "            <div class=\"clip_box clamp\"><span>Multi-line text that gets clamped after two lines using -webkit-line-clamp and display box properties.</span></div>\n"
    "          </div>\n"
    "        </div>\n"
    "\n"
    "        <p id=\"status_text\">v3.12.0 — Vespera GUI Engine</p>\n"
    "      </div><!-- /tab_layout -->\n"
    "\n"
    "      <!-- ═══ TAB: Network ═══ -->\n"
    "      <div class=\"tab_panel\" id=\"tab_network\">\n"
    "        <p class=\"section_title\">Network</p>\n"
    "        <p class=\"section_desc\">VPN, DNS, and connection settings.</p>\n"
    "        <div class=\"sep\"></div>\n"
    "        <div class=\"setting_row\">\n"
    "          <span class=\"setting_label\">VPN</span>\n"
    "          <div class=\"toggle on\" onclick=\"onToggleClick()\"><div class=\"toggle_knob\"></div></div>\n"
    "        </div>\n"
    "        <div class=\"setting_row\">\n"
    "          <span class=\"setting_label\">DNS over HTTPS</span>\n"
    "          <div class=\"checkbox checked\" onclick=\"onCheckboxClick()\"></div>\n"
    "        </div>\n"
    "        <div class=\"setting_row\">\n"
    "          <span class=\"setting_label\">Proxy</span>\n"
    "          <div class=\"toggle\" onclick=\"onToggleClick()\"><div class=\"toggle_knob\"></div></div>\n"
    "        </div>\n"
    "        <div class=\"sep\"></div>\n"
    "        <div id=\"metrics_row\">\n"
    "          <div class=\"metric_pill online\"><p class=\"mp_val\">Online</p><p class=\"mp_label\">STATUS</p></div>\n"
    "          <div class=\"metric_pill peers\"><p class=\"mp_val\">7</p><p class=\"mp_label\">PEERS</p></div>\n"
    "          <div class=\"metric_pill latency\"><p class=\"mp_val\">12ms</p><p class=\"mp_label\">PING</p></div>\n"
    "        </div>\n"
    "        <p id=\"status_text\" style=\"margin-top:auto\">v3.12.0 — Vespera GUI Engine</p>\n"
    "      </div>\n"
    "\n"
    "      <!-- ═══ TAB: Security ═══ -->\n"
    "      <div class=\"tab_panel\" id=\"tab_security\">\n"
    "        <p class=\"section_title\">Security</p>\n"
    "        <p class=\"section_desc\">Firewall, encryption, and access control.</p>\n"
    "        <div class=\"sep\"></div>\n"
    "        <div class=\"setting_row\">\n"
    "          <span class=\"setting_label\">Firewall</span>\n"
    "          <div class=\"toggle on\" onclick=\"onToggleClick()\"><div class=\"toggle_knob\"></div></div>\n"
    "        </div>\n"
    "        <div class=\"setting_row\">\n"
    "          <span class=\"setting_label\">Two-factor Auth</span>\n"
    "          <div class=\"checkbox checked\" onclick=\"onCheckboxClick()\"></div>\n"
    "        </div>\n"
    "        <div class=\"setting_row\">\n"
    "          <span class=\"setting_label\">Auto-lock</span>\n"
    "          <div class=\"toggle on\" onclick=\"onToggleClick()\"><div class=\"toggle_knob\"></div></div>\n"
    "        </div>\n"
    "        <div class=\"setting_row\">\n"
    "          <span class=\"setting_label\">Disk encryption</span>\n"
    "          <div class=\"checkbox\" onclick=\"onCheckboxClick()\"></div>\n"
    "        </div>\n"
    "        <p id=\"status_text\" style=\"margin-top:auto\">v3.12.0 — Vespera GUI Engine</p>\n"
    "      </div>\n"
    "\n"
    "    </div><!-- /content -->\n"
    "  </div><!-- /main_win -->\n"
    "\n"
    "  <!-- ── Toast ── -->\n"
    "  <div id=\"toast\" class=\"window\">\n"
    "    <div id=\"toast_icon\"></div>\n"
    "    <div id=\"toast_body\">\n"
    "      <p id=\"toast_title\">Update Available</p>\n"
    "      <p id=\"toast_msg\">Version 2.3 is ready to install.</p>\n"
    "    </div>\n"
    "    <div id=\"toast_close\" onclick=\"onToastDismiss()\"></div>\n"
    "  </div>\n"
    "\n"
    "  <!-- ── Info window ── -->\n"
    "  <div id=\"info_win\" class=\"window\">\n"
    "    <div id=\"info_close\" onclick=\"onInfoClose()\"></div>\n"
    "    <div id=\"info_icon\"></div>\n"
    "    <p id=\"info_title\">Vespera GUI Engine</p>\n"
    "    <p id=\"info_msg\">OpenGL window manager with CSS styling, gradients, and smooth transitions.</p>\n"
    "  </div>\n"
    "\n"
    "  <!-- ── Dock ── -->\n"
    "  <div id=\"dock\" class=\"window\">\n"
    "    <div class=\"dock_icon\" style=\"background:linear-gradient(135deg,rgba(52,211,153,.75),rgba(5,150,105,.65))\" onclick=\"onDockInfo()\">i<span class=\"dock_label\">Info</span></div>\n"
    "    <div class=\"dock_icon\" style=\"background:linear-gradient(135deg,rgba(251,191,36,.75),rgba(245,158,11,.65))\" onclick=\"onDockTheme()\">T<span class=\"dock_label\">Theme</span></div>\n"
    "    <div class=\"dock_icon\" style=\"background:linear-gradient(135deg,rgba(96,165,250,.75),rgba(99,102,241,.65))\" onclick=\"onDockNotify()\">N<span class=\"dock_label\">Alert</span></div>\n"
    "    <div class=\"dock_icon\" style=\"background:linear-gradient(135deg,rgba(248,113,113,.75),rgba(239,68,68,.65))\" onclick=\"onDockToast()\">✕<span class=\"dock_label\">Toast</span></div>\n"
    "  </div>\n"
    "\n"
    "  <!-- ── Modal ── -->\n"
    "  <div id=\"modal_overlay\" class=\"overlay hidden\">\n"
    "    <div id=\"modal_dialog\" class=\"window\">\n"
    "      <div id=\"modal_icon\"></div>\n"
    "      <p id=\"modal_title\">Apply Changes?</p>\n"
    "      <p id=\"modal_msg\">Your preferences will be updated immediately.</p>\n"
    "      <div class=\"modal_btn cancel\" role=\"button\" onclick=\"onModalCancel()\">Cancel</div>\n"
    "      <div class=\"modal_btn confirm\" role=\"button\" onclick=\"onModalConfirm()\">Apply</div>\n"
    "    </div>\n"
    "  </div>\n"
    "\n"
    "  <script>\n"
    "  function _el() { return event && event.currentTarget; }\n"
    "  function onClose() { window.close(); }\n"
    "  function onMinimize() {}\n"
    "  function onMaximize() {}\n"
    "  function onTabSwitch() {\n"
    "    const el = _el();\n"
    "    const tab = el.dataset.tab;\n"
    "    document.querySelectorAll('.nav_item').forEach(n => n.classList.remove('active'));\n"
    "    el.classList.add('active');\n"
    "    document.querySelectorAll('.tab_panel').forEach(p => p.classList.remove('active'));\n"
    "    const panel = document.getElementById('tab_' + tab);\n"
    "    if (panel) panel.classList.add('active');\n"
    "  }\n"
    "  function onToggleClick() { _el().classList.toggle('on'); }\n"
    "  function onCheckboxClick() { _el().classList.toggle('checked'); }\n"
    "  function onApply() { document.getElementById('modal_overlay').classList.remove('hidden'); }\n"
    "  function onModalCancel() { document.getElementById('modal_overlay').classList.add('hidden'); }\n"
    "  function onModalConfirm() { document.getElementById('modal_overlay').classList.add('hidden'); }\n"
    "  function onToastDismiss() { document.getElementById('toast').style.display = 'none'; }\n"
    "  function onInfoClose() { document.getElementById('info_win').style.display = 'none'; }\n"
    "  function onDockInfo() {\n"
    "    const w = document.getElementById('info_win');\n"
    "    w.style.display = w.style.display === 'none' ? '' : 'none';\n"
    "  }\n"
    "  function onDockTheme() { document.querySelector('.toggle')?.classList.toggle('on'); }\n"
    "  function onDockNotify() { document.querySelector('.checkbox')?.classList.toggle('checked'); }\n"
    "  function onDockToast() { document.getElementById('toast').style.display = ''; }\n"
    "  function onSwatchClick() {\n"
    "    const el = _el();\n"
    "    document.querySelectorAll('.swatch').forEach(s => s.classList.remove('sel'));\n"
    "    el.classList.add('sel');\n"
    "  }\n"
    "  function onTabPillClick() {\n"
    "    const el = _el();\n"
    "    el.parentElement.querySelectorAll('.tab_pill').forEach(p => p.classList.remove('active'));\n"
    "    el.classList.add('active');\n"
    "  }\n"
    "  function onScreenshot() { alert('Press F12 in Vespera GUI'); }\n"
    "  </script>\n"
    "</body>\n"
    "</html>\n"
