    "<!DOCTYPE html>\n"
    "<html lang=\"en\">\n"
    "<head>\n"
    "  <meta charset=\"utf-8\">\n"
    "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
    "  <title>Vespera GUI Engine v4.2</title>\n"
    "  <link rel=\"stylesheet\" type=\"text/css\" href=\"luna-ui.css\">\n"
    "</head>\n"
    "<body>\n"
    "\n"
    "<!-- ================================================================\n"
    "     MAIN WINDOW  760×620\n"
    "================================================================ -->\n"
    "<div id=\"main_win\" class=\"window\">\n"
    "\n"
    "  <!-- Title bar -->\n"
    "  <div id=\"title_bar\">\n"
    "    <div class=\"title_drag\"></div>\n"
    "    <div id=\"btn_close\" class=\"btn_os\" data-action=\"modal\"></div>\n"
    "    <div id=\"btn_min\"   class=\"btn_os\"></div>\n"
    "    <div id=\"btn_max\"   class=\"btn_os\"></div>\n"
    "    <div id=\"title_text\">Vespera &mdash; System Preferences</div>\n"
    "  </div>\n"
    "\n"
    "  <!-- Sidebar 196px -->\n"
    "  <div id=\"sidebar\">\n"
    "    <div id=\"sidebar_avatar\"></div>\n"
    "    <div id=\"sidebar_username\">Yuichiro N.</div>\n"
    "    <div id=\"sidebar_role\">Admin &middot; Pro</div>\n"
    "    <div id=\"sidebar_status\"><div class=\"status_dot\"></div>Online</div>\n"
    "\n"
    "    <div id=\"sidebar_nav\">\n"
    "      <div class=\"nav_item active\" data-tab=\"dashboard\">\n"
    "        <div class=\"nav_icon\">&#9638;</div>Dashboard\n"
    "        <div class=\"nav_dot green\"></div>\n"
    "      </div>\n"
    "      <div class=\"nav_item\" data-tab=\"appearance\">\n"
    "        <div class=\"nav_icon\">&#9672;</div>Appearance\n"
    "      </div>\n"
    "      <div class=\"nav_item\" data-tab=\"layout\">\n"
    "        <div class=\"nav_icon\">&#8862;</div>Layout\n"
    "      </div>\n"
    "      <div class=\"nav_item\" data-tab=\"network\">\n"
    "        <div class=\"nav_icon\">&#8961;</div>Network\n"
    "        <div class=\"nav_dot amber\"></div>\n"
    "      </div>\n"
    "      <div class=\"nav_item\" data-tab=\"security\">\n"
    "        <div class=\"nav_icon\">&#8859;</div>Security\n"
    "        <div class=\"nav_dot red\"></div>\n"
    "      </div>\n"
    "    </div>\n"
    "\n"
    "    <!-- Mini resource bars -->\n"
    "    <div id=\"sidebar_stats\">\n"
    "      <div class=\"stat_row\">\n"
    "        <div class=\"stat_key\">CPU</div>\n"
    "        <div class=\"stat_bar_wrap\"><div class=\"stat_bar_fill\" style=\"width:48%\"></div></div>\n"
    "        <div class=\"stat_num\">48%</div>\n"
    "      </div>\n"
    "      <div class=\"stat_row\">\n"
    "        <div class=\"stat_key\">MEM</div>\n"
    "        <div class=\"stat_bar_wrap\"><div class=\"stat_bar_fill mem\" style=\"width:62%\"></div></div>\n"
    "        <div class=\"stat_num\">62%</div>\n"
    "      </div>\n"
    "      <div class=\"stat_row\">\n"
    "        <div class=\"stat_key\">NET</div>\n"
    "        <div class=\"stat_bar_wrap\"><div class=\"stat_bar_fill net\" style=\"width:31%\"></div></div>\n"
    "        <div class=\"stat_num\">31%</div>\n"
    "      </div>\n"
    "      <div class=\"stat_row\">\n"
    "        <div class=\"stat_key\">GPU</div>\n"
    "        <div class=\"stat_bar_wrap\"><div class=\"stat_bar_fill gpu\" style=\"width:77%\"></div></div>\n"
    "        <div class=\"stat_num\">77%</div>\n"
    "      </div>\n"
    "    </div>\n"
    "    <div id=\"sidebar_version\">Vespera v4.2.1 &middot; Luna UI</div>\n"
    "  </div>\n"
    "\n"
    "  <!-- Content area -->\n"
    "  <div id=\"content\">\n"
    "\n"
    "    <!-- ============================================================\n"
    "         DASHBOARD\n"
    "    ============================================================ -->\n"
    "    <div id=\"tab_dashboard\" class=\"tab_panel active\">\n"
    "      <div class=\"section_title\">Dashboard</div>\n"
    "      <div class=\"section_desc\">Real-time system overview and key performance indicators.</div>\n"
    "\n"
    "      <!-- KPI card row -->\n"
    "      <div class=\"kpi_row\">\n"
    "\n"
    "        <div class=\"kpi_card\">\n"
    "          <div class=\"kpi_head\">\n"
    "            <div class=\"kpi_icon green\">&#8593;</div>\n"
    "            <div class=\"kpi_delta up\">+12%</div>\n"
    "          </div>\n"
    "          <div class=\"kpi_val\">98.4%</div>\n"
    "          <div class=\"kpi_label\">Uptime</div>\n"
    "          <div class=\"sparkline\">\n"
    "            <div class=\"spark_bar\" style=\"height:45%\"></div>\n"
    "            <div class=\"spark_bar\" style=\"height:60%\"></div>\n"
    "            <div class=\"spark_bar\" style=\"height:52%\"></div>\n"
    "            <div class=\"spark_bar\" style=\"height:78%\"></div>\n"
    "            <div class=\"spark_bar\" style=\"height:65%\"></div>\n"
    "            <div class=\"spark_bar\" style=\"height:88%\"></div>\n"
    "            <div class=\"spark_bar\" style=\"height:72%\"></div>\n"
    "            <div class=\"spark_bar\" style=\"height:94%\"></div>\n"
    "            <div class=\"spark_bar\" style=\"height:100%;background:rgba(99,102,241,.75)\"></div>\n"
    "          </div>\n"
    "        </div>\n"
    "\n"
    "        <div class=\"kpi_card\">\n"
    "          <div class=\"kpi_head\">\n"
    "            <div class=\"kpi_icon indigo\">P</div>\n"
    "            <div class=\"kpi_delta up\">+3</div>\n"
    "          </div>\n"
    "          <div class=\"kpi_val\">14</div>\n"
    "          <div class=\"kpi_label\">Active Peers</div>\n"
    "          <div class=\"sparkline\">\n"
    "            <div class=\"spark_bar\" style=\"height:40%;background:rgba(168,85,247,.35)\"></div>\n"
    "            <div class=\"spark_bar\" style=\"height:55%;background:rgba(168,85,247,.35)\"></div>\n"
    "            <div class=\"spark_bar\" style=\"height:48%;background:rgba(168,85,247,.35)\"></div>\n"
    "            <div class=\"spark_bar\" style=\"height:70%;background:rgba(168,85,247,.35)\"></div>\n"
    "            <div class=\"spark_bar\" style=\"height:62%;background:rgba(168,85,247,.35)\"></div>\n"
    "            <div class=\"spark_bar\" style=\"height:80%;background:rgba(168,85,247,.35)\"></div>\n"
    "            <div class=\"spark_bar\" style=\"height:90%;background:rgba(168,85,247,.35)\"></div>\n"
    "            <div class=\"spark_bar\" style=\"height:75%;background:rgba(168,85,247,.35)\"></div>\n"
    "            <div class=\"spark_bar\" style=\"height:100%;background:rgba(168,85,247,.7)\"></div>\n"
    "          </div>\n"
    "        </div>\n"
    "\n"
    "        <div class=\"kpi_card\">\n"
    "          <div class=\"kpi_head\">\n"
    "            <div class=\"kpi_icon amber\">&#8635;</div>\n"
    "            <div class=\"kpi_delta down\">+8ms</div>\n"
    "          </div>\n"
    "          <div class=\"kpi_val\">24ms</div>\n"
    "          <div class=\"kpi_label\">Avg Latency</div>\n"
    "          <div class=\"sparkline\">\n"
    "            <div class=\"spark_bar\" style=\"height:30%;background:rgba(251,191,36,.35)\"></div>\n"
    "            <div class=\"spark_bar\" style=\"height:45%;background:rgba(251,191,36,.35)\"></div>\n"
    "            <div class=\"spark_bar\" style=\"height:80%;background:rgba(251,191,36,.55)\"></div>\n"
    "            <div class=\"spark_bar\" style=\"height:35%;background:rgba(251,191,36,.35)\"></div>\n"
    "            <div class=\"spark_bar\" style=\"height:50%;background:rgba(251,191,36,.35)\"></div>\n"
    "            <div class=\"spark_bar\" style=\"height:40%;background:rgba(251,191,36,.35)\"></div>\n"
    "            <div class=\"spark_bar\" style=\"height:60%;background:rgba(251,191,36,.40)\"></div>\n"
    "            <div class=\"spark_bar\" style=\"height:45%;background:rgba(251,191,36,.35)\"></div>\n"
    "            <div class=\"spark_bar\" style=\"height:100%;background:rgba(251,191,36,.7)\"></div>\n"
    "          </div>\n"
    "        </div>\n"
    "\n"
    "        <div class=\"kpi_card\">\n"
    "          <div class=\"kpi_head\">\n"
    "            <div class=\"kpi_icon cyan\">&#8645;</div>\n"
    "            <div class=\"kpi_delta up\">+2.1G</div>\n"
    "          </div>\n"
    "          <div class=\"kpi_val\">3.7G</div>\n"
    "          <div class=\"kpi_label\">Total Traffic</div>\n"
    "          <div class=\"sparkline\">\n"
    "            <div class=\"spark_bar\" style=\"height:25%;background:rgba(34,211,238,.30)\"></div>\n"
    "            <div class=\"spark_bar\" style=\"height:40%;background:rgba(34,211,238,.30)\"></div>\n"
    "            <div class=\"spark_bar\" style=\"height:55%;background:rgba(34,211,238,.35)\"></div>\n"
    "            <div class=\"spark_bar\" style=\"height:48%;background:rgba(34,211,238,.32)\"></div>\n"
    "            <div class=\"spark_bar\" style=\"height:72%;background:rgba(34,211,238,.45)\"></div>\n"
    "            <div class=\"spark_bar\" style=\"height:65%;background:rgba(34,211,238,.42)\"></div>\n"
    "            <div class=\"spark_bar\" style=\"height:85%;background:rgba(34,211,238,.55)\"></div>\n"
    "            <div class=\"spark_bar\" style=\"height:78%;background:rgba(34,211,238,.50)\"></div>\n"
    "            <div class=\"spark_bar\" style=\"height:100%;background:rgba(34,211,238,.75)\"></div>\n"
    "          </div>\n"
    "        </div>\n"
    "\n"
    "      </div><!-- /kpi_row -->\n"
    "\n"
    "      <!-- Weekly bar chart -->\n"
    "      <div class=\"chart_card\">\n"
    "        <div class=\"chart_head\">\n"
    "          <div class=\"chart_title\">Weekly Throughput</div>\n"
    "          <div class=\"chart_legend\">\n"
    "            <div class=\"legend_item\">\n"
    "              <div class=\"legend_dot\" style=\"background:#6366f1\"></div>\n"
    "              <div class=\"legend_label\">TX</div>\n"
    "            </div>\n"
    "            <div class=\"legend_item\">\n"
    "              <div class=\"legend_dot\" style=\"background:#a855f7\"></div>\n"
    "              <div class=\"legend_label\">RX</div>\n"
    "            </div>\n"
    "            <div class=\"legend_item\">\n"
    "              <div class=\"legend_dot\" style=\"background:#22d3ee\"></div>\n"
    "              <div class=\"legend_label\">Errors</div>\n"
    "            </div>\n"
    "          </div>\n"
    "        </div>\n"
    "        <div class=\"bar_chart\">\n"
    "          <div class=\"bar_col\"><div class=\"bar_fill\"         style=\"height:45%\"></div><div class=\"bar_label\">Mon</div></div>\n"
    "          <div class=\"bar_col\"><div class=\"bar_fill violet\"  style=\"height:30%\"></div><div class=\"bar_label\">Mon</div></div>\n"
    "          <div class=\"bar_col\"><div class=\"bar_fill cyan\"    style=\"height:10%\"></div><div class=\"bar_label\">Mon</div></div>\n"
    "          <div class=\"bar_col\"><div class=\"bar_fill\"         style=\"height:68%\"></div><div class=\"bar_label\">Tue</div></div>\n"
    "          <div class=\"bar_col\"><div class=\"bar_fill violet\"  style=\"height:52%\"></div><div class=\"bar_label\">Tue</div></div>\n"
    "          <div class=\"bar_col\"><div class=\"bar_fill cyan\"    style=\"height:7%\"> </div><div class=\"bar_label\">Tue</div></div>\n"
    "          <div class=\"bar_col\"><div class=\"bar_fill\"         style=\"height:82%\"></div><div class=\"bar_label\">Wed</div></div>\n"
    "          <div class=\"bar_col\"><div class=\"bar_fill violet\"  style=\"height:74%\"></div><div class=\"bar_label\">Wed</div></div>\n"
    "          <div class=\"bar_col\"><div class=\"bar_fill cyan\"    style=\"height:15%\"></div><div class=\"bar_label\">Wed</div></div>\n"
    "          <div class=\"bar_col\"><div class=\"bar_fill\"         style=\"height:55%\"></div><div class=\"bar_label\">Thu</div></div>\n"
    "          <div class=\"bar_col\"><div class=\"bar_fill violet\"  style=\"height:48%\"></div><div class=\"bar_label\">Thu</div></div>\n"
    "          <div class=\"bar_col\"><div class=\"bar_fill cyan\"    style=\"height:5%\"> </div><div class=\"bar_label\">Thu</div></div>\n"
    "          <div class=\"bar_col\"><div class=\"bar_fill\"         style=\"height:91%\"></div><div class=\"bar_label\">Fri</div></div>\n"
    "          <div class=\"bar_col\"><div class=\"bar_fill violet\"  style=\"height:85%\"></div><div class=\"bar_label\">Fri</div></div>\n"
    "          <div class=\"bar_col\"><div class=\"bar_fill cyan\"    style=\"height:20%\"></div><div class=\"bar_label\">Fri</div></div>\n"
    "          <div class=\"bar_col\"><div class=\"bar_fill emerald\" style=\"height:62%\"></div><div class=\"bar_label\">Sat</div></div>\n"
    "          <div class=\"bar_col\"><div class=\"bar_fill amber\"   style=\"height:50%\"></div><div class=\"bar_label\">Sat</div></div>\n"
    "          <div class=\"bar_col\"><div class=\"bar_fill cyan\"    style=\"height:8%\"> </div><div class=\"bar_label\">Sat</div></div>\n"
    "          <div class=\"bar_col\"><div class=\"bar_fill emerald\" style=\"height:38%\"></div><div class=\"bar_label\">Sun</div></div>\n"
    "          <div class=\"bar_col\"><div class=\"bar_fill amber\"   style=\"height:29%\"></div><div class=\"bar_label\">Sun</div></div>\n"
    "          <div class=\"bar_col\"><div class=\"bar_fill cyan\"    style=\"height:3%\"> </div><div class=\"bar_label\">Sun</div></div>\n"
    "        </div>\n"
    "      </div><!-- /chart_card -->\n"
    "\n"
    "      <!-- Connection status row -->\n"
    "      <div class=\"conn_row\">\n"
    "        <div class=\"conn_card\">\n"
    "          <div class=\"conn_head\">\n"
    "            <div class=\"conn_name\">Tokyo Edge-1</div>\n"
    "            <div class=\"conn_badge ok\">Online</div>\n"
    "          </div>\n"
    "          <div class=\"conn_host\">10.88.0.12 &middot; tun0 &middot; PQC</div>\n"
    "          <div class=\"conn_bar_wrap\"><div class=\"conn_bar\" style=\"width:78%\"></div></div>\n"
    "        </div>\n"
    "        <div class=\"conn_card\">\n"
    "          <div class=\"conn_head\">\n"
    "            <div class=\"conn_name\">Singapore-2</div>\n"
    "            <div class=\"conn_badge ok\">Online</div>\n"
    "          </div>\n"
    "          <div class=\"conn_host\">10.88.0.21 &middot; tun1 &middot; AES-GCM</div>\n"
    "          <div class=\"conn_bar_wrap\"><div class=\"conn_bar\" style=\"width:55%\"></div></div>\n"
    "        </div>\n"
    "        <div class=\"conn_card\">\n"
    "          <div class=\"conn_head\">\n"
    "            <div class=\"conn_name\">Frankfurt-3</div>\n"
    "            <div class=\"conn_badge warn\">High RTT</div>\n"
    "          </div>\n"
    "          <div class=\"conn_host\">10.88.0.37 &middot; tun2 &middot; ML-KEM</div>\n"
    "          <div class=\"conn_bar_wrap\">\n"
    "            <div class=\"conn_bar\" style=\"width:30%;background:linear-gradient(90deg,#fbbf24,#f59e0b)\"></div>\n"
    "          </div>\n"
    "        </div>\n"
    "        <div class=\"conn_card\">\n"
    "          <div class=\"conn_head\">\n"
    "            <div class=\"conn_name\">New York-4</div>\n"
    "            <div class=\"conn_badge err\">Offline</div>\n"
    "          </div>\n"
    "          <div class=\"conn_host\">10.88.0.44 &middot; &mdash; &middot; Reconnecting</div>\n"
    "          <div class=\"conn_bar_wrap\">\n"
    "            <div class=\"conn_bar\" style=\"width:5%;background:linear-gradient(90deg,#f43f5e,#be123c)\"></div>\n"
    "          </div>\n"
    "        </div>\n"
    "      </div><!-- /conn_row -->\n"
    "\n"
    "    </div><!-- /tab_dashboard -->\n"
    "\n"
    "\n"
    "    <!-- ============================================================\n"
    "         APPEARANCE\n"
    "    ============================================================ -->\n"
    "    <div id=\"tab_appearance\" class=\"tab_panel\">\n"
    "      <div class=\"section_title\">Appearance</div>\n"
    "      <div class=\"section_desc\">Customize the visual style of Vespera. All changes apply live.</div>\n"
    "\n"
    "      <!-- Toolbar -->\n"
    "      <div id=\"toolbar\">\n"
    "        <div class=\"tool_btn active\" data-group=\"theme\" data-val=\"aurora\">Aurora</div>\n"
    "        <div class=\"tool_btn\" data-group=\"theme\" data-val=\"neon\">Neon</div>\n"
    "        <div class=\"tool_btn\" data-group=\"theme\" data-val=\"minimal\">Minimal</div>\n"
    "        <div class=\"tool_btn\" data-group=\"theme\" data-val=\"solar\">Solar</div>\n"
    "        <div id=\"apply_btn\">Apply</div>\n"
    "      </div>\n"
    "\n"
    "      <!-- Input fields with floating labels -->\n"
    "      <div class=\"demo_label\">Input fields</div>\n"
    "      <div style=\"display:flex;gap:8px\">\n"
    "        <div class=\"input_group\" style=\"flex:1\">\n"
    "          <div class=\"input_label\">VPN Alias</div>\n"
    "          <input class=\"input_field\" type=\"text\" value=\"vespera-home\">\n"
    "        </div>\n"
    "        <div class=\"input_group\" style=\"flex:1\">\n"
    "          <div class=\"input_label\">Passphrase</div>\n"
    "          <input class=\"input_field\" type=\"password\" placeholder=\"&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;\">\n"
    "        </div>\n"
    "      </div>\n"
    "\n"
    "      <div class=\"sep\"></div>\n"
    "\n"
    "      <!-- Color palette -->\n"
    "      <div class=\"demo_label\">Accent palette</div>\n"
    "      <div class=\"palette_row\">\n"
    "        <div class=\"pal_swatch\" style=\"background:linear-gradient(135deg,#6366f1,#4338ca)\"></div>\n"
    "        <div class=\"pal_swatch\" style=\"background:linear-gradient(135deg,#a855f7,#7c3aed)\"></div>\n"
    "        <div class=\"pal_swatch\" style=\"background:linear-gradient(135deg,#22d3ee,#0891b2)\"></div>\n"
    "        <div class=\"pal_swatch\" style=\"background:linear-gradient(135deg,#34d399,#059669)\"></div>\n"
    "        <div class=\"pal_swatch\" style=\"background:linear-gradient(135deg,#fbbf24,#d97706)\"></div>\n"
    "        <div class=\"pal_swatch\" style=\"background:linear-gradient(135deg,#f43f5e,#be123c)\"></div>\n"
    "        <div class=\"pal_swatch\" style=\"background:linear-gradient(135deg,#ec4899,#be185d)\"></div>\n"
    "        <div class=\"pal_swatch\" style=\"background:linear-gradient(135deg,#38bdf8,#0284c7)\"></div>\n"
    "      </div>\n"
    "\n"
    "      <!-- Dot swatches -->\n"
    "      <div style=\"display:flex;gap:8px;align-items:center\">\n"
    "        <div class=\"demo_label\" style=\"width:82px;flex-shrink:0\">Dot swatches</div>\n"
    "        <div style=\"display:flex;gap:6px\">\n"
    "          <div class=\"swatch sel\" style=\"background:#6366f1\"></div>\n"
    "          <div class=\"swatch\" style=\"background:#a855f7\"></div>\n"
    "          <div class=\"swatch\" style=\"background:#22d3ee\"></div>\n"
    "          <div class=\"swatch\" style=\"background:#34d399\"></div>\n"
    "          <div class=\"swatch\" style=\"background:#fbbf24\"></div>\n"
    "          <div class=\"swatch\" style=\"background:#f43f5e\"></div>\n"
    "          <div class=\"swatch\" style=\"background:#ec4899\"></div>\n"
    "          <div class=\"swatch\" style=\"background:#94a3b8\"></div>\n"
    "        </div>\n"
    "      </div>\n"
    "\n"
    "      <div class=\"sep\"></div>\n"
    "\n"
    "      <!-- Slider -->\n"
    "      <div class=\"setting_row col\">\n"
    "        <div class=\"setting_label\">UI Scale &mdash; 1.0&times;</div>\n"
    "        <div id=\"slider_track\">\n"
    "          <div id=\"slider_fill\"></div>\n"
    "          <div id=\"slider_thumb\"></div>\n"
    "        </div>\n"
    "      </div>\n"
    "\n"
    "      <!-- Toggles -->\n"
    "      <div class=\"setting_row\">\n"
    "        <div class=\"setting_label\">Dark mode</div>\n"
    "        <div class=\"toggle on\" data-key=\"dark_mode\"><div class=\"toggle_knob\"></div></div>\n"
    "      </div>\n"
    "      <div class=\"setting_row\">\n"
    "        <div class=\"setting_label\">Translucency</div>\n"
    "        <div class=\"toggle on\" data-key=\"translucency\"><div class=\"toggle_knob\"></div></div>\n"
    "      </div>\n"
    "      <div class=\"setting_row\">\n"
    "        <div class=\"setting_label\">Aurora background animation</div>\n"
    "        <div class=\"toggle on\" data-key=\"aurora_anim\"><div class=\"toggle_knob\"></div></div>\n"
    "      </div>\n"
    "      <div class=\"setting_row\">\n"
    "        <div class=\"setting_label\">Reduce motion</div>\n"
    "        <div class=\"toggle\" data-key=\"reduce_motion\"><div class=\"toggle_knob\"></div></div>\n"
    "      </div>\n"
    "\n"
    "      <!-- Checkboxes -->\n"
    "      <div class=\"setting_row\">\n"
    "        <div class=\"setting_label\">Show menu bar</div>\n"
    "        <div class=\"checkbox checked\" data-key=\"menubar\"></div>\n"
    "      </div>\n"
    "      <div class=\"setting_row\">\n"
    "        <div class=\"setting_label\">Haptic feedback</div>\n"
    "        <div class=\"checkbox\" data-key=\"haptic\"></div>\n"
    "      </div>\n"
    "\n"
    "      <!-- Dropdown -->\n"
    "      <div class=\"setting_row\">\n"
    "        <div class=\"setting_label\">Theme</div>\n"
    "        <div id=\"theme_combo\">\n"
    "          <div id=\"theme_select_box\">Aurora Noir &#9662;</div>\n"
    "          <div id=\"select_panel\" class=\"hidden\">\n"
    "            <div class=\"select_option\">Aurora Noir</div>\n"
    "            <div class=\"select_option\">Neon Pulse</div>\n"
    "            <div class=\"select_option\">Solar Minimal</div>\n"
    "            <div class=\"select_option\">Deep Space</div>\n"
    "          </div>\n"
    "        </div>\n"
    "      </div>\n"
    "\n"
    "      <div class=\"sep\"></div>\n"
    "\n"
    "      <!-- Chips -->\n"
    "      <div id=\"chip_row\">\n"
    "        <div class=\"chip accent\">Default</div>\n"
    "        <div class=\"chip\">Compact</div>\n"
    "        <div class=\"chip\">Comfortable</div>\n"
    "        <div class=\"chip\">Rounded</div>\n"
    "        <div class=\"chip\">Flat</div>\n"
    "        <div class=\"chip\">Minimal</div>\n"
    "        <div class=\"chip\">Pro</div>\n"
    "      </div>\n"
    "\n"
    "      <!-- Progress bar -->\n"
    "      <div id=\"progress_track\"><div id=\"progress_fill\"></div></div>\n"
    "\n"
    "      <!-- Keyboard shortcuts card -->\n"
    "      <div class=\"kbd_card\">\n"
    "        <div class=\"kbd_row\">\n"
    "          <div class=\"kbd_label\">Toggle sidebar</div>\n"
    "          <div class=\"kbd_key\">&#8984; B</div>\n"
    "        </div>\n"
    "        <div class=\"kbd_row\">\n"
    "          <div class=\"kbd_label\">Quick search</div>\n"
    "          <div class=\"kbd_key\">&#8984; K</div>\n"
    "        </div>\n"
    "        <div class=\"kbd_row\">\n"
    "          <div class=\"kbd_label\">Full screen</div>\n"
    "          <div class=\"kbd_key\">&#8984; &#8679; F</div>\n"
    "        </div>\n"
    "        <div class=\"kbd_row\">\n"
    "          <div class=\"kbd_label\">Settings</div>\n"
    "          <div class=\"kbd_key\">&#8984; ,</div>\n"
    "        </div>\n"
    "      </div>\n"
    "\n"
    "      <!-- Activity log -->\n"
    "      <div id=\"activity_panel\">\n"
    "        <div class=\"activity_sticky\">Recent Activity</div>\n"
    "        <div class=\"activity_line\">14:32 &middot; Theme changed &rarr; Aurora Noir</div>\n"
    "        <div class=\"activity_line\">14:28 &middot; Translucency enabled</div>\n"
    "        <div class=\"activity_line\">14:15 &middot; Accent updated &rarr; Indigo</div>\n"
    "        <div class=\"activity_line\">13:50 &middot; Font scale set to 1.0&times;</div>\n"
    "        <div class=\"activity_line\">13:44 &middot; Dark mode toggled on</div>\n"
    "        <div class=\"activity_sticky_bottom\">&#8593; Scroll for older entries</div>\n"
    "      </div>\n"
    "\n"
    "    </div><!-- /tab_appearance -->\n"
    "\n"
    "\n"
    "    <!-- ============================================================\n"
    "         LAYOUT DEMOS\n"
    "    ============================================================ -->\n"
    "    <div id=\"tab_layout\" class=\"tab_panel\">\n"
    "      <div class=\"section_title\">Layout Engine</div>\n"
    "      <div class=\"section_desc\">Live demos of flex, grid and overflow features built into Luna UI.</div>\n"
    "\n"
    "      <!-- Sub-tab pills -->\n"
    "      <div class=\"tab_pill_bar\">\n"
    "        <div class=\"tab_pill active\">Flex</div>\n"
    "        <div class=\"tab_pill\">Grid</div>\n"
    "        <div class=\"tab_pill\">Overflow</div>\n"
    "        <div class=\"tab_pill\">Type</div>\n"
    "      </div>\n"
    "\n"
    "      <!-- flex-grow / flex-shrink -->\n"
    "      <div class=\"demo_card\">\n"
    "        <div class=\"demo_card_head\">\n"
    "          <div class=\"demo_tag indigo\">Flex</div>\n"
    "          <div class=\"demo_caption\">flex-grow: 1 &middot; flex-shrink: 0 &middot; flex: 1 1 auto</div>\n"
    "        </div>\n"
    "        <div class=\"demo_flex_shrink\">\n"
    "          <div class=\"fs_item\">Fixed</div>\n"
    "          <div class=\"fs_item grow\">Grow</div>\n"
    "          <div class=\"fs_item shrink\">Shrink me (long label text)</div>\n"
    "          <div class=\"fs_item\">Fixed</div>\n"
    "        </div>\n"
    "      </div>\n"
    "\n"
    "      <!-- align-self -->\n"
    "      <div class=\"demo_card\">\n"
    "        <div class=\"demo_card_head\">\n"
    "          <div class=\"demo_tag violet\">Flex</div>\n"
    "          <div class=\"demo_caption\">align-self: start | center | end | stretch | baseline</div>\n"
    "        </div>\n"
    "        <div class=\"demo_align_self\">\n"
    "          <div class=\"as_item start\">start</div>\n"
    "          <div class=\"as_item center\">center</div>\n"
    "          <div class=\"as_item end\">end</div>\n"
    "          <div class=\"as_item stretch\">stretch</div>\n"
    "          <div class=\"as_item baseline\">baseline</div>\n"
    "        </div>\n"
    "      </div>\n"
    "\n"
    "      <!-- grid-auto-flow: row dense -->\n"
    "      <div class=\"demo_card\">\n"
    "        <div class=\"demo_card_head\">\n"
    "          <div class=\"demo_tag cyan\">Grid</div>\n"
    "          <div class=\"demo_caption\">grid-auto-flow: row dense &middot; grid-column: span 2</div>\n"
    "        </div>\n"
    "        <div class=\"demo_grid_dense\">\n"
    "          <div class=\"gc\">A</div>\n"
    "          <div class=\"gc wide\">B (wide)</div>\n"
    "          <div class=\"gc\">C</div>\n"
    "          <div class=\"gc\">D</div>\n"
    "          <div class=\"gc wide\">E (wide)</div>\n"
    "          <div class=\"gc\">F</div>\n"
    "          <div class=\"gc\">G</div>\n"
    "          <div class=\"gc\">H</div>\n"
    "        </div>\n"
    "      </div>\n"
    "\n"
    "      <!-- grid-auto-flow: column dense -->\n"
    "      <div class=\"demo_card\">\n"
    "        <div class=\"demo_card_head\">\n"
    "          <div class=\"demo_tag emerald\">Grid</div>\n"
    "          <div class=\"demo_caption\">grid-auto-flow: column dense &middot; grid-row: span 2</div>\n"
    "        </div>\n"
    "        <div class=\"demo_grid_col_dense\">\n"
    "          <div class=\"gcc\">1</div>\n"
    "          <div class=\"gcc b\">2</div>\n"
    "          <div class=\"gcc tall\">3 (tall)</div>\n"
    "          <div class=\"gcc\">4</div>\n"
    "          <div class=\"gcc b\">5</div>\n"
    "          <div class=\"gcc\">6</div>\n"
    "          <div class=\"gcc b\">7</div>\n"
    "        </div>\n"
    "      </div>\n"
    "\n"
    "      <!-- grid-template-areas -->\n"
    "      <div class=\"demo_card\">\n"
    "        <div class=\"demo_card_head\">\n"
    "          <div class=\"demo_tag amber\">Grid</div>\n"
    "          <div class=\"demo_caption\">grid-template-areas: \"header header\" \"sidebar main\" \"footer footer\"</div>\n"
    "        </div>\n"
    "        <div class=\"demo_areas\">\n"
    "          <div class=\"area header\">header</div>\n"
    "          <div class=\"area sidebar\">sidebar</div>\n"
    "          <div class=\"area main\">main</div>\n"
    "          <div class=\"area footer\">footer</div>\n"
    "        </div>\n"
    "      </div>\n"
    "\n"
    "      <!-- min-content / max-content / 1fr -->\n"
    "      <div class=\"demo_card\">\n"
    "        <div class=\"demo_card_head\">\n"
    "          <div class=\"demo_tag pink\">Grid</div>\n"
    "          <div class=\"demo_caption\">grid-template-columns: min-content max-content 1fr</div>\n"
    "        </div>\n"
    "        <div class=\"demo_sizing\">\n"
    "          <div class=\"sz_cell min\">Min</div>\n"
    "          <div class=\"sz_cell max\">Max-content fits text</div>\n"
    "          <div class=\"sz_cell fr\">1fr fills remaining</div>\n"
    "        </div>\n"
    "      </div>\n"
    "\n"
    "      <!-- overflow: clip + ellipsis + line-clamp -->\n"
    "      <div class=\"demo_card\">\n"
    "        <div class=\"demo_card_head\">\n"
    "          <div class=\"demo_tag indigo\">Overflow</div>\n"
    "          <div class=\"demo_caption\">text-overflow: ellipsis &middot; -webkit-line-clamp: 2</div>\n"
    "        </div>\n"
    "        <div class=\"demo_clip_row\">\n"
    "          <div class=\"clip_box\">\n"
    "            <span>Single-line ellipsis: Vespera is a next-generation mesh VPN kernel with PQC cryptography and CSS rendering.</span>\n"
    "          </div>\n"
    "          <div class=\"clip_box clamp\">\n"
    "            <span>Clamped 2 lines: Vespera blends ML-KEM-768 post-quantum security with an Aurora-themed hardware-accelerated CSS/GL UI engine for next-gen privacy tooling on all platforms.</span>\n"
    "          </div>\n"
    "        </div>\n"
    "      </div>\n"
    "\n"
    "      <!-- Horizontal scroll -->\n"
    "      <div class=\"demo_card\">\n"
    "        <div class=\"demo_card_head\">\n"
    "          <div class=\"demo_tag violet\">Overflow</div>\n"
    "          <div class=\"demo_caption\">overflow-x: auto &middot; width: max-content</div>\n"
    "        </div>\n"
    "        <div id=\"hscroll_panel\">\n"
    "          <div id=\"hscroll_inner\">\n"
    "            <div class=\"hscroll_chip pinned\">Pinned</div>\n"
    "            <div class=\"hscroll_chip\">Alpha Node</div>\n"
    "            <div class=\"hscroll_chip\">Beta Node</div>\n"
    "            <div class=\"hscroll_chip\">Gamma Node</div>\n"
    "            <div class=\"hscroll_chip\">Delta Node</div>\n"
    "            <div class=\"hscroll_chip\">Epsilon</div>\n"
    "            <div class=\"hscroll_chip\">Zeta Node</div>\n"
    "            <div class=\"hscroll_chip\">Eta Relay</div>\n"
    "            <div class=\"hscroll_chip\">Theta Peer</div>\n"
    "            <div class=\"hscroll_chip\">Iota Node</div>\n"
    "            <div class=\"hscroll_chip\">Kappa Edge</div>\n"
    "            <div class=\"hscroll_chip\">Lambda Server</div>\n"
    "          </div>\n"
    "        </div>\n"
    "      </div>\n"
    "\n"
    "    </div><!-- /tab_layout -->\n"
    "\n"
    "\n"
    "    <!-- ============================================================\n"
    "         NETWORK\n"
    "    ============================================================ -->\n"
    "    <div id=\"tab_network\" class=\"tab_panel\">\n"
    "      <div class=\"section_title\">Network</div>\n"
    "      <div class=\"section_desc\">Peer connections, tunnel configuration and traffic statistics.</div>\n"
    "\n"
    "      <!-- Metrics pills -->\n"
    "      <div id=\"metrics_row\">\n"
    "        <div class=\"metric_pill online\">\n"
    "          <div class=\"mp_val\">14 / 16</div>\n"
    "          <div class=\"mp_label\">Peers Online</div>\n"
    "        </div>\n"
    "        <div class=\"metric_pill peers\">\n"
    "          <div class=\"mp_val\">4</div>\n"
    "          <div class=\"mp_label\">Subnets</div>\n"
    "        </div>\n"
    "        <div class=\"metric_pill latency\">\n"
    "          <div class=\"mp_val\">24 ms</div>\n"
    "          <div class=\"mp_label\">Avg RTT</div>\n"
    "        </div>\n"
    "        <div class=\"metric_pill badges\">\n"
    "          <div class=\"badge green\">PQC</div>\n"
    "          <div class=\"badge amber\">TURN</div>\n"
    "          <div class=\"badge green\">P2P</div>\n"
    "          <div class=\"badge green\">NAT</div>\n"
    "        </div>\n"
    "      </div>\n"
    "\n"
    "      <div class=\"sep\"></div>\n"
    "\n"
    "      <div class=\"setting_row\">\n"
    "        <div class=\"setting_label\">Enable gateway mode</div>\n"
    "        <div class=\"toggle on\" data-key=\"gateway\"><div class=\"toggle_knob\"></div></div>\n"
    "      </div>\n"
    "      <div class=\"setting_row\">\n"
    "        <div class=\"setting_label\">NAT / IP masquerade</div>\n"
    "        <div class=\"toggle on\" data-key=\"nat\"><div class=\"toggle_knob\"></div></div>\n"
    "      </div>\n"
    "      <div class=\"setting_row\">\n"
    "        <div class=\"setting_label\">IPv6 tunnel</div>\n"
    "        <div class=\"toggle\" data-key=\"ipv6\"><div class=\"toggle_knob\"></div></div>\n"
    "      </div>\n"
    "      <div class=\"setting_row\">\n"
    "        <div class=\"setting_label\">TURN relay only</div>\n"
    "        <div class=\"toggle\" data-key=\"turn_only\"><div class=\"toggle_knob\"></div></div>\n"
    "      </div>\n"
    "      <div class=\"setting_row\">\n"
    "        <div class=\"setting_label\">Crypto algorithm</div>\n"
    "        <div class=\"setting_val\">ML-KEM-768 + ChaCha20</div>\n"
    "      </div>\n"
    "      <div class=\"setting_row\">\n"
    "        <div class=\"setting_label\">MTU</div>\n"
    "        <div class=\"setting_val\">1400 bytes</div>\n"
    "      </div>\n"
    "      <div class=\"setting_row\">\n"
    "        <div class=\"setting_label\">Heartbeat interval</div>\n"
    "        <div class=\"setting_val\">30 s</div>\n"
    "      </div>\n"
    "      <div class=\"setting_row\">\n"
    "        <div class=\"setting_label\">Web admin dashboard</div>\n"
    "        <div class=\"toggle on\" data-key=\"web_admin\"><div class=\"toggle_knob\"></div></div>\n"
    "      </div>\n"
    "\n"
    "      <div class=\"sep\"></div>\n"
    "\n"
    "      <!-- Bandwidth sliders -->\n"
    "      <div class=\"setting_row\">\n"
    "        <div class=\"setting_label\">Upload limit</div>\n"
    "        <div class=\"slider_track2\">\n"
    "          <div class=\"slider_fill2\" style=\"width:60%\"></div>\n"
    "          <div class=\"slider_thumb2\" style=\"left:60%\"></div>\n"
    "        </div>\n"
    "        <div class=\"setting_val\" style=\"margin-left:10px\">60 Mbps</div>\n"
    "      </div>\n"
    "      <div class=\"setting_row\">\n"
    "        <div class=\"setting_label\">Download limit</div>\n"
    "        <div class=\"slider_track2\">\n"
    "          <div class=\"slider_fill2\" style=\"width:80%\"></div>\n"
    "          <div class=\"slider_thumb2\" style=\"left:80%\"></div>\n"
    "        </div>\n"
    "        <div class=\"setting_val\" style=\"margin-left:10px\">80 Mbps</div>\n"
    "      </div>\n"
    "\n"
    "      <div id=\"status_text\">Last sync: 07-19 14:32:18 JST &middot; Prometheus :8080/metrics</div>\n"
    "    </div><!-- /tab_network -->\n"
    "\n"
    "\n"
    "    <!-- ============================================================\n"
    "         SECURITY\n"
    "    ============================================================ -->\n"
    "    <div id=\"tab_security\" class=\"tab_panel\">\n"
    "      <div class=\"section_title\">Security</div>\n"
    "      <div class=\"section_desc\">Authentication, certificates and post-quantum cryptography settings.</div>\n"
    "\n"
    "      <div class=\"setting_row\">\n"
    "        <div class=\"setting_label\">Authentication required</div>\n"
    "        <div class=\"toggle on\" data-key=\"auth\"><div class=\"toggle_knob\"></div></div>\n"
    "      </div>\n"
    "      <div class=\"setting_row\">\n"
    "        <div class=\"setting_label\">TOTP two-factor</div>\n"
    "        <div class=\"toggle on\" data-key=\"totp\"><div class=\"toggle_knob\"></div></div>\n"
    "      </div>\n"
    "      <div class=\"setting_row\">\n"
    "        <div class=\"setting_label\">Post-quantum crypto (ML-KEM-768)</div>\n"
    "        <div class=\"toggle on\" data-key=\"pqc\"><div class=\"toggle_knob\"></div></div>\n"
    "      </div>\n"
    "      <div class=\"setting_row\">\n"
    "        <div class=\"setting_label\">Certificate pinning</div>\n"
    "        <div class=\"toggle\" data-key=\"cert_pin\"><div class=\"toggle_knob\"></div></div>\n"
    "      </div>\n"
    "      <div class=\"setting_row\">\n"
    "        <div class=\"setting_label\">mTLS client certificates</div>\n"
    "        <div class=\"toggle\" data-key=\"mtls\"><div class=\"toggle_knob\"></div></div>\n"
    "      </div>\n"
    "      <div class=\"setting_row\">\n"
    "        <div class=\"setting_label\">Rotate keys on reconnect</div>\n"
    "        <div class=\"toggle on\" data-key=\"key_rotate\"><div class=\"toggle_knob\"></div></div>\n"
    "      </div>\n"
    "      <div class=\"setting_row\">\n"
    "        <div class=\"setting_label\">Perfect forward secrecy</div>\n"
    "        <div class=\"toggle on\" data-key=\"pfs\"><div class=\"toggle_knob\"></div></div>\n"
    "      </div>\n"
    "      <div class=\"setting_row\">\n"
    "        <div class=\"setting_label\">Audit log</div>\n"
    "        <div class=\"checkbox checked\" data-key=\"audit_log\"></div>\n"
    "      </div>\n"
    "      <div class=\"setting_row\">\n"
    "        <div class=\"setting_label\">Block cleartext fallback</div>\n"
    "        <div class=\"checkbox checked\" data-key=\"no_cleartext\"></div>\n"
    "      </div>\n"
    "      <div class=\"setting_row\">\n"
    "        <div class=\"setting_label\">Endpoint isolation</div>\n"
    "        <div class=\"checkbox\" data-key=\"ep_isolate\"></div>\n"
    "      </div>\n"
    "\n"
    "      <div class=\"sep\"></div>\n"
    "\n"
    "      <div class=\"demo_label\">Key exchange algorithms</div>\n"
    "      <div id=\"chip_row\" style=\"margin-top:0\">\n"
    "        <div class=\"chip accent\">ML-KEM-768</div>\n"
    "        <div class=\"chip\">X25519</div>\n"
    "        <div class=\"chip\">ECDH-P256</div>\n"
    "        <div class=\"chip\">Kyber-1024</div>\n"
    "        <div class=\"chip\">NTRU-HPS</div>\n"
    "      </div>\n"
    "\n"
    "      <div class=\"sep\"></div>\n"
    "\n"
    "      <div class=\"kbd_card\">\n"
    "        <div class=\"kbd_row\">\n"
    "          <div class=\"kbd_label\">Lock session</div>\n"
    "          <div class=\"kbd_key\">&#8984; L</div>\n"
    "        </div>\n"
    "        <div class=\"kbd_row\">\n"
    "          <div class=\"kbd_label\">Rotate keys now</div>\n"
    "          <div class=\"kbd_key\">&#8984; &#8679; R</div>\n"
    "        </div>\n"
    "        <div class=\"kbd_row\">\n"
    "          <div class=\"kbd_label\">Revoke all sessions</div>\n"
    "          <div class=\"kbd_key\">&#8984; &#8997; &#9003;</div>\n"
    "        </div>\n"
    "      </div>\n"
    "\n"
    "    </div><!-- /tab_security -->\n"
    "\n"
    "  </div><!-- /content -->\n"
    "</div><!-- /main_win -->\n"
    "\n"
    "\n"
    "<!-- ================================================================\n"
    "     FLOATING ELEMENTS\n"
    "================================================================ -->\n"
    "\n"
    "<!-- Toast notification -->\n"
    "<div id=\"toast\" class=\"window\">\n"
    "  <div id=\"toast_icon\"></div>\n"
    "  <div id=\"toast_body\">\n"
    "    <div id=\"toast_title\">Peer connected</div>\n"
    "    <div id=\"toast_msg\">Tokyo Edge-1 joined via ChaCha20-PQC</div>\n"
    "  </div>\n"
    "  <div id=\"toast_close\" data-action=\"hide_toast\"></div>\n"
    "</div>\n"
    "\n"
    "<!-- Info floating window -->\n"
    "<div id=\"info_win\" class=\"window\">\n"
    "  <div id=\"info_close\" data-action=\"hide_info\"></div>\n"
    "  <div id=\"info_icon\"></div>\n"
    "  <div id=\"info_title\">All Systems Nominal</div>\n"
    "  <div id=\"info_msg\">Vespera mesh healthy. 14 of 16 peers reachable. PQC key rotation up to date.</div>\n"
    "  <div id=\"info_link\">View detailed report &rarr;</div>\n"
    "</div>\n"
    "\n"
    "<!-- Dock -->\n"
    "<div id=\"dock\" class=\"window\">\n"
    "  <div class=\"dock_icon\" style=\"background:linear-gradient(135deg,#6366f1,#4338ca)\">&#9638;</div>\n"
    "  <div class=\"dock_icon\" style=\"background:linear-gradient(135deg,#a855f7,#7c3aed)\">&#8961;</div>\n"
    "  <div class=\"dock_icon\" style=\"background:linear-gradient(135deg,#22d3ee,#0891b2)\">P</div>\n"
    "  <div class=\"dock_icon\" style=\"background:linear-gradient(135deg,#34d399,#059669)\">&#8801;</div>\n"
    "  <div class=\"dock_icon\" style=\"background:linear-gradient(135deg,#f43f5e,#be123c)\">&#8859;</div>\n"
    "</div>\n"
    "\n"
    "<!-- Modal overlay -->\n"
    "<div id=\"modal_overlay\" class=\"overlay hidden\">\n"
    "  <div id=\"modal_dialog\">\n"
    "    <div id=\"modal_icon\"></div>\n"
    "    <div id=\"modal_title\">Disconnect all peers?</div>\n"
    "    <div id=\"modal_msg\">This will terminate all active tunnels and rotate session keys. Peers will need to reconnect. This action cannot be undone.</div>\n"
    "    <div class=\"modal_btn confirm\" data-action=\"modal_confirm\">Disconnect &amp; Rotate Keys</div>\n"
    "    <div class=\"modal_btn cancel\"  data-action=\"modal_cancel\">Cancel</div>\n"
    "  </div>\n"
    "</div>\n"
    "\n"
    "<script>\n"
    "// Tab switching\n"
    "document.querySelectorAll('.nav_item[data-tab]').forEach(function(item) {\n"
    "  item.addEventListener('click', function() {\n"
    "    var tab = this.getAttribute('data-tab');\n"
    "    document.querySelectorAll('.nav_item').forEach(function(n){ n.classList.remove('active'); });\n"
    "    document.querySelectorAll('.tab_panel').forEach(function(p){ p.classList.remove('active'); });\n"
    "    this.classList.add('active');\n"
    "    var panel = document.getElementById('tab_' + tab);\n"
    "    if (panel) panel.classList.add('active');\n"
    "  });\n"
    "});\n"
    "\n"
    "// Toggle\n"
    "document.querySelectorAll('.toggle').forEach(function(t) {\n"
    "  t.addEventListener('click', function(){ this.classList.toggle('on'); });\n"
    "});\n"
    "\n"
    "// Checkbox\n"
    "document.querySelectorAll('.checkbox').forEach(function(c) {\n"
    "  c.addEventListener('click', function(){ this.classList.toggle('checked'); });\n"
    "});\n"
    "\n"
    "// Dropdown\n"
    "var combo = document.getElementById('theme_select_box');\n"
    "var panel = document.getElementById('select_panel');\n"
    "if (combo && panel) {\n"
    "  combo.addEventListener('click', function(e) {\n"
    "    e.stopPropagation();\n"
    "    panel.classList.toggle('hidden');\n"
    "  });\n"
    "  panel.querySelectorAll('.select_option').forEach(function(opt) {\n"
    "    opt.addEventListener('click', function() {\n"
    "      combo.textContent = this.textContent + ' ▾';\n"
    "      panel.classList.add('hidden');\n"
    "    });\n"
    "  });\n"
    "  document.addEventListener('click', function(){ panel.classList.add('hidden'); });\n"
    "}\n"
    "\n"
    "// Modal\n"
    "document.addEventListener('click', function(e) {\n"
    "  var action = e.target.getAttribute('data-action');\n"
    "  if (!action) return;\n"
    "  var overlay = document.getElementById('modal_overlay');\n"
    "  if (action === 'modal')         { if(overlay) overlay.classList.remove('hidden'); }\n"
    "  if (action === 'modal_confirm') { if(overlay) overlay.classList.add('hidden'); }\n"
    "  if (action === 'modal_cancel')  { if(overlay) overlay.classList.add('hidden'); }\n"
    "  if (action === 'hide_toast')    { var t=document.getElementById('toast');    if(t) t.style.display='none'; }\n"
    "  if (action === 'hide_info')     { var i=document.getElementById('info_win'); if(i) i.style.display='none'; }\n"
    "});\n"
    "\n"
    "// Tool button group\n"
    "document.querySelectorAll('.tool_btn[data-group]').forEach(function(btn) {\n"
    "  btn.addEventListener('click', function() {\n"
    "    var group = this.getAttribute('data-group');\n"
    "    document.querySelectorAll('.tool_btn[data-group=\"'+group+'\"]').forEach(function(b){ b.classList.remove('active'); });\n"
    "    this.classList.add('active');\n"
    "  });\n"
    "});\n"
    "</script>\n"
    "\n"
    "</body>\n"
    "</html>\n"
