    "/* ═══════════════════════════════════════════\n"
    "   Vespera GUI Engine — Aurora Noir\n"
    "   1024 × 700 canvas, tab-based layout\n"
    "═══════════════════════════════════════════ */\n"
    "\n"
    ":root {\n"
    "  --bg:         #06060f;\n"
    "  --surface:    rgba(255,255,255,0.042);\n"
    "  --surface-hi: rgba(255,255,255,0.075);\n"
    "  --border:     rgba(255,255,255,0.072);\n"
    "  --border-hi:  rgba(255,255,255,0.14);\n"
    "  --indigo:     #6366f1;\n"
    "  --violet:     #a855f7;\n"
    "  --cyan:       #22d3ee;\n"
    "  --emerald:    #34d399;\n"
    "  --amber:      #fbbf24;\n"
    "  --pink:       #ec4899;\n"
    "  --text-1:     rgba(255,255,255,0.92);\n"
    "  --text-2:     rgba(255,255,255,0.52);\n"
    "  --text-3:     rgba(255,255,255,0.26);\n"
    "  --r-xl: 20px; --r-lg: 14px; --r-md: 10px; --r-sm: 7px;\n"
    "  --font:   'Inter', -apple-system, sans-serif;\n"
    "  --font-d: 'Space Grotesk', 'Inter', sans-serif;\n"
    "  --blur:   blur(28px) saturate(1.5);\n"
    "}\n"
    "\n"
    "*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }\n"
    "html, body {\n"
    "  width: 100%; height: 100%;\n"
    "  background: var(--bg);\n"
    "  font-family: var(--font);\n"
    "  -webkit-font-smoothing: antialiased;\n"
    "  overflow: hidden;\n"
    "}\n"
    "body { min-width: 1024px; min-height: 700px; position: relative; }\n"
    "\n"
    "/* Aurora background */\n"
    "body::before {\n"
    "  content: '';\n"
    "  position: fixed; inset: 0; pointer-events: none; z-index: 0;\n"
    "  background:\n"
    "    radial-gradient(ellipse 560px 360px at 16% 14%, rgba(99,102,241,.17) 0%, transparent 68%),\n"
    "    radial-gradient(ellipse 420px 300px at 84% 82%, rgba(34,211,238,.12) 0%, transparent 68%),\n"
    "    radial-gradient(ellipse 360px 260px at 62% 38%, rgba(168,85,247,.09) 0%, transparent 68%);\n"
    "  animation: aurora 20s ease-in-out infinite alternate;\n"
    "}\n"
    "@keyframes aurora {\n"
    "  0%   { transform: scale(1)    translate(0,0); }\n"
    "  50%  { transform: scale(1.04) translate(14px,-8px); }\n"
    "  100% { transform: scale(1)    translate(-6px,6px); }\n"
    "}\n"
    "\n"
    ".window   { position: absolute; border-radius: var(--r-xl); }\n"
    ".overlay  { position: absolute; border-radius: 0 !important; }\n"
    ".hidden   { display: none !important; }\n"
    "\n"
    "/* ══════════════════════════════════════════\n"
    "   MAIN WINDOW  740 × 600\n"
    "══════════════════════════════════════════ */\n"
    "#main_win {\n"
    "  width: 740px; height: 600px;\n"
    "  left: 50%; top: 50%;\n"
    "  transform: translate(-50%, -50%);\n"
    "  z-index: 10; overflow: hidden;\n"
    "  backdrop-filter: var(--blur);\n"
    "  -webkit-backdrop-filter: var(--blur);\n"
    "  background: linear-gradient(140deg, rgba(255,255,255,.062) 0%, rgba(255,255,255,.022) 100%);\n"
    "  border: 1px solid rgba(99,102,241,.22);\n"
    "  box-shadow:\n"
    "    0 1px 0 rgba(255,255,255,.07) inset,\n"
    "    0 28px 80px rgba(0,0,0,.65),\n"
    "    0 0 50px rgba(99,102,241,.08);\n"
    "}\n"
    "\n"
    "/* Title bar */\n"
    "#title_bar {\n"
    "  position: absolute; left: 0; top: 0; width: 100%; height: 42px;\n"
    "  background: rgba(255,255,255,.022);\n"
    "  border-bottom: 1px solid var(--border);\n"
    "  display: flex; align-items: center;\n"
    "}\n"
    ".title_drag { position: absolute; inset: 0; cursor: move; }\n"
    ".btn_os {\n"
    "  position: absolute; width: 12px; height: 12px; border-radius: 50%;\n"
    "  top: 15px; cursor: pointer; z-index: 5;\n"
    "  transition: opacity .15s, transform .15s;\n"
    "}\n"
    ".btn_os:hover { opacity:.8; transform:scale(1.1); }\n"
    "#btn_close { background:#ff5f57; left:16px; box-shadow:0 0 7px rgba(255,95,87,.5); }\n"
    "#btn_min   { background:#febc2e; left:34px; box-shadow:0 0 7px rgba(254,188,46,.4); }\n"
    "#btn_max   { background:#28c840; left:52px; box-shadow:0 0 7px rgba(40,200,64,.4); }\n"
    "#title_text {\n"
    "  position: absolute; inset: 0;\n"
    "  display: flex; align-items: center; justify-content: center;\n"
    "  color: var(--text-2); font-size: 11.5px; font-weight: 500;\n"
    "  letter-spacing: .07em; text-transform: uppercase; pointer-events: none;\n"
    "  text-shadow: 0 0 12px rgba(129,140,248,.45);\n"
    "}\n"
    "\n"
    "/* ── Sidebar ── */\n"
    "#sidebar {\n"
    "  position: absolute; left: 0; top: 42px;\n"
    "  width: 192px; height: calc(100% - 42px);\n"
    "  background: rgba(5,5,16,.72);\n"
    "  border-right: 1px solid var(--border);\n"
    "  display: flex; flex-direction: column; align-items: center;\n"
    "  padding: 22px 0 16px;\n"
    "  overflow: hidden;\n"
    "}\n"
    "#sidebar_avatar {\n"
    "  width: 48px; height: 48px; border-radius: 50%; flex-shrink: 0;\n"
    "  background: radial-gradient(circle at 32% 28%, #a5b4fc 0%, var(--indigo) 38%, var(--violet) 72%, #312e81 100%);\n"
    "  box-shadow: 0 0 0 2px rgba(99,102,241,.35), 0 0 18px rgba(99,102,241,.4), inset 0 -6px 12px rgba(0,0,0,.35);\n"
    "  animation: hue-spin 14s linear infinite;\n"
    "}\n"
    "@keyframes hue-spin { to { filter: hue-rotate(360deg); } }\n"
    "#sidebar_username {\n"
    "  margin-top: 11px; color: var(--text-1);\n"
    "  font-family: var(--font-d); font-size: 13px; font-weight: 700; letter-spacing: -.01em;\n"
    "}\n"
    "#sidebar_role {\n"
    "  margin-top: 3px; color: var(--text-3);\n"
    "  font-size: 9px; font-weight: 700; letter-spacing: .08em; text-transform: uppercase;\n"
    "}\n"
    "#sidebar_nav {\n"
    "  margin-top: 18px; width: 100%;\n"
    "  display: flex; flex-direction: column; gap: 2px; padding: 0 10px;\n"
    "}\n"
    ".nav_item {\n"
    "  position: relative; height: 34px; border-radius: var(--r-md);\n"
    "  padding: 0 12px; display: flex; align-items: center;\n"
    "  color: var(--text-2); font-size: 12.5px; font-weight: 500;\n"
    "  cursor: pointer; transition: background .15s, color .15s;\n"
    "  user-select: none;\n"
    "}\n"
    ".nav_item:hover  { background: var(--surface-hi); color: var(--text-1); }\n"
    ".nav_item.active {\n"
    "  background: rgba(99,102,241,.18); color: #c7d2fe; font-weight: 600;\n"
    "  border: 1px solid rgba(99,102,241,.22);\n"
    "  box-shadow: inset 0 1px 0 rgba(255,255,255,.08), 0 4px 14px rgba(99,102,241,.16);\n"
    "}\n"
    ".nav_dot {\n"
    "  position: absolute; right: 12px; top: 50%; transform: translateY(-50%);\n"
    "  width: 6px; height: 6px; border-radius: 50%;\n"
    "}\n"
    ".nav_dot.green { background:#4ade80; box-shadow:0 0 7px rgba(74,222,128,.8); }\n"
    ".nav_dot.amber { background:#fbbf24; box-shadow:0 0 7px rgba(251,191,36,.7); }\n"
    "\n"
    "#sidebar_stats {\n"
    "  margin-top: auto; width: 100%; padding: 0 14px;\n"
    "  display: flex; flex-direction: column; gap: 9px;\n"
    "}\n"
    ".stat_row { display:flex; align-items:center; gap:7px; }\n"
    ".stat_key {\n"
    "  color: var(--text-3); font-size: 8.5px; font-weight: 800;\n"
    "  letter-spacing: .1em; text-transform: uppercase; width: 26px; flex-shrink: 0;\n"
    "}\n"
    ".stat_bar_wrap {\n"
    "  flex: 1; height: 3px; border-radius: 2px;\n"
    "  background: rgba(255,255,255,.07); overflow: hidden;\n"
    "}\n"
    ".stat_bar_fill {\n"
    "  height: 100%; border-radius: 2px;\n"
    "  background: linear-gradient(90deg, var(--indigo), var(--violet));\n"
    "  box-shadow: 0 0 5px rgba(99,102,241,.5);\n"
    "}\n"
    ".stat_bar_fill.mem { background: linear-gradient(90deg,#06b6d4,var(--indigo)); box-shadow:0 0 5px rgba(6,182,212,.5); }\n"
    ".stat_bar_fill.net { background: linear-gradient(90deg,var(--emerald),#059669); box-shadow:0 0 5px rgba(52,211,153,.5); }\n"
    ".stat_num {\n"
    "  color: var(--text-2); font-size: 9px; font-weight: 700;\n"
    "  width: 28px; text-align: right; flex-shrink: 0;\n"
    "}\n"
    "#sidebar_version {\n"
    "  margin-top: 14px; color: var(--text-3);\n"
    "  font-size: 8px; letter-spacing: .08em; text-transform: uppercase;\n"
    "}\n"
    "\n"
    "/* ── Content ── */\n"
    "#content {\n"
    "  position: absolute; left: 192px; top: 42px;\n"
    "  width: calc(100% - 192px); height: calc(100% - 42px);\n"
    "  overflow: hidden;\n"
    "}\n"
    ".tab_panel {\n"
    "  display: none; flex-direction: column; gap: 12px;\n"
    "  height: 100%; overflow-y: auto; overflow-x: hidden;\n"
    "  padding: 20px 22px 18px;\n"
    "  scrollbar-width: thin; scrollbar-color: rgba(99,102,241,.3) transparent;\n"
    "}\n"
    ".tab_panel.active { display: flex; }\n"
    ".tab_panel::-webkit-scrollbar { width: 4px; }\n"
    ".tab_panel::-webkit-scrollbar-thumb { background: rgba(99,102,241,.32); border-radius: 2px; }\n"
    "\n"
    ".section_title {\n"
    "  font-family: var(--font-d); font-size: 19px; font-weight: 700;\n"
    "  color: var(--text-1); letter-spacing: -.025em;\n"
    "}\n"
    ".section_desc {\n"
    "  font-size: 12px; color: var(--text-2); line-height: 1.55; margin-top: -6px;\n"
    "}\n"
    ".sep {\n"
    "  height: 1px;\n"
    "  background: linear-gradient(90deg, transparent, var(--border-hi) 25%, var(--border-hi) 75%, transparent);\n"
    "  flex-shrink: 0;\n"
    "}\n"
    "\n"
    "/* Toolbar */\n"
    "#toolbar {\n"
    "  display: flex; gap: 6px; align-items: center; flex-shrink: 0;\n"
    "}\n"
    ".tool_btn {\n"
    "  height: 32px; padding: 0 14px; border-radius: var(--r-sm);\n"
    "  background: var(--surface); border: 1px solid var(--border); color: var(--text-2);\n"
    "  box-shadow: inset 0 1px 0 rgba(255,255,255,.07), 0 2px 6px rgba(0,0,0,.35);\n"
    "  font-size: 11px; font-weight: 600; letter-spacing: .04em; text-transform: uppercase;\n"
    "  cursor: pointer; display: flex; align-items: center;\n"
    "  transition: background .13s, color .13s, border-color .13s, transform .1s;\n"
    "  user-select: none;\n"
    "}\n"
    ".tool_btn:hover { background: var(--surface-hi); color: var(--text-1); border-color: var(--border-hi); transform: translateY(-1px); }\n"
    ".tool_btn:active { transform: translateY(0); }\n"
    ".tool_btn.active {\n"
    "  background: rgba(99,102,241,.28); color: #c7d2fe;\n"
    "  border-color: rgba(99,102,241,.35); box-shadow: 0 0 12px rgba(99,102,241,.2);\n"
    "}\n"
    "#apply_btn {\n"
    "  margin-left: auto; height: 32px; padding: 0 18px; border-radius: 16px;\n"
    "  background: linear-gradient(135deg, var(--indigo), var(--violet)); color: #fff;\n"
    "  font-size: 11px; font-weight: 700; letter-spacing: .05em; text-transform: uppercase;\n"
    "  cursor: pointer; display: flex; align-items: center;\n"
    "  box-shadow: inset 0 1px 0 rgba(255,255,255,.28), 0 4px 18px rgba(99,102,241,.45);\n"
    "  transition: box-shadow .15s, transform .12s; user-select: none;\n"
    "  text-shadow: 0 1px 2px rgba(0,0,0,.35);\n"
    "}\n"
    "#apply_btn:hover { box-shadow: 0 6px 26px rgba(99,102,241,.6); transform: translateY(-1px); }\n"
    "#apply_btn:active { transform: translateY(0); }\n"
    "\n"
    "/* Setting rows */\n"
    ".setting_row {\n"
    "  display: flex; align-items: center;\n"
    "  min-height: 38px; border-radius: var(--r-md);\n"
    "  padding: 0 12px; background: var(--surface); border: 1px solid var(--border);\n"
    "  flex-shrink: 0;\n"
    "  box-shadow: inset 0 1px 0 rgba(255,255,255,.04);\n"
    "}\n"
    ".setting_row.col { flex-direction: column; align-items: flex-start; height: auto; padding: 10px 12px; gap: 8px; }\n"
    ".setting_label { font-size: 12.5px; color: var(--text-1); font-weight: 400; flex: 1; }\n"
    ".setting_val   { color: var(--text-3); font-size: 11px; margin-left: 5px; }\n"
    "\n"
    "/* Toggle */\n"
    ".toggle {\n"
    "  width: 40px; height: 22px; border-radius: 11px;\n"
    "  background: rgba(255,255,255,.1); border: 1px solid var(--border-hi);\n"
    "  cursor: pointer; position: relative; flex-shrink: 0;\n"
    "  transition: background .2s, border-color .2s;\n"
    "}\n"
    ".toggle.on {\n"
    "  background: rgba(99,102,241,.55); border-color: rgba(99,102,241,.4);\n"
    "  box-shadow: 0 0 12px rgba(99,102,241,.35), inset 0 1px 3px rgba(0,0,0,.3);\n"
    "}\n"
    ".toggle_knob {\n"
    "  position: absolute; width: 16px; height: 16px; border-radius: 50%;\n"
    "  background: #fff; top: 3px; left: 3px;\n"
    "  box-shadow: 0 2px 6px rgba(0,0,0,.35);\n"
    "  transition: left .2s cubic-bezier(.4,0,.2,1);\n"
    "}\n"
    ".toggle.on .toggle_knob { left: 21px; }\n"
    "\n"
    "/* Checkbox */\n"
    ".checkbox {\n"
    "  width: 17px; height: 17px; border-radius: 5px; flex-shrink: 0;\n"
    "  background: transparent; border: 1.5px solid var(--border-hi); cursor: pointer;\n"
    "  transition: background .14s, border-color .14s, box-shadow .14s;\n"
    "}\n"
    ".checkbox.checked { background: var(--indigo); border-color: transparent; box-shadow: 0 0 9px rgba(99,102,241,.45); }\n"
    "\n"
    "/* Dropdown */\n"
    "#theme_combo { position: relative; }\n"
    "#theme_select_box {\n"
    "  height: 28px; padding: 0 10px; border-radius: var(--r-sm);\n"
    "  background: rgba(255,255,255,.06); border: 1px solid var(--border-hi);\n"
    "  color: var(--text-1); font-size: 12px; font-weight: 500; cursor: pointer;\n"
    "  display: flex; align-items: center; white-space: nowrap;\n"
    "  transition: border-color .12s, background .12s;\n"
    "}\n"
    "#theme_select_box:hover { border-color: rgba(99,102,241,.4); background: var(--surface-hi); }\n"
    "#select_panel {\n"
    "  position: absolute; right: 0; top: 32px; width: 138px;\n"
    "  border-radius: var(--r-md); background: rgba(10,10,24,.97);\n"
    "  border: 1px solid var(--border-hi); box-shadow: 0 14px 44px rgba(0,0,0,.65);\n"
    "  z-index: 200; overflow: hidden; backdrop-filter: blur(20px);\n"
    "}\n"
    ".select_option {\n"
    "  height: 30px; padding: 0 12px; display: flex; align-items: center;\n"
    "  color: var(--text-2); font-size: 12px; cursor: pointer;\n"
    "  transition: background .1s, color .1s;\n"
    "}\n"
    ".select_option:hover { background: rgba(99,102,241,.16); color: #c7d2fe; }\n"
    "\n"
    "/* Slider */\n"
    "#slider_track {\n"
    "  position: relative; width: 100%; height: 4px; border-radius: 3px;\n"
    "  background: rgba(255,255,255,.08);\n"
    "}\n"
    "#slider_fill {\n"
    "  position: absolute; left: 0; top: 0; width: 70%; height: 100%; border-radius: 3px;\n"
    "  background: linear-gradient(90deg, var(--indigo), var(--violet));\n"
    "  box-shadow: 0 0 8px rgba(99,102,241,.5);\n"
    "}\n"
    "#slider_thumb {\n"
    "  position: absolute; top: 50%; left: 70%; transform: translate(-50%,-50%);\n"
    "  width: 15px; height: 15px; border-radius: 50%;\n"
    "  background: #fff; border: 2px solid var(--indigo);\n"
    "  box-shadow: 0 0 10px rgba(99,102,241,.5); cursor: pointer;\n"
    "  transition: transform .1s;\n"
    "}\n"
    "#slider_thumb:hover { transform: translate(-50%,-50%) scale(1.25); }\n"
    ".slider_track2 {\n"
    "  position: relative; width: 140px; height: 4px; border-radius: 3px;\n"
    "  background: rgba(255,255,255,.08); flex-shrink: 0;\n"
    "}\n"
    ".slider_fill2 {\n"
    "  position: absolute; left: 0; top: 0; height: 100%; border-radius: 3px;\n"
    "  background: linear-gradient(90deg, var(--indigo), var(--violet));\n"
    "  box-shadow: 0 0 8px rgba(99,102,241,.5);\n"
    "}\n"
    ".slider_thumb2 {\n"
    "  position: absolute; top: 50%; transform: translate(-50%,-50%);\n"
    "  width: 14px; height: 14px; border-radius: 50%;\n"
    "  background: #fff; border: 2px solid var(--indigo);\n"
    "  box-shadow: 0 0 8px rgba(99,102,241,.5); cursor: pointer;\n"
    "}\n"
    "\n"
    "/* Demo label */\n"
    ".demo_label {\n"
    "  font-size: 9.5px; font-weight: 700; letter-spacing: .08em; text-transform: uppercase;\n"
    "  color: var(--text-3); flex-shrink: 0;\n"
    "}\n"
    "\n"
    "/* Chips */\n"
    "#chip_row { display: flex; flex-wrap: wrap; gap: 6px; flex-shrink: 0; }\n"
    ".chip {\n"
    "  height: 25px; padding: 0 9px; border-radius: 12.5px;\n"
    "  background: var(--surface); border: 1px solid var(--border);\n"
    "  color: var(--text-2); font-size: 10px; font-weight: 600;\n"
    "  letter-spacing: .04em; text-transform: uppercase;\n"
    "  cursor: pointer; display: flex; align-items: center;\n"
    "  transition: background .13s, color .13s, border-color .13s;\n"
    "}\n"
    ".chip:hover { background: var(--surface-hi); color: var(--text-1); border-color: var(--border-hi); }\n"
    ".chip:nth-child(3n+2) { border-color: rgba(34,211,238,.25); color: rgba(165,243,252,.75); }\n"
    ".chip:nth-child(3n)   { border-color: rgba(168,85,247,.25); color: rgba(216,180,254,.75); }\n"
    ".chip:last-child      { border-color: rgba(236,72,153,.3);  color: rgba(251,207,232,.8); }\n"
    ".chip.accent { background: rgba(99,102,241,.28); color: #c7d2fe; border-color: rgba(99,102,241,.35); box-shadow: 0 0 10px rgba(99,102,241,.18); }\n"
    "\n"
    "/* Hscroll */\n"
    "#hscroll_panel {\n"
    "  border-radius: var(--r-sm); background: var(--surface); border: 1px solid var(--border);\n"
    "  height: 36px; padding: 0 6px;\n"
    "  overflow-x: auto; overflow-y: hidden; scrollbar-width: none; flex-shrink: 0;\n"
    "}\n"
    "#hscroll_panel::-webkit-scrollbar { display: none; }\n"
    "#hscroll_inner {\n"
    "  display: flex; gap: 5px; align-items: center; height: 100%; width: max-content;\n"
    "}\n"
    ".hscroll_chip {\n"
    "  height: 24px; padding: 0 11px; border-radius: 6px; flex-shrink: 0;\n"
    "  background: rgba(99,102,241,.2); border: 1px solid rgba(99,102,241,.2);\n"
    "  color: #c7d2fe; font-size: 9.5px; font-weight: 700; letter-spacing: .04em;\n"
    "  display: flex; align-items: center;\n"
    "}\n"
    ".hscroll_chip.pinned {\n"
    "  background: rgba(236,72,153,.28); border-color: rgba(236,72,153,.28); color: #fce7f3;\n"
    "  box-shadow: 0 0 10px rgba(236,72,153,.22);\n"
    "}\n"
    "\n"
    "/* Progress */\n"
    "#progress_track {\n"
    "  height: 3px; border-radius: 2px; background: rgba(255,255,255,.07);\n"
    "  overflow: hidden; flex-shrink: 0;\n"
    "}\n"
    "#progress_fill {\n"
    "  height: 100%; border-radius: 2px; width: 0;\n"
    "  background: linear-gradient(90deg, var(--cyan), var(--indigo));\n"
    "  box-shadow: 0 0 7px rgba(34,211,238,.6);\n"
    "  animation: prog 2.8s ease-in-out infinite alternate;\n"
    "}\n"
    "@keyframes prog { to { width: 75%; } }\n"
    "\n"
    "/* Activity */\n"
    "#activity_panel {\n"
    "  border-radius: var(--r-md); background: var(--surface); border: 1px solid var(--border);\n"
    "  max-height: 100px; overflow-y: auto; flex-shrink: 0;\n"
    "  scrollbar-width: thin; scrollbar-color: rgba(99,102,241,.3) transparent;\n"
    "}\n"
    ".activity_sticky {\n"
    "  position: sticky; top: 0; background: rgba(6,6,18,.96);\n"
    "  padding: 4px 12px; color: var(--text-3); font-size: 9px; font-weight: 800;\n"
    "  letter-spacing: .09em; text-transform: uppercase;\n"
    "  border-bottom: 1px solid var(--border);\n"
    "}\n"
    ".activity_sticky_bottom {\n"
    "  position: sticky; bottom: 0;\n"
    "  background: linear-gradient(90deg, rgba(99,102,241,.22), rgba(168,85,247,.16));\n"
    "  padding: 4px 12px; text-align: center; color: rgba(199,210,254,.55);\n"
    "  font-size: 9px; font-weight: 700; letter-spacing: .06em; text-transform: uppercase;\n"
    "  border-top: 1px solid rgba(99,102,241,.14);\n"
    "}\n"
    ".activity_line {\n"
    "  padding: 5px 12px; color: var(--text-2); font-size: 11px;\n"
    "  border-bottom: 1px solid rgba(255,255,255,.03);\n"
    "}\n"
    ".activity_line:nth-child(even) { background: rgba(255,255,255,.025); }\n"
    ".activity_line:last-child { border-bottom: none; }\n"
    "\n"
    "/* Metrics */\n"
    "#metrics_row { display: flex; gap: 6px; flex-shrink: 0; }\n"
    ".metric_pill {\n"
    "  flex: 1; border-radius: var(--r-md); background: var(--surface);\n"
    "  border: 1px solid var(--border); padding: 8px 12px;\n"
    "  display: flex; flex-direction: column; gap: 2px; position: relative;\n"
    "}\n"
    ".metric_pill.online  { border-color:rgba(74,222,128,.22);  background:rgba(74,222,128,.06); }\n"
    ".metric_pill.peers   { border-color:rgba(99,102,241,.22);  background:rgba(99,102,241,.06); }\n"
    ".metric_pill.latency { border-color:rgba(251,191,36,.22);  background:rgba(251,191,36,.06); }\n"
    ".metric_pill.badges  { display:flex; flex-direction:row; align-items:center; gap:5px; flex:1.5; }\n"
    ".mp_val   { font-family:var(--font-d); font-size:14px; font-weight:700; letter-spacing:-.02em; }\n"
    ".mp_label { font-size:7.5px; font-weight:800; letter-spacing:.09em; text-transform:uppercase; opacity:.5; }\n"
    ".metric_pill.online  .mp_val, .metric_pill.online  .mp_label { color:#4ade80; }\n"
    ".metric_pill.peers   .mp_val, .metric_pill.peers   .mp_label { color:#a78bfa; }\n"
    ".metric_pill.latency .mp_val, .metric_pill.latency .mp_label { color:#fbbf24; }\n"
    "\n"
    ".badge {\n"
    "  height: 19px; padding: 0 8px; border-radius: 9px;\n"
    "  font-size: 9px; font-weight: 800; letter-spacing: .05em; text-transform: uppercase;\n"
    "  display: flex; align-items: center;\n"
    "}\n"
    ".badge.green { background:rgba(74,222,128,.14);  color:#4ade80; border:1px solid rgba(74,222,128,.25); }\n"
    ".badge.amber { background:rgba(251,191,36,.14);  color:#fbbf24; border:1px solid rgba(251,191,36,.25); }\n"
    ".badge.red   { background:rgba(248,113,113,.14); color:#f87171; border:1px solid rgba(248,113,113,.25); }\n"
    "\n"
    "#status_text {\n"
    "  color: var(--text-3); font-size: 9.5px; text-align: right;\n"
    "  letter-spacing: .05em; text-transform: uppercase; padding-top: 4px; flex-shrink: 0;\n"
    "}\n"
    "\n"
    "/* Swatches */\n"
    ".swatch {\n"
    "  width: 20px; height: 20px; border-radius: 50%; cursor: pointer;\n"
    "  border: 1.5px solid rgba(255,255,255,.15);\n"
    "  transition: transform .12s, box-shadow .12s;\n"
    "}\n"
    ".swatch:hover { transform: scale(1.18); }\n"
    ".swatch.sel   { border-color: rgba(255,255,255,.7); border-width: 2px; }\n"
    "\n"
    "/* Tab pill bar (Appearance) */\n"
    ".tab_pill_bar {\n"
    "  display: flex; gap: 3px; padding: 3px;\n"
    "  background: var(--surface); border: 1px solid var(--border);\n"
    "  border-radius: 16px; width: fit-content; flex-shrink: 0;\n"
    "}\n"
    ".tab_pill {\n"
    "  height: 26px; padding: 0 14px; border-radius: 13px;\n"
    "  color: var(--text-3); font-size: 10px; font-weight: 700;\n"
    "  letter-spacing: .04em; text-transform: uppercase;\n"
    "  cursor: pointer; display: flex; align-items: center;\n"
    "  transition: background .14s, color .14s; user-select: none;\n"
    "}\n"
    ".tab_pill:hover { color: var(--text-2); }\n"
    ".tab_pill.active {\n"
    "  background: linear-gradient(135deg, rgba(99,102,241,.5), rgba(139,92,246,.4));\n"
    "  color: #c7d2fe; box-shadow: 0 2px 8px rgba(99,102,241,.3);\n"
    "}\n"
    "\n"
    "/* Keyboard card */\n"
    ".kbd_card {\n"
    "  border-radius: var(--r-md); background: var(--surface); border: 1px solid var(--border);\n"
    "  padding: 6px 12px; display: flex; flex-direction: column; gap: 0; flex-shrink: 0;\n"
    "}\n"
    ".kbd_row {\n"
    "  display: flex; align-items: center; justify-content: space-between;\n"
    "  height: 28px; border-bottom: 1px solid rgba(255,255,255,.04);\n"
    "}\n"
    ".kbd_row:last-child { border-bottom: none; }\n"
    ".kbd_label { color: var(--text-2); font-size: 11px; }\n"
    ".kbd_key {\n"
    "  background: rgba(255,255,255,.06); border: 1px solid var(--border-hi);\n"
    "  border-radius: 5px; padding: 0 6px; height: 18px;\n"
    "  box-shadow: inset 0 -2px 0 rgba(0,0,0,.35), 0 1px 0 rgba(255,255,255,.05);\n"
    "  display: flex; align-items: center;\n"
    "  color: var(--text-2); font-size: 10px; font-weight: 700; letter-spacing: .03em;\n"
    "  font-family: var(--font-d);\n"
    "}\n"
    "\n"
    "/* ════════════════════════════════════\n"
    "   LAYOUT DEMO CARDS\n"
    "════════════════════════════════════ */\n"
    ".demo_card {\n"
    "  background: var(--surface); border: 1px solid var(--border);\n"
    "  border-radius: var(--r-lg); padding: 12px 14px;\n"
    "  display: flex; flex-direction: column; gap: 10px; flex-shrink: 0;\n"
    "}\n"
    ".demo_card_head {\n"
    "  display: flex; align-items: center; gap: 8px;\n"
    "}\n"
    ".demo_tag {\n"
    "  height: 18px; padding: 0 8px; border-radius: 9px; flex-shrink: 0;\n"
    "  font-size: 9px; font-weight: 800; letter-spacing: .06em; text-transform: uppercase;\n"
    "  display: flex; align-items: center;\n"
    "  background: rgba(99,102,241,.25); color: #c7d2fe; border: 1px solid rgba(99,102,241,.3);\n"
    "}\n"
    ".demo_tag.indigo { background:rgba(99,102,241,.25); color:#c7d2fe; border-color:rgba(99,102,241,.3); }\n"
    ".demo_tag.violet { background:rgba(168,85,247,.22);  color:#d8b4fe; border-color:rgba(168,85,247,.28); }\n"
    ".demo_tag.cyan   { background:rgba(34,211,238,.18);  color:#a5f3fc; border-color:rgba(34,211,238,.26); }\n"
    ".demo_tag.emerald{ background:rgba(52,211,153,.18);  color:#a7f3d0; border-color:rgba(52,211,153,.26); }\n"
    ".demo_tag.amber  { background:rgba(251,191,36,.18);  color:#fde68a; border-color:rgba(251,191,36,.26); }\n"
    ".demo_tag.pink   { background:rgba(236,72,153,.2);   color:#fbcfe8; border-color:rgba(236,72,153,.28); }\n"
    ".demo_caption {\n"
    "  color: var(--text-3); font-size: 10px; font-weight: 500; letter-spacing: .02em;\n"
    "  font-family: monospace; font-size: 10.5px;\n"
    "}\n"
    "\n"
    "/* — Flex shrink/grow — */\n"
    ".demo_flex_shrink {\n"
    "  display: flex; gap: 5px; align-items: center; height: 32px;\n"
    "}\n"
    ".fs_item {\n"
    "  background: rgba(99,102,241,.35); border: 1px solid rgba(99,102,241,.3);\n"
    "  color: #c7d2fe; border-radius: var(--r-sm); height: 28px;\n"
    "  display: flex; align-items: center; justify-content: center;\n"
    "  font-size: 10px; font-weight: 700; min-width: 0;\n"
    "  flex: 0 0 auto; padding: 0 10px;\n"
    "}\n"
    ".fs_item.grow    { flex: 1 1 auto; background: rgba(52,211,153,.25); border-color:rgba(52,211,153,.3); color:#a7f3d0; }\n"
    ".fs_item.shrink  { flex: 1 1 140px; min-width: 0; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; background: rgba(236,72,153,.22); border-color:rgba(236,72,153,.28); color:#fbcfe8; }\n"
    "\n"
    "/* — Grid row dense — */\n"
    ".demo_grid_dense {\n"
    "  display: grid;\n"
    "  grid-template-columns: repeat(4, 1fr);\n"
    "  grid-auto-rows: 26px;\n"
    "  grid-auto-flow: row dense;\n"
    "  gap: 4px;\n"
    "}\n"
    ".gc {\n"
    "  background: rgba(99,102,241,.3); border: 1px solid rgba(99,102,241,.25);\n"
    "  color: #c7d2fe; border-radius: 5px;\n"
    "  display: flex; align-items: center; justify-content: center;\n"
    "  font-size: 10px; font-weight: 700;\n"
    "}\n"
    ".gc.wide { grid-column: span 2; background: rgba(168,85,247,.32); border-color:rgba(168,85,247,.28); color:#d8b4fe; }\n"
    "\n"
    "/* — Grid col dense — */\n"
    ".demo_grid_col_dense {\n"
    "  display: grid;\n"
    "  grid-template-rows: repeat(2, 26px);\n"
    "  grid-template-columns: repeat(4, 1fr);\n"
    "  grid-auto-flow: column dense;\n"
    "  gap: 4px;\n"
    "}\n"
    ".gcc {\n"
    "  background: rgba(139,92,246,.32); border: 1px solid rgba(139,92,246,.28);\n"
    "  color: #d8b4fe; border-radius: 5px;\n"
    "  display: flex; align-items: center; justify-content: center;\n"
    "  font-size: 10px; font-weight: 700;\n"
    "}\n"
    ".gcc.tall { grid-row: span 2; background: rgba(236,72,153,.28); border-color:rgba(236,72,153,.26); color:#fbcfe8; }\n"
    ".gcc.b    { background: rgba(245,158,11,.28); border-color:rgba(245,158,11,.26); color:#fde68a; }\n"
    "\n"
    "/* — Align-self — */\n"
    ".demo_align_self {\n"
    "  display: flex; gap: 5px; align-items: stretch; height: 56px;\n"
    "}\n"
    ".as_item {\n"
    "  flex: 1; border-radius: var(--r-sm);\n"
    "  display: flex; align-items: center; justify-content: center;\n"
    "  font-size: 9px; font-weight: 700; letter-spacing: .03em; text-transform: uppercase;\n"
    "  border: 1px solid rgba(34,211,238,.25); background: rgba(34,211,238,.12); color: #a5f3fc;\n"
    "}\n"
    ".as_item.start    { align-self: flex-start;  height: 28px; }\n"
    ".as_item.center   { align-self: center;       height: 28px; }\n"
    ".as_item.end      { align-self: flex-end;     height: 28px; }\n"
    ".as_item.stretch  { align-self: stretch; }\n"
    ".as_item.baseline { align-self: baseline;     height: 36px; }\n"
    "\n"
    "/* — Grid template areas — */\n"
    ".demo_areas {\n"
    "  display: grid;\n"
    "  grid-template-areas:\n"
    "    \"header  header\"\n"
    "    \"sidebar main\"\n"
    "    \"footer  footer\";\n"
    "  grid-template-columns: 72px 1fr;\n"
    "  grid-template-rows: 22px 34px 22px;\n"
    "  gap: 4px;\n"
    "}\n"
    ".area {\n"
    "  display: flex; align-items: center; justify-content: center;\n"
    "  border-radius: 5px; font-size: 9.5px; font-weight: 700;\n"
    "  letter-spacing: .03em; text-transform: uppercase;\n"
    "}\n"
    ".area.header  { grid-area: header;  background:rgba(99,102,241,.3);  border:1px solid rgba(99,102,241,.28);  color:#c7d2fe; }\n"
    ".area.sidebar { grid-area: sidebar; background:rgba(168,85,247,.26); border:1px solid rgba(168,85,247,.26);  color:#d8b4fe; }\n"
    ".area.main    { grid-area: main;    background:rgba(52,211,153,.18);  border:1px solid rgba(52,211,153,.22);  color:#a7f3d0; }\n"
    ".area.footer  { grid-area: footer;  background:rgba(251,191,36,.18);  border:1px solid rgba(251,191,36,.22);  color:#fde68a; }\n"
    "\n"
    "/* — min/max/fr sizing — */\n"
    ".demo_sizing {\n"
    "  display: grid;\n"
    "  grid-template-columns: min-content max-content 1fr;\n"
    "  gap: 4px; height: 30px;\n"
    "}\n"
    ".sz_cell {\n"
    "  border-radius: 5px; display: flex; align-items: center; justify-content: center;\n"
    "  font-size: 9.5px; font-weight: 700; letter-spacing: .03em; white-space: nowrap;\n"
    "  overflow: hidden; text-overflow: ellipsis; padding: 0 8px;\n"
    "}\n"
    ".sz_cell.min { background:rgba(236,72,153,.24); border:1px solid rgba(236,72,153,.26); color:#fbcfe8; }\n"
    ".sz_cell.max { background:rgba(245,158,11,.22);  border:1px solid rgba(245,158,11,.24);  color:#fde68a; }\n"
    ".sz_cell.fr  { background:rgba(99,102,241,.28); border:1px solid rgba(99,102,241,.28); color:#c7d2fe; }\n"
    "\n"
    "/* — Clip + ellipsis — */\n"
    ".demo_clip_row { display: flex; gap: 8px; }\n"
    ".clip_box {\n"
    "  flex: 1; background: var(--surface-hi); border: 1px solid var(--border-hi);\n"
    "  border-radius: var(--r-sm); padding: 8px 10px;\n"
    "  overflow: hidden;\n"
    "}\n"
    ".clip_box span {\n"
    "  display: block; white-space: nowrap; overflow: hidden; text-overflow: ellipsis;\n"
    "  color: var(--text-2); font-size: 11px; line-height: 1.5;\n"
    "}\n"
    ".clip_box.clamp span {\n"
    "  white-space: normal;\n"
    "  display: -webkit-box; -webkit-box-orient: vertical; -webkit-line-clamp: 2;\n"
    "}\n"
    "\n"
    "/* ══════════════════════════════════════════\n"
    "   TOAST\n"
    "══════════════════════════════════════════ */\n"
    "#toast {\n"
    "  width: 288px; height: 64px;\n"
    "  right: 22px; top: 20px; z-index: 20;\n"
    "  border-radius: 20px 6px 20px 20px;\n"
    "  backdrop-filter: var(--blur); -webkit-backdrop-filter: var(--blur);\n"
    "  background: linear-gradient(140deg, rgba(255,255,255,.07) 0%, rgba(255,255,255,.03) 100%);\n"
    "  border: 1px solid rgba(255,255,255,.1);\n"
    "  box-shadow: 0 1px 0 rgba(255,255,255,.06) inset, 0 16px 48px rgba(0,0,0,.55), 0 0 26px rgba(168,85,247,.12);\n"
    "  display: flex; align-items: center; gap: 11px; padding: 0 13px;\n"
    "}\n"
    "#toast_icon {\n"
    "  width: 30px; height: 30px; border-radius: 9px; flex-shrink: 0;\n"
    "  background: linear-gradient(135deg, var(--indigo), var(--violet));\n"
    "  box-shadow: 0 4px 12px rgba(99,102,241,.45);\n"
    "}\n"
    "#toast_body { flex: 1; min-width: 0; }\n"
    "#toast_title { color: var(--text-1); font-size: 12px; font-weight: 700; letter-spacing: -.01em; }\n"
    "#toast_msg   { color: var(--text-2); font-size: 10.5px; margin-top: 1px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }\n"
    "#toast_close {\n"
    "  width: 11px; height: 11px; border-radius: 50%; flex-shrink: 0;\n"
    "  background: rgba(255,95,87,.65); cursor: pointer;\n"
    "  transition: background .12s;\n"
    "}\n"
    "#toast_close:hover { background: #ff5f57; }\n"
    "\n"
    "/* ══════════════════════════════════════════\n"
    "   INFO WINDOW\n"
    "══════════════════════════════════════════ */\n"
    "#info_win {\n"
    "  width: 264px; height: 162px;\n"
    "  left: 22px; bottom: 22px; z-index: 15;\n"
    "  backdrop-filter: var(--blur); -webkit-backdrop-filter: var(--blur);\n"
    "  background: linear-gradient(140deg, rgba(255,255,255,.065) 0%, rgba(255,255,255,.022) 100%);\n"
    "  border: 1px solid rgba(99,102,241,.18);\n"
    "  box-shadow: 0 1px 0 rgba(255,255,255,.06) inset, 0 18px 55px rgba(0,0,0,.55), 0 0 28px rgba(99,102,241,.07);\n"
    "  display: flex; flex-direction: column; align-items: center;\n"
    "  padding-top: 34px; position: absolute;\n"
    "}\n"
    "#info_close {\n"
    "  position: absolute; left: 13px; top: 13px;\n"
    "  width: 11px; height: 11px; border-radius: 50%;\n"
    "  background: rgba(255,95,87,.65); cursor: pointer;\n"
    "  transition: background .12s;\n"
    "}\n"
    "#info_close:hover { background: #ff5f57; }\n"
    "#info_icon {\n"
    "  width: 40px; height: 40px; border-radius: 50%; flex-shrink: 0;\n"
    "  background: linear-gradient(135deg, rgba(52,211,153,.72), rgba(5,150,105,.62));\n"
    "  box-shadow: 0 0 16px rgba(52,211,153,.4), 0 0 0 5px rgba(52,211,153,.1);\n"
    "}\n"
    "#info_title {\n"
    "  margin-top: 9px; color: var(--text-1);\n"
    "  font-family: var(--font-d); font-size: 13px; font-weight: 700; letter-spacing: -.01em;\n"
    "}\n"
    "#info_msg {\n"
    "  margin-top: 6px; padding: 0 16px;\n"
    "  color: var(--text-2); font-size: 11px; line-height: 1.55; text-align: center;\n"
    "}\n"
    "#info_link {\n"
    "  margin-top: 7px; color: var(--cyan); font-size: 10px; font-weight: 600;\n"
    "  letter-spacing: .05em; text-decoration: underline; cursor: pointer;\n"
    "  text-shadow: 0 0 10px rgba(34,211,238,.4);\n"
    "}\n"
    "\n"
    "/* ══════════════════════════════════════════\n"
    "   DOCK\n"
    "══════════════════════════════════════════ */\n"
    "#dock {\n"
    "  width: 228px; height: 58px;\n"
    "  left: 50%; bottom: 20px; transform: translateX(-50%);\n"
    "  z-index: 30;\n"
    "  backdrop-filter: var(--blur); -webkit-backdrop-filter: var(--blur);\n"
    "  background: rgba(255,255,255,.042);\n"
    "  border: 1px solid rgba(255,255,255,.1);\n"
    "  box-shadow: 0 1px 0 rgba(255,255,255,.07) inset, 0 10px 40px rgba(0,0,0,.55);\n"
    "  display: flex; align-items: center; justify-content: center;\n"
    "  gap: 7px; padding: 0 12px;\n"
    "}\n"
    ".dock_icon {\n"
    "  width: 38px; height: 38px; border-radius: 11px;\n"
    "  cursor: pointer; display: flex; align-items: center; justify-content: center;\n"
    "  font-size: 13px; font-weight: 800; color: #fff; position: relative;\n"
    "  transition: transform .15s cubic-bezier(.34,1.56,.64,1);\n"
    "}\n"
    ".dock_icon:hover { transform: scale(1.2) translateY(-8px); }\n"
    ".dock_icon:first-child { border-radius: 19px 11px 11px 19px; }\n"
    ".dock_icon:last-child  { border-radius: 11px 19px 19px 11px; }\n"
    ".dock_label { display: none; }\n"
    "\n"
    "/* ══════════════════════════════════════════\n"
    "   MODAL\n"
    "══════════════════════════════════════════ */\n"
    "#modal_overlay {\n"
    "  inset: 0; z-index: 100;\n"
    "  background: rgba(0,0,6,.72);\n"
    "  backdrop-filter: blur(6px);\n"
    "  display: flex; align-items: center; justify-content: center;\n"
    "}\n"
    "#modal_dialog {\n"
    "  width: 350px; position: relative;\n"
    "  backdrop-filter: blur(36px) saturate(1.8); -webkit-backdrop-filter: blur(36px) saturate(1.8);\n"
    "  background: linear-gradient(145deg, rgba(255,255,255,.09) 0%, rgba(255,255,255,.03) 100%);\n"
    "  border: 1px solid rgba(255,255,255,.12);\n"
    "  box-shadow: 0 1px 0 rgba(255,255,255,.07) inset, 0 28px 80px rgba(0,0,0,.7), 0 0 40px rgba(99,102,241,.1);\n"
    "  display: flex; flex-direction: column; align-items: center;\n"
    "  padding: 28px 22px 20px; gap: 0;\n"
    "}\n"
    "#modal_icon {\n"
    "  width: 44px; height: 44px; border-radius: 14px;\n"
    "  background: linear-gradient(135deg, var(--indigo), var(--violet));\n"
    "  box-shadow: 0 6px 22px rgba(99,102,241,.45), 0 0 0 6px rgba(99,102,241,.1);\n"
    "}\n"
    "#modal_title {\n"
    "  margin-top: 14px; color: var(--text-1);\n"
    "  font-family: var(--font-d); font-size: 15px; font-weight: 700; letter-spacing: -.02em;\n"
    "}\n"
    "#modal_msg {\n"
    "  margin-top: 7px; color: var(--text-2);\n"
    "  font-size: 12px; line-height: 1.6; text-align: center;\n"
    "}\n"
    ".modal_btn {\n"
    "  height: 34px; border-radius: var(--r-md); font-size: 12px; font-weight: 700;\n"
    "  letter-spacing: .03em; cursor: pointer;\n"
    "  display: flex; align-items: center; justify-content: center;\n"
    "  width: 100%; transition: .14s; user-select: none;\n"
    "}\n"
    ".modal_btn.cancel  { background: var(--surface); border: 1px solid var(--border-hi); color: var(--text-2); margin-top: 18px; }\n"
    ".modal_btn.cancel:hover { background: var(--surface-hi); color: var(--text-1); }\n"
    ".modal_btn.confirm { background: linear-gradient(135deg, var(--indigo), var(--violet)); color: #fff; box-shadow: 0 4px 16px rgba(99,102,241,.4); margin-top: 7px; }\n"
    ".modal_btn.confirm:hover { box-shadow: 0 6px 22px rgba(99,102,241,.55); transform: translateY(-1px); }\n"
    ".modal_btn.confirm:active { transform: translateY(0); }\n"
    "\n"
    "/* ── Luna UI engine overlays (scrollbars, a11y) ── */\n"
    ".luna_sb_track {\n"
    "  position: absolute;\n"
    "  background: rgba(99,102,241,0.10);\n"
    "  border-radius: 3px;\n"
    "  pointer-events: none;\n"
    "}\n"
    ".luna_sb_thumb {\n"
    "  position: absolute;\n"
    "  background: rgba(99,102,241,0.42);\n"
    "  border-radius: 3px;\n"
    "  pointer-events: none;\n"
    "  transition: background 0.12s;\n"
    "}\n"
    ".luna_sb_thumb:hover, .luna_sb_v:hover, .luna_sb_h:hover {\n"
    "  background: rgba(99,102,241,0.62);\n"
    "}\n"
    ".luna_a11y {\n"
    "  position: absolute;\n"
    "  background: rgba(12,12,22,0.92);\n"
    "  border: 1px solid rgba(99,102,241,0.22);\n"
    "  border-radius: 10px;\n"
    "  color: rgba(230,232,255,0.92);\n"
    "  font-size: 12px;\n"
    "  font-weight: 500;\n"
    "  padding: 0 14px;\n"
    "  display: flex;\n"
    "  align-items: center;\n"
    "  box-shadow: 0 8px 28px rgba(0,0,0,0.45);\n"
    "  border-left: 4px solid var(--indigo);\n"
    "  z-index: 12000;\n"
    "}\n"
    ".luna_a11y_assertive { border-left-color: #f59e0b; }\n"
    "\n"
    "/* ── Global ── */\n"
    "::selection { background: rgba(99,102,241,.32); color: #fff; }\n"
    ":focus-visible { outline: 2px solid rgba(99,102,241,.5); outline-offset: 2px; }\n"
    "::-webkit-scrollbar { width: 4px; height: 4px; }\n"
    "::-webkit-scrollbar-track { background: transparent; }\n"
    "::-webkit-scrollbar-thumb { background: rgba(99,102,241,.3); border-radius: 2px; }\n"
    "@media (prefers-reduced-motion: reduce) {\n"
    "  *, *::before, *::after { animation-duration: .01ms !important; transition-duration: .01ms !important; }\n"
    "}\n"
